### ISSUE TITLE
报错额，好像是字符错误？

### ISSUE THREAD

**Issue by lovingfrank** [Tai7sy/card-system#1]
![default](https://user-images.githubusercontent.com/3955860/34511596-dfabccd6-f097-11e7-90ef-e04944f150b5.png)
网站打开也是
 Parse error: syntax error, unexpected '?' in /home/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

用宝塔安装的，Nginx1.12 php5.6.32 mysql5.5.54

**Comment by Tai7sy** [comment]
由于使用了laravel框架，对php版本有要求，建议更新php版本

**Comment by ShuiPingYang** [comment]
用了php5不支持的语法，？？是php7的语法。你把php升级到7以上就可以了

**Comment by lovingfrank** [comment]
升级了php7可以了
