### ISSUE TITLE
支付驱动未找到

### ISSUE THREAD

**Issue by cnluminous** [Tai7sy/card-system#100]
为什么吧易支付的SDK拿来用会提示这个？放在/libary/pay文件夹里的

**Comment by Tai7sy** [comment]
需要单独对接，并不是放进去就能用

**Comment by cnluminous** [comment]
请问下，发卡系统有独立查单页面吗？

**Comment by Tai7sy** [comment]
目前没有，有需求可以定做

**Comment by cnluminous** [comment]
现在有其他模板吗？还是说现在只有2个

**Comment by Tai7sy** [comment]
没有

**Comment by cnluminous** [comment]
在请问下，如何修改/?theme=Material#buy下面的版权信息？我想把备案号加进去，改哪里？

**Comment by Tai7sy** [comment]
前端文件位于 `public/dist` 目录

直接目录全局搜索 `@2019` 自己修改即可

**Comment by cnluminous** [comment]
好的感谢

**Comment by cnluminous** [comment]
没有找到前端文件啊

**Comment by cnluminous** [comment]
只有index_dev.html和文件夹

**Comment by cnluminous** [comment]
index_dev.html也没有@2019

**Comment by cnluminous** [comment]
dalao能不能留下QQ？github说有点不方便

**Comment by Tai7sy** [comment]
都说了目录搜索, 你非要在文件里面搜
在 js 里面

**Comment by cnluminous** [comment]
grep @2019 /www/wwwroot/faka.cnluminous.com/public/dist/js/*
也搜不出来啊.搜文件也没有

**Comment by Tai7sy** [comment]
那个字符不是`@`

**Comment by cnluminous** [comment]
是©吧？

**Comment by cnluminous** [comment]
请问下定做独立查单页面多少钱？

**Comment by Tai7sy** [comment]
QQ: 1.9.0.6.0
email: @qq.com
