### ISSUE TITLE
风铃大佬 小微商户微信扫码支付能添加个参数吗

### ISSUE THREAD

**Issue by cjiasu** [Tai7sy/card-system#102]
![UO 6R%9~O9J BUZ6(OX3WC7](https://user-images.githubusercontent.com/40857324/60380421-04df3200-9a78-11e9-83c3-1338b1c79f97.png)

就差一个 sub_mch_id 参数   这是子服务商ID  求添加

**Comment by jihuoxia** [comment]
小微商户能实现吗，不可能吧

**Comment by Tai7sy** [comment]
2.8已经支持, 在配置里面增加`sub_mch_id`字段即可
