### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by andhub-cn** [Tai7sy/card-system#103]
您好，

1. 极验目前不允许个人用户注册 不开放注册，希望可以修改验证码平台

2. 希望后台可以开启强制用户购买时候填写邮箱，可以避免部分用户填写联系方式不认真导致无法查询卡密，发送到邮箱记录一直再

3. 如何修改模板，有无添加新模板计划

**Comment by Tai7sy** [comment]
暂时没有修改验证码平台的打算
最新版已经支持限制联系方式格式以及单独配置邮件发送
新模板计划暂无, 模板目录位于`resource/views/shop_theme`, 可以自行修改
