### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#104]
1.建议增加微信支付的 服务商-小微子商户支付，和paypal支付。
2.经典主题左下角有个1，后台怎么设置都去不掉，估计是模板上的事
3.有赞支付接口是不是不能用了，最近微店支付比较火，最好能接上微店支付

**Comment by Tai7sy** [comment]
小微子商户已经支持, paypal很早之前已经支持
经典主题的`1`已经修复
微店支付暂时不会接入, 有需求可以定制
