### ISSUE TITLE
一个问题及反馈

### ISSUE THREAD

**Issue by yi-shiyu** [Tai7sy/card-system#107]
某个商品，指定联系方式只填写邮箱的话。联系方式中的灰色提示字，在选中这个商品的时候会变成“请输入邮箱，用于查询账单”，再选中别的商品，字不会变回去那个输入QQ、手机号什么的那个提起字。还有这个短信是怎么收费的，一条多少费用呢

**Comment by Tai7sy** [comment]
具体哪个主题, 可否给个链接查看, 这边没有复现出来
详情可以测试 http://123.207.240.190/

**Comment by yi-shiyu** [comment]
主题是material 按钮式。几个商品之中有一个联系方式指定仅能填邮箱。来回点击几个商品，提示文字不会变动了。别的商品的提示也变成了“请输入邮箱，用于查询账单”

**Comment by yi-shiyu** [comment]
短信的话，多少钱一条的

**Comment by yi-shiyu** [comment]
还有那个微信小微账户也可以用native支付吗

**Comment by Tai7sy** [comment]
> 短信的话，多少钱一条的

短信接口不定期变动, 以最终扣费为准, 最高不会不超过0.1


> 还有那个微信小微账户也可以用native支付吗

这个没有测试, 请自行测试

**Comment by Tai7sy** [comment]
> 主题是material 按钮式。几个商品之中有一个联系方式指定仅能填邮箱。来回点击几个商品，提示文字不会变动了。别的商品的提示也变成了“请输入邮箱，用于查询账单”

没有测试出此种情况
