### ISSUE TITLE
风铃大佬,想知道短信接口直接在后台申请,后台充值就行了是嘛?

### ISSUE THREAD

**Issue by iddddg** [Tai7sy/card-system#108]
那费用是怎么计费的呢?还有我看到商品详情上显示自动发货,请问能在后台设置为手动发货嘛?

**Comment by Tai7sy** [comment]
短信接口较为复杂，以最终扣费为准，不会超过0.1，后台设置0.1可以保证盈余。
手动发货功能别人有定制的，暂不开放

**Comment by iddddg** [comment]
好的,明白,谢谢
