### ISSUE TITLE
增加小微商户支持(自行增加sub_mch_id选项)，这个怎么弄啊

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#109]
能不能在支付驱动里显示出来，我们填参数就可以用的。
另外，建议支付ID及密钥之类的，弄成保存后不显示，或者显示成星星，复制也不能复制出来。
这样在多人操作后台的时候，可以防止支付参数泄露造成隐患。最好在数据库也查看不了

**Comment by Tai7sy** [comment]
- -,  你后台都给人家了, 补单什么的都能操作了

**Comment by jihuoxia** [comment]
操作会有记录的，查看密钥不显示记录，隐藏密钥还是很有必要的。
这个自行增加sub_mch_id选项是要到源码里改吗

**Comment by Tai7sy** [comment]
支付渠道里面改

**Comment by jihuoxia** [comment]
是在源码里支付渠道那一块 还是直接在网站后台支付渠道里添加

**Comment by Tai7sy** [comment]
网站后台支付渠道里添加

**Comment by yi-shiyu** [comment]
这个有参考教程吗

**Comment by iLay1678** [comment]
大概是这样改
![Screenshot_20190721_191640.jpg](https://i.loli.net/2019/07/21/5d3449b8908c069424.jpg

**Comment by Tai7sy** [comment]
已经加入配置说明
https://github.com/Tai7sy/card-system/tree/master/app/Library/Pay/WeChat
