### ISSUE TITLE
逻辑优化建议

### ISSUE THREAD

**Issue by andhub-cn** [Tai7sy/card-system#112]
当设置购买预留信息仅限邮箱时候，勾选了邮件通知时还需要再一次填写邮箱，希望优化下，一次购买无须连续两次输入邮箱

**Comment by Tai7sy** [comment]
这是考虑到了通知邮箱和查询购买邮箱可能不一致的问题

**Comment by NBY** [comment]
能不能只输入一次邮箱，屏蔽那个邮件通知按钮，没升级之前输入邮箱自动发邮件通知挺好用的，升级之后多一步操作反而更繁琐了。

**Comment by Tai7sy** [comment]
@NBY
这个考虑到了联系方式限定了QQ号，手机号等情况下需要发送到邮箱的问题，有什么好的建议可以继续提一下

**Comment by NBY** [comment]
后台编辑商品页面中，买家信息如果选择了只能输入邮箱后加个选项，选择提醒邮件默认发到联系方式OR额外填写提醒邮件收件地址？

**Comment by Tai7sy** [comment]
目前如果联系方式填写了邮箱，
当选中发送到邮箱选项，是会自动使用联系方式填写的邮箱

**Comment by NBY** [comment]
我试了一下，好像没有发送提醒邮件到联系方式的邮箱，选邮件提醒才会有邮件通知。能不能加个选项屏蔽一下邮件提醒按钮？

**Comment by Tai7sy** [comment]
后台取消邮箱发送功能就可以了

**Comment by NBY** [comment]
不不不。。。我是说屏蔽那个邮件提醒按钮，直接发送邮件到联系方式填的那个邮箱地址。或者有啥办法能降级到之前版本么？

**Comment by Tai7sy** [comment]
@NBY 新版本(2.92)已经加入一个选项了，感谢建议
