### ISSUE TITLE
 Class DatabaseSeeder does not exist 

### ISSUE THREAD

**Issue by zeus911** [Tai7sy/card-system#124]
Migrating: 2019_06_04_214122_modify_cards_created_at
Migrated:  2019_06_04_214122_modify_cards_created_at
Migrating: 2019_06_17_185712_add_options_to_shop_theme
Migrated:  2019_06_17_185712_add_options_to_shop_theme
Migrating: 2019_06_18_112211_add_manual_products
Migrated:  2019_06_18_112211_add_manual_products
Migrating: 2019_07_03_213426_add_sms_price_to_orders
Migrated:  2019_07_03_213426_add_sms_price_to_orders

In Container.php line 752:
                                       
  Class DatabaseSeeder does not exist  
                                       
数据库中没有建管理员账号

**Comment by Tai7sy** [comment]
请按照安装教程进行安装

**Comment by Tai7sy** [comment]
![Snipaste_2019-08-23_10-11-29.png](https://i.loli.net/2019/08/23/5jWzm1IePpJAsla.png)

刚测试了一切正常

**Comment by zeus911** [comment]
我是直接下载的线上版本。是否是这个问题
