### ISSUE TITLE
构建数据库一直出现错误

### ISSUE THREAD

**Issue by 602269640** [Tai7sy/card-system#125]
![QQ截图20190907152135](https://user-images.githubusercontent.com/29164714/64471348-49c3cb00-d183-11e9-8521-eff82f540a14.png)
一直出现这个错误不知道怎么解决

**Comment by Tai7sy** [comment]
请自己搜索错误内容，这里不是谷歌百度

**Comment by 602269640** [comment]
已经解决了，谢谢


------------------ 原始邮件 ------------------
发件人: "风铃"<notifications@github.com>;
发送时间: 2019年9月7日(星期六) 下午4:09
收件人: "Tai7sy/card-system"<card-system@noreply.github.com>;
抄送: "🐽"<602269640@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tai7sy/card-system] 构建数据库一直出现错误 (#125)




请自己搜索错误内容，这里不是谷歌百度
