### ISSUE TITLE
加卡数量可否自定义

### ISSUE THREAD

**Issue by maxzhang666** [Tai7sy/card-system#128]
目前是分段上传
但是每次100个

想问下这个100能否自定义
js源码未找到

**Comment by Tai7sy** [comment]
这个100也是为了兼容考虑，很多没设置php post大小限制，然后卡密又很长，各种报错

**Comment by maxzhang666** [comment]
不知道前端js源码是否开源？
我想自定义一下，卡密上万的时候很费时间

**Comment by Tai7sy** [comment]
在 /public/dist/ 内的某个js文件里面, 可以在目录中搜索 100 关键字

**Comment by maxzhang666** [comment]
> 在 /public/dist/ 内的某个js文件里面, 可以在目录中搜索 100 关键字

哇这可难为死我了。。。。8个文件搜了一下167个结果
