### ISSUE TITLE
在网站根目录进行php artisan key:generate操作时提示 putenv() has been disabled for security reasons

### ISSUE THREAD

**Issue by mengyalei** [Tai7sy/card-system#129]
在网站根目录进行php artisan key:generate操作时提示 putenv() has been disabled for security reasons
操作环境：
Centos7.3X64
宝塔6.9.9
Nginx 1.15.10
PHP7.2 
MySql5.7.26
phpMyAmin4.7

**Comment by Tai7sy** [comment]
这个自己搜索解决
