### ISSUE TITLE
默认新主题 优惠码bug

### ISSUE THREAD

**Issue by ZHQSM** [Tai7sy/card-system#130]
新主题 下  设置优惠码 用于某一个商品  选择该商品 输入优惠码后 再选择其他商品 同样可以享有该优惠。  原经典主题不存在这个问题。

**Comment by Tai7sy** [comment]
能否发一下截图我看下

**Comment by ZHQSM** [comment]
![image](https://user-images.githubusercontent.com/45648920/66182642-84e4eb80-e6a8-11e9-9d07-2cb91bf6ca52.png)

**Comment by ZHQSM** [comment]
优惠码 用于月卡 季度卡 半年卡  先选择月卡 输入优惠码 在点不能使用的无限年卡   仍然有折扣效果

**Comment by Tai7sy** [comment]
感谢反馈，将与下个版本进行修复
