### ISSUE TITLE
Payjs支付方式

### ISSUE THREAD

**Issue by liyehuicn** [Tai7sy/card-system#132]
Payjs支付方式是native吗？

**Comment by liyehuicn** [comment]
![360截图-203602708](https://user-images.githubusercontent.com/22151489/66699570-a2eec380-ed1a-11e9-8694-1e3398a64378.jpg)
这样填对吗

**Comment by Tai7sy** [comment]
这个是payjs内的方式，请参考payjs文档

**Comment by Tai7sy** [comment]
目前支持 native和cashier
