### ISSUE TITLE
请教一下大佬，当面付不显示二维码何解？

### ISSUE THREAD

**Issue by zhanghaozhijia** [Tai7sy/card-system#136]
当使用当面付的时候，生成的二维码不显示
请求 x.com/api/qrcode/query/7 报500错误

**Comment by zhanghaozhijia** [comment]
这个问题好像只存在于chrome浏览器

**Comment by Tai7sy** [comment]
500错误
storage/logs 里面有错误详细内容, 可以自行参考解决, 或者附录log文件
