### ISSUE TITLE
 请问一下大佬, 在执行 php artisan migrate:fresh --seed 时报错.

### ISSUE THREAD

**Issue by SanJingYe88** [Tai7sy/card-system#138]
请问一下大佬, 在执行 php artisan migrate:fresh --seed 时报错. 如下, 是什么原因呢?

  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using pas  
  sword: YES) (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')

**Comment by Prk123Studio** [comment]
您好，请检查数据库配置是否正常
