### ISSUE TITLE
添加卡密报错

### ISSUE THREAD

**Issue by ceecx** [Tai7sy/card-system#142]
应该是卡密数量过多导致的问题
![20191105170843](https://user-images.githubusercontent.com/18570103/68193994-21274880-ffef-11e9-8ce7-d99f117e474d.png)

**Comment by Tai7sy** [comment]
请附上日志方便定位问题

**Comment by ceecx** [comment]
[card-2019-11-05.log](https://github.com/Tai7sy/card-system/files/3808143/card-2019-11-05.log)

**Comment by Tai7sy** [comment]
这个是添加过于频繁触发了后台的防CC, 不要开多个窗口同时添加

**Comment by ceecx** [comment]
> 这个是添加过于频繁触发了后台的防CC, 不要开多个窗口同时添加

只开了一个窗口。。应该是卡密数量太多导致吧，而且添加速度有些慢。

**Comment by Tai7sy** [comment]
后台限制已经很宽松了, 1分钟内限制120个请求

**Comment by Tai7sy** [comment]
添加卡密处, 前端限制是1秒内添加10次, 每次添加100张卡密, 
后面改成1000张看一下吧 (可自行在public/dist目录内搜索"添加卡密结束" 关键字找到上面的100改掉)

但是这样可能会触发最大post大小限制导致你一次都不成功

**Comment by ceecx** [comment]
> 添加卡密处, 前端限制是1秒内添加10次, 每次添加100张卡密,
> 后面改成1000张看一下吧 (可自行在public/dist目录内搜索"添加卡密结束" 关键字找到上面的100改掉)
> 
> 但是这样可能会触发最大post大小限制导致你一次都不成功

谢谢，这个问题回头测试了再反馈。

**Comment by Tai7sy** [comment]
新版本已经修复
