### ISSUE TITLE
如何对接支付接口

### ISSUE THREAD

**Issue by ceecx** [Tai7sy/card-system#144]
https://www.shiling.org/docs/index.html
目前按现有的接口来配置的话貌似不行，能否看一下文档指导一下？

**Comment by Tai7sy** [comment]
需要自己写接口
开发文档: 
https://github.com/Tai7sy/card-system/wiki/%E6%94%AF%E4%BB%98%E6%8E%A5%E5%8F%A3%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3
