### ISSUE TITLE
支付宝当面付弹窗问题

### ISSUE THREAD

**Issue by ceecx** [Tai7sy/card-system#146]
因为在支付二维码下面会有红包码，用户可以选择是否扫红包码，弹窗有点多此一举。觉得这个弹窗可以关闭，我看别人的接口也没有弹窗，是否可以修改接口配置关闭？

![image](https://user-images.githubusercontent.com/18570103/68310184-8875f300-00ea-11ea-982e-4ae241d72837.png)

![image](https://user-images.githubusercontent.com/18570103/68310273-afccc000-00ea-11ea-8b12-194b7f238238.png)

**Comment by fyglinfo** [comment]
/resources/views/pay/aliqr.blade.php
删除下面
 <div id="myModal" class="modal">
        
        <div class="modal-content">
            <span class="close" id="dialog-close">&times;</span>
            <img src="https://s2.ax1x.com/2019/06/20/Vj4sWq.jpg" style="max-width: 100%"/>
        </div>

    </div>
</div>

**Comment by ceecx** [comment]
> /resources/views/pay/aliqr.blade.php
> 删除下面
> 
> ```
> <div id="myModal" class="modal">
>         
>         <div class="modal-content">
>             <span class="close" id="dialog-close">&times;</span>
>             <img src="https://s2.ax1x.com/2019/06/20/Vj4sWq.jpg" style="max-width: 100%"/>
>         </div>
> 
>     </div>
> </div>
> ```

感谢，我还一直以为是自带的我自己的红包码，你这样一发我才知道原来是作者的。。。

**Comment by Tai7sy** [comment]
此功能 为部分人需要特意联系我加的, 默认的红包码子我放了自己的, 
可以删掉或者替换(搜索 `https://s2.ax1x.com/2019/06/20/Vj4sWq.jpg` 替换即可)
