### ISSUE TITLE
【已自行解决】邮件服务不可用

### ISSUE THREAD

**Issue by ceecx** [Tai7sy/card-system#147]
用的阿里云实例和邮件推送服务，默认25端口貌似是不能用的，所以用他们的465端口，防火墙已经打开。

如果不使用加密，值为null，提示超时：
![image](https://user-images.githubusercontent.com/18570103/68324025-879c8b80-0101-11ea-892b-193114b26ed8.png)

如果使用加密，值为ssl，报错信息：
![image](https://user-images.githubusercontent.com/18570103/68324171-ccc0bd80-0101-11ea-820e-ca8b42710d21.png)

实例上安装了邮局系统可能有点冲突，已自行解决。

**Comment by ceecx** [comment]
邮局是用的阿里云邮件推送服务。

**Comment by ceecx** [comment]
已测试阿里云邮件推送服务提供不加密的80端口也不可用

**Comment by ceecx** [comment]
才搭建一天，发现不少问题，作者会持续维护吗？确定用的话应该是不会频繁换程序了，但是目前BUG好像有点多，只希望不是三分钟热度，我会支持的，长期用更愿意打赏，祝好。

**Comment by qq514444957** [comment]
老哥我也是这样的  这可咋解决哦
