### ISSUE TITLE
邮件功能貌似有问题啊

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#148]
我用的SMTP发邮件
试了一个QQ邮箱和一个网易邮箱，465端口，在两台不同的服务器上，都发不成功

这俩邮箱我在相同的服务器上别的发卡程序上测试发件正常

提示是这样的   timeout of 15000ms exceeded

**Comment by Tai7sy** [comment]
timeout of 15000ms exceeded 是 15秒后端尚未返回结果的错误
有可能是连不上邮件服务器导致的
详细错误可以查看 storage/logs 下日志

**Comment by ceecx** [comment]
Server 是否安装邮局系统？如果没有的话 检查防火墙 是否开启所需端口
或者你的信息填写不正确 仔细检查你的 SMTP

**Comment by jihuoxia** [comment]
正常了
