### ISSUE TITLE
商品购买件数限制问题

### ISSUE THREAD

**Issue by ceecx** [Tai7sy/card-system#149]
有的商品是需要手动发货的，卡密我就随便添加了可复用的一条，商品单次就变成只能购买一件了。
客户想给我赞助，我设置了一个专门的 0.1 元赞助商品，如果一次客户需要购买多件就不行，除非我批量添加很多卡密，但是卡密数量太多就遇到 [这个 Issues](https://github.com/Tai7sy/card-system/issues/142) 的问题。尽管没有问题，可能效率也会有些低。

**Comment by Tai7sy** [comment]
此限制的初衷是为了避免正常情况用户购买商品发现买了两次只有一张卡的问题
后面取消强制限制改为可调购买限制

**Comment by ceecx** [comment]
> 此限制的初衷是为了避免正常情况用户购买商品发现买了两次只有一张卡的问题
> 后面取消强制限制改为可调购买限制

![image](https://user-images.githubusercontent.com/18570103/68749989-1fd2cd00-063a-11ea-9420-38ad71375d8d.png)

现在这种情况可以修改哪个文件解决？谢谢

**Comment by Tai7sy** [comment]
现在这种情况的修改涉及核心发货逻辑 需要大量修改测试

**Comment by ceecx** [comment]
> 现在这种情况的修改涉及核心发货逻辑 需要大量修改测试

如果这种方式需要改动大量代码的话，那会不会区分自动和手动发货商品比较好下手呢？自动发货就按照目前逻辑，额外添加手动发货逻辑分类。

**Comment by Tai7sy** [comment]
手动发货已经有了, 目前缺少测试, 没有开启

**Comment by ceecx** [comment]
> 手动发货已经有了, 目前缺少测试, 没有开启

目前版本里有吗？我可以先行测试再反馈。

**Comment by Tai7sy** [comment]
有的

**Comment by ceecx** [comment]
> 有的

该如何开启？

**Comment by Tai7sy** [comment]
新版本已经实现此功能, 感谢反馈
