### ISSUE TITLE
建议多邮箱发件

### ISSUE THREAD

**Issue by Insightfy** [Tai7sy/card-system#150]
有些邮局用的多就会黑，qq什么的就收不到了。建议可以配置多邮局，随机发送这样。
谢谢风铃大佬无私奉献。
（鞠躬

**Comment by Insightfy** [comment]
刚接触 发现有些刚需的貌似没有涉及。就是在线客服 Crisp/mylivechat这些的 可以整合进去然后后台可以进行选择之类的。方便卖家快速响应。另外我想问问footer文件在那个路径啊QAQ 太菜了，找了半天没找到。谢谢大佬

**Comment by Tai7sy** [comment]
在线客服这些都是第三方代码, 自己加到统计代码或者客服代码里面就OK了

**Comment by Insightfy** [comment]
好的 已经成功。谢谢大佬。辛苦
