### ISSUE TITLE
错误代码 self-invoke-forbidden 错误原因: 此用户不允许自调用

### ISSUE THREAD

**Issue by ldxw** [Tai7sy/card-system#152]
![自调用](https://user-images.githubusercontent.com/25827746/69617563-587b9900-1073-11ea-91a2-8659a3667fde.PNG)
新版电脑手机版支付的 可以加上这个不。。

**Comment by ldxw** [comment]
创建的第三方应用就会这样。。

**Comment by Tai7sy** [comment]
新版电脑手机版支付, 驱动为 AliAop, 方式可选 pc(电脑) / mobile(手机) / f2f (当面付)

**Comment by ldxw** [comment]
> 新版电脑手机版支付，驱动为AliAop，方式任选pc（PC）/ mobile（手机）/ f2f（当面付）

![支付](https://user-images.githubusercontent.com/25827746/69638905-963de900-1096-11ea-9a07-03ab8647c952.PNG)
默认就是这个，只能用当面付，新版电脑跟手机那个就会显示自调用，

`isv.self-invoke-forbidden（此用户不允许自调用）
报错描述：isv.self-invoke-forbidden（此用户不允许自调用）
报错原因：如果您在调用蚂蚁金服接口出现这个错误，说明您请求的appid属于第三方应用不允许自己appid请求蚂蚁金服接口。简单来说：如果您出现这个报错说明这个appid不可以直接自己调用。 
解决方案： 
1、创建一个自用型应用来自用； 
2、通过第三方应用授权，获取到商户授权的app_auth_token之后，在第三方应用进行接口请求的时候传入app_auth_token，代替商户发起请求。
说明：对于历史应用，不受影响，新创建的应用受影响。 `

**Comment by Tai7sy** [comment]
说明你开的可能有问题, 建议联系支付宝询问下, 这边都是正常的
