### ISSUE TITLE
安装成功就是后台上传图片访问404 

### ISSUE THREAD

**Issue by heihuo8** [Tai7sy/card-system#153]
目录里面也有图片 新建其他格式文本也能访问 唯独图片404 麻烦风铃大佬 教一下解决办法。我百度了很多。

**Comment by heihuo8** [comment]
我保证是按照 BT安装顺序走的。安装了 4次

**Comment by cnluminous** [comment]
apache还是nginx

**Comment by Tai7sy** [comment]
bt面板的默认 nginx 配置存在错误
需要删除配置文件中  png/jpg 的那一块配置文件

**Comment by heihuo8** [comment]
噢。。谢谢大佬 我等你好久了。。我想问问风铃大佬 接定制么？ 我想对接易支付。

**Comment by heihuo8** [comment]
需要删除配置文件中 png/jpg 的那一块配置文件 。。我比较傻逼能提示一下在哪个位子么 叫啥名来着

**Comment by Tai7sy** [comment]
location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log /dev/null;
    }

**Comment by heihuo8** [comment]
谢谢您 已经解决了
