### ISSUE TITLE
风铃大佬这里有点懵后台也没地方设置

### ISSUE THREAD

**Issue by heihuo8** [Tai7sy/card-system#154]
![微信截图_20191127195545](https://user-images.githubusercontent.com/58242425/69721672-53404c00-1150-11ea-894f-475bcdc645ae.png)

后台没有设置logo的地方。。还有这个 投诉订单

**Comment by cnluminous** [comment]
你这是哪一年的版本了 。。新版本已经没有了啊。。

**Comment by Tai7sy** [comment]
logo只能在数据库修改app_logo字段
