### ISSUE TITLE
更新2.95c 版本后 500 错误

### ISSUE THREAD

**Issue by ceecx** [Tai7sy/card-system#156]
后台正常登陆，前台也能打开，但是购买不了，启用新主题首页直接提示‘未知错误，请联系客服’，购买跳转和启用新主题一样的错误。
[card-2019-12-01.log](https://github.com/Tai7sy/card-system/files/3907291/card-2019-12-01.log)

**Comment by ceecx** [comment]
另外有没有主题开发文档？没事可以折腾折腾

**Comment by ceecx** [comment]
购买时报错 Logs
[Uploading card-2019-12-01 (1).log…]()

**Comment by ceecx** [comment]
请风铃大佬告知如何回退旧版本？因为我没备份就直接升级了，导致现在服务不可用，损失不少。。

**Comment by Tai7sy** [comment]
部分主题尚未更新完毕, 你这是使用了新主题的原因, 请先不要使用新主题, 等下才会发布新版
第二个错误是由于你没有按照正常逻辑更新, 导致Gateway文件缺失

**Comment by ceecx** [comment]
> 部分主题尚未更新完毕, 你这是使用了新主题的原因, 请先不要使用新主题, 等下才会发布新版
> 第二个错误是由于你没有按照正常逻辑更新, 导致Gateway文件缺失

我没有第一时间看到文档的更新教程，后台看到有更新直接就执行 update 了。。。现在该如何？

**Comment by ceecx** [comment]
我应该可以按文档重新更新一遍最新？

**Comment by Tai7sy** [comment]
2.95d 已经发布修复主题问题, 更新即可

**Comment by ceecx** [comment]
已更新到 2.95e

**Comment by Tai7sy** [comment]
> 已更新到 2.95e

刚才版本发错了一个, 建议重新更新, 更新方法:
修改 `app/Providers/ConfigServiceProvider.php` 里面的版本信息(如搜索版本号`2.95`)替换为低版本的版本号

然后重新执行命令行即可重新更新

**Comment by ceecx** [comment]
> > 已更新到 2.95e
> 
> 刚才版本发错了一个, 建议重新更新, 更新方法:
> 修改 `app/Providers/ConfigServiceProvider.php` 里面的版本信息(如搜索版本号`2.95`)替换为低版本的版本号
> 
> 然后重新执行命令行即可重新更新

![image](https://user-images.githubusercontent.com/18570103/69909885-f5a44c00-143c-11ea-9e3f-4e017f8e41d9.png)
