### ISSUE TITLE
如何搭配全站CDN避免攻击？

### ISSUE THREAD

**Issue by ceecx** [Tai7sy/card-system#158]
近期老是被恶意攻击，几天跑了1000多G流量，损失有点大。想用国内等服务商的全站CDN，目前配置完成会自动跳转到源站域名，是否和伪静态有关？采用CF的CNAME方式接入则是没有问题，但是速度太慢。

**Comment by Tai7sy** [comment]
配置CDN按照一般步骤就可以, 这个程序没有什么特殊步骤

**Comment by ceecx** [comment]
也有可能是国内服务商的全站CDN部署方面和CF不太一样，但是用CF是减速，目前还没有想到更好的安全方案。

**Comment by Tai7sy** [comment]
很多用的阿里云腾讯云等全站加速，并没有问题
