### ISSUE TITLE
IE11 报错 缺少标识符、字符串或数字

### ISSUE THREAD

**Issue by Hzbeta** [Tai7sy/card-system#16]
IE内核都无法打开网站，提示错误：
SCRIPT1010: 缺少标识符
manifest.ee2fd8cade10e3f1aaf9.js (1,1251)
SCRIPT1028: 缺少标识符、字符串或数字
vendor.9b836c99da247ece1703.js (1,13487)
SCRIPT1010: 缺少标识符
app.4cca40a2daa378a776d7.js (1,2993)
是不是Webpack导致的？希望能修复一下！

**Comment by Tai7sy** [comment]
Ver 1.4
 - support IE11

**Comment by dingpei** [comment]
同问，引入babel-polyfill都不行
