### ISSUE TITLE
建议能够创建多个用户

### ISSUE THREAD

**Issue by cnluminous** [Tai7sy/card-system#160]
如题，多个用户管理一个网站，数据表内添加数据就成了一站多户的样子了

**Comment by Tai7sy** [comment]
多用户版本可以参考商业版演示站点

**Comment by cnluminous** [comment]
我是能够希望多个用户管理同一个店铺的。

**Comment by Tai7sy** [comment]
那你直接后台账号密码给他不就行了。。。

**Comment by cnluminous** [comment]
呢好的。
再请问一个问题，我使用阿里云全站加速后，后台统计功能失效，提示
The given data was invalid.
{"day":["The day field is required."]}

**Comment by Tai7sy** [comment]
这个建议联系阿里云排查问题

**Comment by cnluminous** [comment]
好的

**Comment by Prk123Studio** [comment]
您好，创建多账户可以通过修改数据库的方法修改，切记做之前要备份数据库！修改方式如下：登录到你的MySQL的后台，即phpMyAdmin，通过账号密码进入到后台之后，从左侧找到数据库名点击进去，可直接来到users数据表中，对id为1的数据表点击左侧(Edit编辑 Copy复制 Delete删除)中的Copy复制，id这里改成2，email改成你要登录的邮箱,mobile手机号可两个一致，切记，password密码的加密形式不要乱改，你可以先把主账号的密码改成要设置第二个账号的密码查看到密文填写进来，随后主账号密码可以改回去，最后的关键就是remember_token的数值第二个账号要比第一个加一，然后按下Go，保存后再试试后台登录就可以登录啦~
