### ISSUE TITLE
支付成功后跳转错误

### ISSUE THREAD

**Issue by cnluminous** [Tai7sy/card-system#162]
使用安发卡API支付，支付成功后跳转错误，使用cdn，域名正确，二级域名错误

**Comment by Tai7sy** [comment]
请上传错误截图

**Comment by cnluminous** [comment]
我的网站为shop.cnluminous.com
点击查询订单时就会出现问题

**Comment by cnluminous** [comment]
网站域名:shop.cnluminous.com
跳转域名:all.cnluminous.com

**Comment by Tai7sy** [comment]
请检查你的系统设置里面的api网址是否填写正确

**Comment by cnluminous** [comment]
设置正确了

**Comment by cnluminous** [comment]
![image](https://user-images.githubusercontent.com/47070284/71444770-d0121600-274e-11ea-8bee-acfdf0c8de64.png)

**Comment by Tai7sy** [comment]
试了下你的站正常的啊

**Comment by cnluminous** [comment]
我是为了能够正常使用，把all.cnluminous.com也绑定到nginx上了

**Comment by Tai7sy** [comment]
已确认是阿里云泛域名cdn引起，请添加全域名。
预计下个版本修复此问题

**Comment by Tai7sy** [comment]
新版本已修复此问题
https://github.com/Tai7sy/card-system/releases/tag/3.0
