### ISSUE TITLE
邮箱发送邮件错误

### ISSUE THREAD

**Issue by xinxinjiushizhu** [Tai7sy/card-system#163]
截图：
没动过设置，一直可以发送，昨天开始突然无法发送邮件了

**Comment by Tai7sy** [comment]
自己看下文件夹权限是否出问题

**Comment by xinxinjiushizhu** [comment]
权限是777

**Comment by xinxinjiushizhu** [comment]
![image](https://user-images.githubusercontent.com/52072126/71305288-5c010680-240c-11ea-9b2b-20644873abcd.png)

**Comment by Tai7sy** [comment]
777是没问题的, 那试一下把那个文件删掉试一下, 那是邮件模板缓存

**Comment by xinxinjiushizhu** [comment]
可以了，谢谢风铃大佬
