### ISSUE TITLE
两个后面页面报错：后台/商品管理/商品分类、后台/商品管理/商品列表

### ISSUE THREAD

**Issue by liwenchao1984** [Tai7sy/card-system#166]
后台这两处页面报错，均提示：未知错误，请联系客服

**Comment by liwenchao1984** [comment]
如图：

**Comment by liwenchao1984** [comment]
Uncaught error {"exception":"[object] (RuntimeException(code: 0): Missing BC Math or GMP extension. at /var/www/html/vendor/hashids/hashids/src/Math.php:2)
[stacktrace]
#0 /var/www/html/vendor/hashids/hashids/src/Hashids.php(2): Hashids\\Math::mod(2226203566, 100)
#1 /var/www/html/app/Library/Helper.php(2): Hashids\\Hashids->encode(2226203566, 5, 450215437, 2)
#2 /var/www/html/app/Product.php(2): App\\Library\\Helper::id_encode(5, 2)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(2): App\\Product->getUrlAttribute(NULL)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(2): Illuminate\\Database\\Eloquent\\Model->mutateAttribute('url', NULL)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(2): Illuminate\\Database\\Eloquent\\Model->mutateAttributeForArray('url', NULL)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2): Illuminate\\Database\\Eloquent\\Model->attributesToArray()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(2): Illuminate\\Database\\Eloquent\\Model->toArray()
#8 [internal function]: Illuminate\\Support\\Collection->Illuminate\\Support\\{closure}(Object(App\\Product))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Collection.php(2): array_map(Object(Closure), Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Pagination/LengthAwarePaginator.php(2): Illuminate\\Support\\Collection->toArray()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pagination/LengthAwarePaginator.php(2): Illuminate\\Pagination\\LengthAwarePaginator->toArray()
#12 [internal function]: Illuminate\\Pagination\\LengthAwarePaginator->jsonSerialize()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(2): json_encode(Array, 0)
#14 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(2): Illuminate\\Http\\JsonResponse->setData(Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(2): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 200, Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(2): Illuminate\\Http\\JsonResponse->__construct(Array, 200, Array, 0)
#17 /var/www/html/app/Library/Response.php(2): Illuminate\\Routing\\ResponseFactory->json(Array, 200, Array, 0)
#18 /var/www/html/app/Library/Response.php(2): App\\Library\\Response::json(Array)
#19 /var/www/html/app/Http/Controllers/Merchant/Product.php(2): App\\Library\\Response::success(Object(Illuminate\\Pagination\\LengthAwarePaginator))
#20 [internal function]: App\\Http\\Controllers\\Merchant\\Product->get(Object(Illuminate\\Http\\Request))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(2): call_user_func_array(Array, Array)
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(2): Illuminate\\Routing\\Controller->callAction('get', Array)
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Merchant\\Product), 'get')
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\Route->runController()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Route->run()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 120, '1')
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#56 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/html/app/Http/Middleware/CORS.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): App\\Http\\Middleware\\CORS->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#79 /var/www/html/public/index.php(2): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#80 {main}
","method":"POST","url":"http://card.fxxf.online/api/admin/product","data":"category_id=-1&search=name&val=&current_page=1&per_page=10","ip":"120.228.126.248","client_ip":"172.17.0.1","headers":{"cookie":["UM_distinctid=16ed9f6615058-0d45ce2151aa69-4d045769-1fa400-16ed9f661513f3; _ga=GA1.2.23833436.1576204267; CNZZDATA1272914459=379748575-1577330306-%7C1577330306; customer=300b53891af6d127af0a0e6ccb921560; laravel_session=eyJpdiI6Ijlydm5weTBhcWVCY2JIZjlkNlk0YlE9PSIsInZhbHVlIjoiK2phRUlQM3ZRaEhHVTNESGdwMmRib2hvWHA2eFp6aHVCVGhuT28yVmtlRnpKWDlrdjNVd0lXalhoeFdhK1RndiIsIm1hYyI6IjEyMjg4NzdiZjY1ZTE1Nzk5OTI1NjllYzEzODkzYjcyZTkyNDQxZmFiZmVjNjIyMDc2MTBmNmJmZmU3YzI0MjkifQ%3D%3D; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IlE2ckhRSllHY1kyWkdXTEdKclFldHc9PSIsInZhbHVlIjoiVUZXVjFiXC9Cb1JERytXK1RZV0VrcmRWNjZ6bjFXSk1kMk5CbmpwdjA5XC9QOHA3MTB0eEZYaGY0aEZaTEd0aFB2THNkQ09NMUxEWEhiU1YzSzlSQkR0MGRaZVYzdmV2S3dpN2piRHJ0WkZmWnpLRG1OTGdMVGhqSDdRRHdHM2ZLeFg5YkVKTUh2dkVYdnVlU21SRGV5SGRlSGJ1TVJzZnljb2RMajE0aU9tMkk9IiwibWFjIjoiYzNkZjNlODhiYTc4MDA4OWUxYjAzNWIzZTZkZDc5NjNhNWYwNjhiNDFhOTRkNDQ5ZjlkMmM0MDYxMjMwNjI2MyJ9; admin_free-token=login"],"accept-language":["zh-CN,zh;q=0.8"],"accept-encoding":["gzip, deflate"],"referer":["http://card.fxxf.online/admin/product/list"],"content-type":["application/x-www-form-urlencoded"],"user-agent":["Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 SE 2.X MetaSr 1.0"],"x-requested-with":["XMLHttpRequest"],"x-xsrf-token":["4G6WW2JeE6GpPBY6dFSmNJbbZe44mZyc"],"origin":["http://card.fxxf.online"],"accept":["application/json, text/plain, */*"],"content-length":["58"],"connection":["close"],"x-forwarded-for":["120.228.126.248"],"x-real-ip":["120.228.126.248"],"host":["card.fxxf.online"]}}

**Comment by Tai7sy** [comment]
字面意思
 Missing BC Math or GMP extension.
缺少bc_math或gmp插件

**Comment by liwenchao1984** [comment]
感谢Tai7sy， 按照你的思路已解决。

我的运行情况是docker容器alpine linux里的php+nginx，缺少这个bc math扩展。
处理方式如下两行代码解可：

cd /usr/local/bin  
./docker-php-ext-install php-bcmath

(原理：该镜像的/usr/local/bin目录下有一个docker-php-ext-install程序专门用来安装php扩展)
