### ISSUE TITLE
關於買家收取郵件功能

### ISSUE THREAD

**Issue by WooSih** [Tai7sy/card-system#169]
能否在郵件內加入商品的「使用說明」？

**Comment by WooSih** [comment]
![g](https://s2.ax1x.com/2020/01/01/lJZQbR.png)
就是買家收取的郵件不只顯示卡密，還顯示這個說明

**Comment by Tai7sy** [comment]
上传一下邮件截图

**Comment by WooSih** [comment]
![截圖](https://user-images.githubusercontent.com/58901924/71642542-f0f6e000-2ce7-11ea-997c-4271dc3e3430.png)

**Comment by Tai7sy** [comment]
新版本已经发布
https://github.com/Tai7sy/card-system/releases/tag/3.0
