### ISSUE TITLE
库存显示错误

### ISSUE THREAD

**Issue by Hzbeta** [Tai7sy/card-system#17]
如果手动添加已售出的卡密，在显示库存时，不能识别成已售出，本来是5/100，加入一个已售出卡密，仍然为5/100
     希望能修复一下

**Comment by Tai7sy** [comment]
商品个数是自己设置的, 和卡密数量没有关系

**Comment by Hzbeta** [comment]
但是原来是5/100，添加一个以出售的，应该是6/100啊，不能正确显示已出售多少

**Comment by Hzbeta** [comment]
解决了，添加了一个定时任务，用来更新已售出的数量
