### ISSUE TITLE
如何修改后台登录地址/admin？

### ISSUE THREAD

**Issue by baiguke2019** [Tai7sy/card-system#170]
如题
还有个问题是 如何修改支付宝当面付，付款时的那个扫码红包？

**Comment by Tai7sy** [comment]
后台地址不支持修改, 不知道你修改的动机是什么, 如果不想让人黑进后台, 正确的办法应该设置一个复杂的密码

当面付问题可以参考如下替换成自己的或删除:
https://github.com/Tai7sy/card-system/issues/146
