### ISSUE TITLE
能不能加上多语言支持，用户可以多语言切换的功能

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#171]
能不能加上多语言支持，用户可以多语言切换的功能，做国外客户用得着

**Comment by Tai7sy** [comment]
```
<div id="google_translate_element" style="position:fixed;bottom:64px;right:6px;z-index:2000;opacity:0.7"></div><script>
  function googleTranslateElementInit() {
    new google.translate.TranslateElement(
      {
        pageLanguage: 'zh-CN',
        includedLanguages: 'en,zh-CN,hr,cs,da,nl,fr,de,el,iw,hu,ga,it,ja,ko,pt,ro,ru,sr,es,th,vi',
        layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
        autoDisplay: true, 
      },
      'google_translate_element'
    );
   }
</script>
<script src="https://translate.google.cn/translate_a/element.js?cb=googleTranslateElementInit"></script>
```

可以将以上代码粘贴到 统计代码中 即可实现多语言功能

**Comment by jihuoxia** [comment]
> ```
> <div id="google_translate_element" style="position:fixed;bottom:64px;right:6px;z-index:2000;opacity:0.7"></div><script>
>   function googleTranslateElementInit() {
>     new google.translate.TranslateElement(
>       {
>         pageLanguage: 'zh-CN',
>         includedLanguages: 'en,zh-CN,hr,cs,da,nl,fr,de,el,iw,hu,ga,it,ja,ko,pt,ro,ru,sr,es,th,vi',
>         layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
>         autoDisplay: true, 
>       },
>       'google_translate_element'
>     );
>    }
> </script>
> <script src="https://translate.google.cn/translate_a/element.js?cb=googleTranslateElementInit"></script>
> ```
> 
> 可以将以上代码粘贴到后台设置的 "客服代码" 或 "统计代码" 中，即可实现多语言功能

这个代码好像不是谷歌内核的浏览器不生效啊

**Comment by Tai7sy** [comment]
> ```
> <div id="google_translate_element" style="position:fixed;bottom:64px;right:6px;z-index:2000;opacity:0.7"></div><script>
>   function googleTranslateElementInit() {
>     new google.translate.TranslateElement(
>       {
>         pageLanguage: 'zh-CN',
>         includedLanguages: 'en,zh-CN,hr,cs,da,nl,fr,de,el,iw,hu,ga,it,ja,ko,pt,ro,ru,sr,es,th,vi',
>         layout: google.translate.TranslateElement.InlineLayout.SIMPLE,
>         autoDisplay: true, 
>       },
>       'google_translate_element'
>     );
>    }
> </script>
> <script src="https://translate.google.cn/translate_a/element.js?cb=googleTranslateElementInit"></script>
> ```
> 
> 可以将以上代码粘贴到后台设置的 "客服代码" 或 "统计代码" 中，即可实现多语言功能

已知bug: 
1. 输入框的placeholder不会自动翻译(属于Google插件问题)
2. 不分主题风格元素宽高翻译后变形问题

需要修改部分布局尝试兼容Google translator插件

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/wiki/%E5%A4%9A%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81
