### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by yi-shiyu** [Tai7sy/card-system#173]
在
https://xxx.com/pay/result/订单号
这个网址所在的模板中，那个查看订单详情的href网址应该是指向自己的。少了一个:，变成https//xxx.com/pay/result/订单号

**Comment by Tai7sy** [comment]
这个网址是你网站设置里面填写的url

**Comment by yi-shiyu** [comment]
后台设置中的网站设置里面的地址是没填错的https://vlan.run/pay/result/202001151537566BPUp

**Comment by Tai7sy** [comment]
感谢反馈，下个版本将会修复此问题

**Comment by Tai7sy** [comment]
新版本3.01已修复
