### ISSUE TITLE
更新后，后台登录提示错误

### ISSUE THREAD

**Issue by xinxinjiushizhu** [Tai7sy/card-system#176]
![image](https://user-images.githubusercontent.com/52072126/72682918-73b3d380-3b0d-11ea-8f68-aeb98aab3dfd.png)

**Comment by Tai7sy** [comment]
请贴日志文件

**Comment by xinxinjiushizhu** [comment]
emmm,没有了，我重装回了2.94，我用命令更新后网站打开提示503，我重装了3.01导入数据库 就提示的这个

**Comment by xinxinjiushizhu** [comment]
我使用另一个服务器 重复了操作，安装3.01导入2.95数据库后，后台登录错误日志
#52 {main}
","method":"POST","url":"http://maoruan.xyz/api/admin/auth/login","data":"email=200672576%40qq.com&password=haoran1997&&remember=false","ip":"34.92.159.32","client_ip":"34.92.159.32","headers":{"connection":["close"],"cookie":["customer=10715b8d22ea308881d20990aa384186; UM_distinctid=16fbe5bbdd912c-091275314e35c6-b383f66-1fa400-16fbe5bbddacce; CNZZDATA1272914459=889885597-1579444859-null%7C1579444859"],"accept-language":["zh-CN,zh;q=0.9,en;q=0.8,und;q=0.7"],"accept-encoding":["gzip, deflate"],"referer":["http://maoruan.xyz/admin/auth/login"],"content-type":["application/x-www-form-urlencoded"],"user-agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"],"x-requested-with":["XMLHttpRequest"],"x-xsrf-token":["p2bQfDKTaMtsbXXeMTGFA78AFapK5rT2"],"origin":["http://maoruan.xyz"],"accept":["application/json, text/plain, */*"],"content-length":["60"],"host":["maoruan.xyz"]}}

**Comment by Tai7sy** [comment]
高版本和低版本数据库无法直接导入
请使用
php artisan migrate
命令升级数据库
