### ISSUE TITLE
更新失败...

### ISSUE THREAD

**Issue by xinxinjiushizhu** [Tai7sy/card-system#177]
![image](https://user-images.githubusercontent.com/52072126/72685031-ec705b00-3b20-11ea-9c3b-7b3059232afa.png)
更新后，打开网站提示这个
使用sudo php artisan update命令更新的

**Comment by Tai7sy** [comment]
请提供日志文件

**Comment by iddddg** [comment]
同2.95e版本,执行sudo php artisan update命令后,网站显示当前服务不可用,,请稍后重试.
storage/logs/下清空当天日志,重新访问,不产生日志
再次执行sudo php artisan update,会显示如下
```
[root@ecs-001 centos]# sudo php artisan update
sh: /www/server/php/73/etc/php: No such file or directory
sh: /www/server/php/73/etc/php: No such file or directory

检查更新中...
当前版本: 3.01
最新版本: 3.01
版本说明: -
-
--------- 注意 ---------
本次更新可能会更新失败
更新失败后再次更新即可!!!
更新失败后再次更新即可!!!
-
-
您的版本已是最新!

 是否再次更新 (yes/no) [no]:
 > yes

正在下载新版本...
    download: 100.00%
正在解压...
正在关闭主站...
sh: /www/server/php/73/etc/php: No such file or directory
 --> 正在清理旧文件...
 --> 正在复制新文件...
 --> 正在创建缓存...
sh: /www/server/php/73/etc/php: No such file or directory
sh: /www/server/php/73/etc/php: No such file or directory
sh: /www/server/php/73/etc/php: No such file or directory
 --> 正在更新数据库...
sh: /www/server/php/73/etc/php: No such file or directory
 --> 正在设置目录权限...
正在启用主站...
sh: /www/server/php/73/etc/php: No such file or directory
sh: /www/server/php/73/etc/php: No such file or directory
清理临时目录...
更新成功!
```

**Comment by iddddg** [comment]
@Tai7sy 还有其他地方日志可以看吗?

**Comment by iddddg** [comment]
@Tai7sy 
问题似乎找到了，环境CentOS7，宝塔7。
出现这个问题是因为你的Update.php文件第4行：
exec($spd07be9 . ' cache:clear');这一句之前,获取到的变量$spd07be9值是"/www/server/php/73/etc/php" "artisan"，后面exec执行就是"/www/server/php/73/etc/php" "artisan"  cache:clear，没有在网站根目录下所以报错sh: /www/server/php/73/etc/php: No such file or directory
我偷懒重新赋值成php astisan，然后重新更新网站就好了。

**Comment by Tai7sy** [comment]
属于bug 更新时获取php路径出错导致, 部分宝塔环境会有此问题

**Comment by Tai7sy** [comment]
新版本3.02已发布
尝试兼容部分宝塔面板的设置获取php路径
