### ISSUE TITLE
MySQL 老是自动停止 

### ISSUE THREAD

**Issue by baiguke2019** [Tai7sy/card-system#179]
MySQL 三天两头老是自动停止  导致网站访问失败 未知错误 联系客服 500
换了2台机器都是这个问题
vps环境
MySQL 5.7.28
PHP-7.3
Nginx 1.16.1
配置 1g1h
大佬请帮我看下是vps问题吗？

**Comment by Tai7sy** [comment]
mysql停止不是网站问题, 网站权限无法使mysql关闭
