### ISSUE TITLE
用Material的主题，网站被百度收录后，前面会多个“购买商品”?

### ISSUE THREAD

**Issue by uubxs** [Tai7sy/card-system#185]
Material这个主题很喜欢，大佬能否教我如何删除网站名称前面多出来的“购买商品”？

**Comment by Tai7sy** [comment]
发张截图看一下

**Comment by uubxs** [comment]
<a href="https://sm.ms/image/PZA4fn5r8Kx7c6C" target="_blank"><img src="https://i.loli.net/2020/02/08/PZA4fn5r8Kx7c6C.png" ></a>
<a href="https://sm.ms/image/Mv2yhP8SYVKzsHf" target="_blank"><img src="https://i.loli.net/2020/02/08/Mv2yhP8SYVKzsHf.png" ></a>

**Comment by uubxs** [comment]
上图标签页显示，
下图百度收录的截图。

**Comment by Tai7sy** [comment]
你好歹给个带文字的...商品名称可以F12改一下啊

**Comment by uubxs** [comment]
截图是收录的 网站首页：www.XXX.com，   查询记录边上的“购买商品”我会改，但是标签页这个没找到。百度收录的时候网站名前面也就多了“购买商品”

**Comment by Tai7sy** [comment]
这个啊, 这个建议`public\dist\js`
目录里面搜索 "window.document.title=xxx"的字样 删掉

**Comment by uubxs** [comment]
大佬果真是大佬，感谢！试过loc坛子几套开源发卡程序，还是大佬的最好用！
这个主题可以提点儿建议吗：
1.公告栏能显示卖家QQ，后台设置开关显示（自己弄的苹果手机和电脑打开的代码不一样，只能分开挂的链接）
2.罗列的 商品名称可以有超链接功能，直接有点击 具有后面“购买”的效果
3.商品分类可以设置显示 商品名称 的数量，太多的话可以点击“加载更多”
说的有点儿多，大佬自行采纳。 晚安！
