### ISSUE TITLE
3.0的更新方式可以用2.x系列的方法升级吗？

### ISSUE THREAD

**Issue by zhujitop** [Tai7sy/card-system#186]
升级到3.2之后，在后台只要一刷新就退出了，要重新登录。

使用了阿里云的CDN，缓存也配置了/admin文件夹不缓存的。

还有登录日志都是这样：
请下载qqwry.dat放在app/Library/QQWry目录下

**Comment by Tai7sy** [comment]
想要不退出请点击记住密码,另外登陆日志的提示是哪里有不懂的吗
