### ISSUE TITLE
建议：增加一个查询密码

### ISSUE THREAD

**Issue by Lifestrive** [Tai7sy/card-system#188]
购买商品时候填写查询密码和联系方式，作为主要查询方式，联系方式为辅助方式！

**Comment by Tai7sy** [comment]
联系方式本身就起到了密码的作用, 再多增加有什么意义呢

**Comment by mengxuan619** [comment]
> 联系方式本身就起到了密码的作用, 再多增加有什么意义呢

确实建议增加一个查询密码，现在只要有联系方式就能查询，有的人潜伏在QQ群里面，用群里面的QQ去挨个查，能查到订单的。

**Comment by Tai7sy** [comment]
> > 联系方式本身就起到了密码的作用, 再多增加有什么意义呢
> 
> 确实建议增加一个查询密码，现在只要有联系方式就能查询，有的人潜伏在QQ群里面，用群里面的QQ去挨个查，能查到订单的。

可以尝试将联系方式限定为手机号

**Comment by BOTBAKS** [comment]
以前联系方式改成手机号挺安全的，但是最近出了个可以通过QQ号查手机号，现在卡密总是被盗

**Comment by Tai7sy** [comment]
3.13 已加入此功能
