### ISSUE TITLE
更新完所有数据都被覆盖

### ISSUE THREAD

**Issue by jack8788** [Tai7sy/card-system#194]
更新后所有数据都消失了，全部需要重新上架

**Comment by Tai7sy** [comment]
更新逻辑不会对数据库进行操作

**Comment by jack8788** [comment]
商品和卡密信息没有保存到数据库中，所有更新后这些都没了

**Comment by Tai7sy** [comment]
不保存在数据库存在哪里？ 你搞笑的吗

**Comment by jack8788** [comment]
搞错了，是保存到数据库，但是更新后数据库也更新了，运行的命令是php artisan update，提前备份的数据库也显示导入失败，，不知道什么原因！

**Comment by Tai7sy** [comment]
那我也不知道什么原因 抱歉
