### ISSUE TITLE
有没有想过接入stripe接口？

### ISSUE THREAD

**Issue by menglicl** [Tai7sy/card-system#195]
如题

**Comment by Tai7sy** [comment]
这个接入微信支付宝也要国内审核吧

**Comment by menglicl** [comment]
https://www.payssion.com/这个好像不需要

**Comment by menglicl** [comment]
> 这个收件人微信支付宝也要国内审核吧
https://www.payssion.com    这个平台不错，不需要国内审核，支持支付宝，微信，银联卡

**Comment by Tai7sy** [comment]
大佬业务都扩展到全球了完全可以找人收费对接啊.....
