### ISSUE TITLE
商品介绍加入图片代码之后会乱码

### ISSUE THREAD

**Issue by zhujitop** [Tai7sy/card-system#196]
商品介绍里面想加个图片，但是发现不能调整大小，我就手动用图片代码：
`<img src="xxx.jpg" width="100" height="100">`
保存商品之后，去前台看商品详情，整个都乱码了。

换行直接显示了\n
图片代码img src之后也都不显示了。

**Comment by Tai7sy** [comment]
商品介绍是delta格式，并不是html

**Comment by zhujitop** [comment]
> 商品介绍是delta格式，并非html

还有支付宝的面对面支付，在支付的时候会先弹出来让扫红包，要付款用户总得手动去关闭红包那个提示，这个设置支付宝可以解决吗？
之前用zfaka那个系统没这个情况。

**Comment by Tai7sy** [comment]
> > 商品介绍是delta格式，并非html
> 
> 还有支付宝的面对面支付，在支付的时候会先弹出来让扫红包，要付款用户总得手动去关闭红包那个提示，这个设置支付宝可以解决吗？
> 之前用zfaka那个系统没这个情况。

这个可以issue里面搜一下，有方法关闭或者替换成自己的
至于图片大小下个版本预计会增加调整功能

**Comment by Tai7sy** [comment]
图片大小功能已经加入
