### ISSUE TITLE
实际付款金额小于订单金额

### ISSUE THREAD

**Issue by mengxuan619** [Tai7sy/card-system#197]
大佬您好，最近用您的发卡程序对接了一个支付接口，当短时间多次下单时，支付平台那边的逻辑是订单金额-0.01 ，但是卡网程序判定实际金额小于订单金额不发货。

已咨询支付平台不支持改动
您这边应该怎么改？或者有哪里可以设置

**Comment by mengxuan619** [comment]
然后再反应个bug，我这边更新新版本后 自写的支付接口 改的支付页面的html 全被覆盖了

**Comment by Tai7sy** [comment]
这个改动比较危险了，买家如果拦截了订单几百块的修改为 0.01这个风险怎么办呢

**Comment by Tai7sy** [comment]
> 然后再反应个bug，我这边更新新版本后 自写的支付接口 改的支付页面的html 全被覆盖了

自己修改了文件的话建议备份，更新逻辑很简单删除旧的覆盖新的。。。

**Comment by mengxuan619** [comment]
> 这个改动比较危险了，买家如果拦截了订单几百块的修改为 0.01这个风险怎么办呢

感谢大佬回复，钻了个空子，把逻辑改成了支付金额+0.1 这样暂时解决了

**Comment by mengxuan619** [comment]
> > 然后再反应个bug，我这边更新新版本后 自写的支付接口 改的支付页面的html 全被覆盖了
> 
> 自己修改了文件的话建议备份，更新逻辑很简单删除旧的覆盖新的。。。

了解。感谢回复

**Comment by Tai7sy** [comment]
> 这个改动比较危险了，买家如果拦截了订单几百块的修改为 0.01这个风险怎么办呢

这个问题你可以在自己的支付渠道对接的时候传递需要的金额(比如订单需要的金额)而不是买家实际付款的金额(当然这样可能会不安全)
