### ISSUE TITLE
使用升级命令出现错误，网站无法打开

### ISSUE THREAD

**Issue by 928882650** [Tai7sy/card-system#198]
是否现在更新 (yes/no) [no]:
 > yes

正在下载新版本...
    download: 100.00%
正在解压...
正在关闭主站...
 --> 正在清理旧文件...
 --> 正在复制新文件...
 --> 正在创建缓存...

In Application.php line 2:
                                                             
  Class 'Intervention\Image\ImageServiceProvider' not found  
                                                             
这个文件在哪也找不到，现在卡网打开提示当前服务不可用，请稍后重试

**Comment by Tai7sy** [comment]
重新更新一次即可
