### ISSUE TITLE
金额为0的订单下单后，不跳转成功页面

### ISSUE THREAD

**Issue by mojieitanshi** [Tai7sy/card-system#199]
/pay/result/202002230522380dtQw

订单已经成功了，但是自动跳转页面显示这个。
![image](https://user-images.githubusercontent.com/19925379/75099724-dfeb9080-55ff-11ea-813a-25cb56795487.png)

**Comment by Tai7sy** [comment]
是不是nginx之类的反代之类的cdn之类的配置问题？
本来应该跳转到这个网址你这个没有跳

**Comment by mojieitanshi** [comment]
就挂了一个cloudflare,2.x版本似乎没问题

风铃 <notifications@github.com> 于 2020年2月23日周日 上午10:18写道：

**Comment by Tai7sy** [comment]
看你这个url, 应该是下单的url吧，不需要支付直接成功的么

**Comment by mojieitanshi** [comment]
> 看你这个url, 应该是下单的url吧，不需要支付直接成功的么

是的，使用优惠券百分百优惠。然后就这样了，是不是bug？

**Comment by mojieitanshi** [comment]
> 看你这个url, 应该是下单的url吧，不需要支付直接成功的么
经过我的测试，即使不使用cloudflare，还是那个问题，就是用百分百的优惠券购买产品，页面不会跳转，只会显示要跳转的网址信息

**Comment by Rong1998** [comment]
哥，我还没有搞懂这个怎么弄，就一个订单号和卡密，求解

**Comment by Tai7sy** [comment]
> 哥，我还没有搞懂这个怎么弄，就一个订单号和卡密，求解

这个bug下个版本修复

**Comment by Rong1998** [comment]
> > 哥，我还没有搞懂这个怎么弄，就一个订单号和卡密，求解
> 
> 这个bug下个版本修复

那哥，我现在能干啥，电脑有急用。要用vpn，有备用的么？

**Comment by mojieitanshi** [comment]
卡密下面有说明

Rong1998 <notifications@github.com> 于2020年3月6日周五 下午11:08写道：

**Comment by mojieitanshi** [comment]
> > 哥，我还没有搞懂这个怎么弄，就一个订单号和卡密，求解
> 
> 这个bug下个版本修复

辛苦大大了，坐等更新~

**Comment by Rong1998** [comment]
> > > 哥，我还没有搞懂这个怎么弄，就一个订单号和卡密，求解
> > 
> > 
> > 这个bug下个版本修复
> 
> 辛苦大大了，坐等更新~

之前看到有安卓版的套餐，我同学也购买了，现在那个购买地址去哪儿了呢？

**Comment by Tai7sy** [comment]
此问题已经修复
