### ISSUE TITLE
风大，能不能添加一些MugglePay

### ISSUE THREAD

**Issue by GillianJiao** [Tai7sy/card-system#203]
MugglePay 不支持支付宝和微信了 ， 但是我发现usdt玩的很舒服，所以希望风大能添加些这样的支付平台。

谢谢

**Comment by Tai7sy** [comment]
MugglePay已经支持了啊
https://github.com/Tai7sy/card-gateway/tree/master/Pay/MugglePay

**Comment by GillianJiao** [comment]
他们现在不让发卡 用支付宝 和 微信收款了  只能用数字货币  现在几个人买东西用数字货币啊  大部分不还是用支付宝和微信支付
