### ISSUE TITLE
风大 幻兮支付 的 设置gateway 问题

### ISSUE THREAD

**Issue by GillianJiao** [Tai7sy/card-system#207]
大佬 设置id 和 key 但是就是找不到gateway 在幻兮支付后台也没有看到，
![25e966927f4379a86b.png](https://www.privacypic.com/images/2020/03/11/25e966927f4379a86b.png)

他们的后台没有看到gateway 的这是  搞一下午 硬是没搞懂

请风大能指明下

谢谢

**Comment by Tai7sy** [comment]
gateway 为你接入的支付的网址, 如 `http://www.example.com/`
