### ISSUE TITLE
码支付接口服务器地址改了，无法使用

### ISSUE THREAD

**Issue by mojieitanshi** [Tai7sy/card-system#209]
![image](https://user-images.githubusercontent.com/19925379/76953217-4fc41100-6949-11ea-8e4e-f9fad0aff749.png)

**Comment by Tai7sy** [comment]
fixed
https://github.com/Tai7sy/card-gateway/commit/a4a12b5053d2f59b1c52777cc59dc923013556a2

**Comment by EighteenWu** [comment]
测试版还是无法使用么，我这边仍然是无法支付

**Comment by Tai7sy** [comment]
自己按照上面的commit修改
