### ISSUE TITLE
是否能支持虚拟主机

### ISSUE THREAD

**Issue by linmiao233** [Tai7sy/card-system#215]
能不能支持虚拟主机安装该源码？

**Comment by Tai7sy** [comment]
本身就是支持的

**Comment by linmiao233** [comment]
> 本身就是支持的

wiki宝塔安装的教程 没有虚拟主机安装的教程
虚拟主机 因为没有终端
无法做购建数据库这一步
php artisan key:generate
php artisan migrate:fresh --seed
php artisan cache:clear
请问有其他的方法代替吗?

**Comment by Tai7sy** [comment]
可以本机构建之后数据库传上去, 一样可以使用的

**Comment by linmiao233** [comment]
> 可以本机构建之后数据库传上去, 一样可以使用的

我没有CentOS。。能不能提供一份安装完的sql?

**Comment by Tai7sy** [comment]
windows osx 都支持,
