### ISSUE TITLE
可否增加一些功能

### ISSUE THREAD

**Issue by wangshenstudio** [Tai7sy/card-system#216]
**1主题的LOGO图片
2可自定义菜单导航**
3自定义页面的发布

**Comment by wangshenstudio** [comment]
以上的LOGO自己修改已经实现了
可以付费更改增加一些开源版的功能，
除了以上可以帮忙增加个coinpayments的支付接口看了对接教程还是不会
还有订单投诉按钮的启用

**Comment by Tai7sy** [comment]
1. 主题的LOGO图片
这个可以在 数据库中systems表中增加app_logo,value为图片URL实现

2. 自定义菜单导航需要对每个主题进行适配, 建议通过公告内容形式实现

3. 订单投诉按钮留在源码中, 是因为前端页面是使用的商业版直接 构建出来, 因此会残留按钮, 实际上逻辑没有打包进去, 所以暂时没法开启
