### ISSUE TITLE
支付宝当面付扫码之前有个广告

### ISSUE THREAD

**Issue by labibaby** [Tai7sy/card-system#227]
大佬您好，我是小白。刚刚接入了支付宝当面付。然后测试了一下，点付款的时候会先弹出一个支付宝红包的广告，必须先关了广告才能扫码付款。
然后我去问了下支付宝技术，他们说这个是网站原因。所以请大佬赐教如何修改或者关闭

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/issues/146

**Comment by labibaby** [comment]
哇靠太感谢作者了。秒回 发卡网还好用。怎么赞赏作者
