### ISSUE TITLE
MugglePay是不是不支持了？

### ISSUE THREAD

**Issue by chennanpo** [Tai7sy/card-system#228]
添加后无效，
费率驱动跟方式到底填写格式是什么？

**Comment by Tai7sy** [comment]
请提供详细信息

**Comment by chennanpo** [comment]
就是TG上的设置绑定都设置好了，但是系统上的设置不知道有没有问题
驱动：MugglePay
方式：COIN
配置：JSON的应用秘匙也填写了

方式有3种，就添加了 3次。。但是支付测试的时候没反应

**Comment by Tai7sy** [comment]
1. 我不知道没有反应是什么意思
2. 建议联系支付方解决问题
