### ISSUE TITLE
当面付和NATIVE支付手机不会显示二维码

### ISSUE THREAD

**Issue by labibaby** [Tai7sy/card-system#229]
遇见了个很奇怪的bug。我用电脑使用当面付和NATIVE支付 可以显示出二维码。用苹果手机也可以，用安卓就不显示NATIVE和当面付二维码，只有码支付的二维码显示正常。求赐教。另外求大佬留个支付宝，本人小白想打赏想大佬

**Comment by Tai7sy** [comment]
那请排查你的安卓手机是否是史前版本

**Comment by labibaby** [comment]
求大佬支付宝。老麻烦您 怪不好意思的

**Comment by Tai7sy** [comment]
pay.his.cat
欢迎老板打赏
