### ISSUE TITLE
请求作者联系方式

### ISSUE THREAD

**Issue by huaqinbo** [Tai7sy/card-system#230]
很欣赏你的程序，想购买商业版，找了很久找不到，请告知联系方式，谢谢

**Comment by Tai7sy** [comment]
qq
1 9 0 6 0

**Comment by huaqinbo** [comment]
Hello！How can I buy the commercial version？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "风铃"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午9:43
收件人: "Tai7sy/card-system"<card-system@noreply.github.com&gt;; 
抄送: "梦开始的地方"<huaqinbo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tai7sy/card-system] 请求作者联系方式 (#230)





 
Closed #230.

**Comment by huaqinbo** [comment]
诚心想购买您的程序，请求购买地址或您的联系方式




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "风铃"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午9:43
收件人: "Tai7sy/card-system"<card-system@noreply.github.com&gt;; 
抄送: "梦开始的地方"<huaqinbo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tai7sy/card-system] 请求作者联系方式 (#230)





 
Closed #230.

**Comment by huaqinbo** [comment]
请问验证的答案

**Comment by huaqinbo** [comment]
加您的QQ 需要验证答案，车牌号是多少




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "风铃"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午9:48
收件人: "Tai7sy/card-system"<card-system@noreply.github.com&gt;; 
抄送: "梦开始的地方"<huaqinbo@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tai7sy/card-system] 请求作者联系方式 (#230)





 
qq
 1 9 0 6 0
 
&mdash;

**Comment by Tai7sy** [comment]
任意填写即可

**Comment by huaqinbo** [comment]
提示答案错误

**Comment by Tai7sy** [comment]
自己再试一次
