### ISSUE TITLE
建立数据库的时候出现这个错误

### ISSUE THREAD

**Issue by CollinsWalker** [Tai7sy/card-system#233]
Parse error: syntax error, unexpected '?' in /www/wwwroot/shop.sharequick.cn/vendor/overtrue/wechat/src/Kernel/Support/Helpers.php on line 2

如何解决

**Comment by Tai7sy** [comment]
请执行`php --version` 查看你的php版本

如果自己不会配置版本建议卸载掉低版本只保留php7.X一个

**Comment by CollinsWalker** [comment]
不好意思打扰了，已经设置了，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "风铃"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 上午10:13
收件人: "Tai7sy/card-system"<card-system@noreply.github.com&gt;; 
抄送: "我数到三就跑，三"<528221428@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tai7sy/card-system] 建立数据库的时候出现这个错误 (#233)





 
请执行php --version 查看你的php版本
 
如果自己不会配置版本建议卸载掉低版本只保留php7.X一个
