### ISSUE TITLE
商品分类和商品列表出现 未知错误，日志如下

### ISSUE THREAD

**Issue by zeuero** [Tai7sy/card-system#239]
","method":"GET","url":"https://kkcfd.cn/api/admin/product?category_id=-1&current_page=1&per_page=10&search=name&val=","data":"","ip":"161.117.178.23","client_ip":"161.117.178.23","headers":{"te":["trailers"],"referer":["https://kkcfd.cn/admin/product/list"],"dnt":["1"],"x-requested-with":["XMLHttpRequest"],"authorization":["Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcGFsYWNlZ2lmdC5jblwvYXBpXC9hZG1pblwvYXV0aFwvbG9naW4iLCJpYXQiOjE1OTAxNjk1MzMsImV4cCI6MTU5MDc3NDMzMywibmJmIjoxNTkwMTY5NTMzLCJqdGkiOiI3VHhnbmdJM0JOdEtsa1BiIiwic3ViIjoxLCJwcnYiOiI4N2UwYWYxZWY5ZmQxNTgxMmZkZWM5NzE1M2ExNGUwYjA0NzU0NmFhIn0.CYFPaeKSkFoaOXUqKbS4aBXA2GQkFFPuMgngGNZ0EIU"],"x-xsrf-token":["5Hsd3Q3MKPQCncG37FBxRzRChi8esQtP"],"accept-encoding":["gzip, deflate, br"],"accept-language":["zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2"],"accept":["application/json, text/plain, */*"],"user-agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0"],"host":["kkcfd.cn"],"content-length":[""],"content-type":[""]}}

**Comment by Tai7sy** [comment]
日志不完整

**Comment by zeuero** [comment]
[card_fpm-fcgi-2020-05-23.log](https://github.com/Tai7sy/card-system/files/4671742/card_fpm-fcgi-2020-05-23.log)

**Comment by zeuero** [comment]
已上传完整日志

**Comment by Tai7sy** [comment]
日志里面第一行就是你的解决方法
```
Missing BC Math or GMP extension
```

请自行安装php扩展
