### ISSUE TITLE
是否可以添加有赞云api支持？

### ISSUE THREAD

**Issue by aimerforreimu** [Tai7sy/card-system#24]
https://laravel-china.org/articles/7014/real-time-account-implementation-scheme-based-on-personal-receipts-with-praise-clouds

比如参考以上方法

**Comment by Tai7sy** [comment]
已添加 下一个版本放出
PS: 这个API很烂, 用户扫码要注册账户, 注册了又不能自动跳到支付网址, 还要再扫一次,
手机QQ扫了只有银行卡支付选项, 其余未测
