### ISSUE TITLE
忘记配置验证码的key和ID就开启了后台登录验证码,如何关闭

### ISSUE THREAD

**Issue by hechuan4** [Tai7sy/card-system#240]
忘记配置验证码的key和ID就开启了后台登录验证码,现在登录不进后台了,求助
数据库表里的systems里的vcode_login改成0或者1都不行

**Comment by Tai7sy** [comment]
修改systems表里面内容之后需要清空缓存配置才可以生效

**Comment by hechuan4** [comment]
谢谢!这样清空缓存吗
cd /www/wwwroot/demo.anfaka.com #这里替换成你的网站目录
rm -rf storage/framework/cache/data/*
php artisan cache:clear
php artisan config:clear
php artisan route:clear
