### ISSUE TITLE
迁移站点，恢复程序和数据库后打不开站

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#246]
这个程序迁移站点该怎么操作。

最新版本的支付那块是可以轮询支付接口吗

**Comment by Tai7sy** [comment]
迁移站点无需其他设置，注意配置目录权限即可

**Comment by jihuoxia** [comment]
> 迁移站点无需其他设置，注意配置目录权限即可

我迁移后打不开500错误，新站点目录权限那俩命令也执行了，数据库和密码也改过了

**Comment by Tai7sy** [comment]
500错误可以参考readme里面路径查找日志文件

**Comment by jihuoxia** [comment]
> 500错误可以参考readme里面路径查找日志文件

这是啥意思，我的老站和新站域名不一样

[2020-06-08 00:07:56] local.ERROR: Uncaught Exception {"Exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught ErrorException: file_exists(): open_basedir restriction in effect. File(/www/wwwroot/原站.com/resources/views/errors/_.blade.php) is not within the allowed path(s): (/www/wwwroot/新站.com/:/tmp/:/proc/) in /www/wwwroot/新站.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:2
Stack trace:
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_exists(): ...', '/www/wwwroot/24...', 2, Array)
#1 /www/wwwroot/新站.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(2): file_exists('/www/wwwroot/ce...')
#2 /www/wwwroot/新站.com/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(2): Illuminate\\Filesystem\\Filesystem->exists('/www/wwwroot/ce...')
#3 /www/wwwroot/新站.com/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(2): Illuminate\\View\\FileViewFinder->findInPaths('errors._', Array)
#4 /www/wwwroot/新站.com/vendor/laravel/framework/src/Illuminate/View/Factory.php(2): Ill at /www/wwwroot/新站.com/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:2)
[stacktrace]
#0 {main}
"}

**Comment by Tai7sy** [comment]
请配置跨站权限，如果是宝塔，请参考安装教程进行配置

**Comment by jihuoxia** [comment]
> 请配置跨站权限，如果是宝塔，请参考安装教程进行配置

防跨站已经关闭了，是宝塔，目录权限那俩命令也执行了，伪静态，运行目录，都对着类，还是500错误

**Comment by jihuoxia** [comment]
要重新执行php artisan migrate:fresh --seed这个命令吗，那迁移过来的数据就没了啊

**Comment by Tai7sy** [comment]
按照首页说明清空一下缓存配置试一下, 你这个感觉是路径错误了
