### ISSUE TITLE
支付方式图片路径错误

### ISSUE THREAD

**Issue by hiCasper** [Tai7sy/card-system#248]
当用户使用 https:/example.com/p/xxxxxx 的方式直达商品或者分类链接时，支付方式（如支付宝）的图片路径为 “plugins/images/ali.png”，造成实际请求路径为“https:/example.com/p/plugins/images/ali.png”，出现404错误，无法加载图片。

**Comment by Tai7sy** [comment]
支付方式图片是后台自己输入的, 自己网址前面加斜杠
"/plugins/images/ali.png"
