### ISSUE TITLE
大佬求指教

### ISSUE THREAD

**Issue by Shirooooo** [Tai7sy/card-system#25]
Fatal error: Uncaught ReflectionException: Class config does not exist in /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Container/Container.php:752 Stack trace: #0 /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('config') #1 /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('config') #2 /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('config', Array) #3 /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('config', Array) #4 /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): Illuminate\Foundation\Application->make('config', Array) #5 /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(272): app('config') in /www/wwwroot/card-system/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752

访问网站和ip都这样显示
是什么问题如何解决

**Comment by Tai7sy** [comment]
env配置文件错误
