### ISSUE TITLE
建议加入一个向卖家发送邮件的功能

### ISSUE THREAD

**Issue by cnluminous** [Tai7sy/card-system#250]
建议加入一个向卖家发送邮件的功能，买家购买物品后向卖家发送订单号信息，无需卡密

**Comment by Tai7sy** [comment]
需求场景是什么呢, 如果是为了提醒, 设置库存预计即可

**Comment by cnluminous** [comment]
方便确认订单信息，有些时候在外面，买家购买卡密错误的时候方便确认订单信息

**Comment by Tai7sy** [comment]
那可以随时登录后台查看，比起登录邮箱来说登录后台应该不是很麻烦吧。。。
后台做了分辨率自适应，手机端应该可以比较方便的查看

**Comment by cnluminous** [comment]
虽然做了自适应，但是网址太长不方便输。邮箱的话一般就是直接软件，查看也方便

**Comment by Tai7sy** [comment]
输网址这种事情不应该书签或者首字母打上自动联想的吗...



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cnluminous"<notifications@github.com&gt;; 
发送时间: 2020年6月28日(星期天) 晚上9:24
收件人: "Tai7sy/card-system"<card-system@noreply.github.com&gt;; 
抄送: "windy"<19060@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Tai7sy/card-system] 建议加入一个向卖家发送邮件的功能 (#250)





 
虽然做了自适应，但是网址太长不方便输。邮箱的话一般就是直接软件，查看也方便

**Comment by cnluminous** [comment]
有的浏览器不支持....

**Comment by cnluminous** [comment]
只是为了更快确认订单信息...

**Comment by Tai7sy** [comment]
个人觉得网页比app快, 
此需求可能后期会考虑加入
