### ISSUE TITLE
码支付问题

### ISSUE THREAD

**Issue by benxiong2** [Tai7sy/card-system#252]
请问码支付-微信支付方式网站不显示是怎么回事？(后台已启用)
![15930738706705728437715357736022](https://user-images.githubusercontent.com/60654542/85685119-5230c680-b701-11ea-993e-48cdfebd94cb.jpg)

**Comment by Tai7sy** [comment]
自己配置前台支付方式

**Comment by benxiong2** [comment]
> 前台支付方式和后台的都需要配置

前天支付我已经打开了，后天渠道id和key都已经填写了！

**Comment by benxiong2** [comment]
> 子渠道后面也有个选项选择是否开启

开启了
![15930745737848757480340958926014](https://user-images.githubusercontent.com/60654542/85686889-f23b1f80-b702-11ea-807e-bd2d052b2eee.jpg)

**Comment by benxiong2** [comment]
> 子渠道后面也有个选项选择是否开启

我记得以前只要启动网站就会有微信支付图标

**Comment by Tai7sy** [comment]
现在多了子渠道功能, 用户购买时候一个支付方式后面可以配置多个子方式, 这样子可以对接N个支付接口

**Comment by benxiong2** [comment]
![15930749885228982640600350988868](https://user-images.githubusercontent.com/60654542/85687959-e8fe8280-b703-11ea-897c-46414c66ccfc.jpg)


> 现在多了子渠道功能，用户购买时候一个支付方式后面可以配置多个子方式，这样子可以对接N个支付接口
我码支付和有趣支付都不会显示这个，其他都可以！

**Comment by benxiong2** [comment]
> 现在多了子渠道功能，用户购买时候一个支付方式后面可以配置多个子方式，这样子可以对接N个支付接口

我弄好了！
