### ISSUE TITLE
对比普通版，商业版有什么新功能和改变？售价和购买地址？以及有交流群么？

### ISSUE THREAD

**Issue by Beattheend** [Tai7sy/card-system#253]
对比普通版，商业版有什么新功能和改变？售价和购买地址？以及有交流群么？
再放送

**Comment by Beattheend** [comment]
我的邮箱：xuanwuguo@gmail.com
QQ号：1559921679

**Comment by Tai7sy** [comment]
已经联系

**Comment by Beattheend** [comment]
不是，请问你是选的那个方式联系的呢？我这边QQ丶给gmail和tg都没收到消息呢。
