### ISSUE TITLE
码支付失效了貌似

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#254]
码支付接口失效了貌似，显示支付验证失败，您可以稍后查看支付状态。
建议码支付付款页面本地化处理，这样可以避免QQ拦截码支付的地址。

**Comment by Tai7sy** [comment]
码支付应该是换了个域名, 程序之前已经更新过, 如果支付成功了未通知的话建议码支付里面看下通知状态

**Comment by jihuoxia** [comment]
> 码支付应该是换了个域名, 程序之前已经更新过, 如果支付成功了未通知的话建议码支付里面看下通知状态

码支付显示是成功了，发卡站里查询订单，也能查出来卡密，就是不自动显示卡密，支付完显示支付失败

**Comment by Tai7sy** [comment]
可否有网站配置个0.01的, 协助定位一下BUG

**Comment by Blackyezi** [comment]
没问题可以正常使用。
