### ISSUE TITLE
只是一个建议“不要用宝塔面板安装”

### ISSUE THREAD

**Issue by mianmianmi** [Tai7sy/card-system#256]
我只是想提个建议，能不能多增加一个用lnmp整合包安装的教程。因为宝塔面板本身就要增加服务器的资源消耗，所以一般我都是用lnmp安装的。个人觉得原始的安装档案可以增加一个不用BT面板，直接用lnmp整合包安装的教程。

**Comment by Tai7sy** [comment]
教程中使用到宝塔了有创建数据库和设置Rewrite规则这里, 如果这些会自己配置的话, 其他的部分一致

**Comment by mianmianmi** [comment]
谢谢

风铃 <notifications@github.com> 于2020年7月12日周日 下午7:06写道：
