### ISSUE TITLE
我用的二级域名访问后台是404

### ISSUE THREAD

**Issue by zkzq520** [Tai7sy/card-system#257]
我用的二级域名访问后台是404
后台是/admin

**Comment by Tai7sy** [comment]
自己检查rewrite规则

**Comment by zkzq520** [comment]
哦 ，麻烦了，我用的lamp，是Apache，rewirte怎么配置哦，安装教程里也没有呀，是用默认的吗

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/blob/043ee5b2bedfeece645f985d99f3da8e1ff98e7f/public/.htaccess.example#L1

**Comment by zkzq520** [comment]
好了 谢谢大佬，原来要将public下面的.htaccess.example 重命名为 .htaccess
