### ISSUE TITLE
作者有考虑建个QQ或者tg群组吗,方便我们小白交流

### ISSUE THREAD

**Issue by fjhechuan** [Tai7sy/card-system#259]
作者有考虑建个QQ或者tg群组吗,方便我们小白交流
一些小问题,方便问群组里人.
人多力量大.

**Comment by Tai7sy** [comment]
这个做的话前期做比较好, 现在搞个群没人加会很尴尬

**Comment by fjhechuan** [comment]
> 这个做的话前期做比较好，现在搞个群没人加会很尴尬

不会啊,肯定有很多人加得.这样我们一些问题就能白嫖问了
