### ISSUE TITLE
当面付接入后无法调用

### ISSUE THREAD

**Issue by gimgoo** [Tai7sy/card-system#260]
支付宝公钥，应用私钥，appid已经填写完毕并且确保正确（本人有一个zfaka，所以知道这三者关系，不存在填错）
但是购买商品时提示：

支付失败！

error:0906D064:PEM routines:PEM_read_bio:bad base64 decode (-----BEGIN RSA PRIVATE KEY----- merchant_private_key -----END RSA PRIVATE KEY-----)

请问这是什么情况啊？

**Comment by gimgoo** [comment]
问题已解决

**Comment by hulu888** [comment]
> 问题已解决

真么解决的啊
