### ISSUE TITLE
不能构建数据库

### ISSUE THREAD

**Issue by abc13131412** [Tai7sy/card-system#267]
c:\wwwroot\card>php artisan key:generate

Warning: require(C:\wwwroot\card/vendor/autoload.php): failed to open stream: No such file or directory in C:\wwwroot\card\artisan on line 18

Warning: require(C:\wwwroot\card/vendor/autoload.php): failed to open stream: No such file or directory in C:\wwwroot\card\artisan on line 18

Fatal error: require(): Failed opening required 'C:\wwwroot\card/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\wwwroot\card\artisan on line 18

**Comment by Tai7sy** [comment]
下载release，开发包不会构建就别用
