### ISSUE TITLE
支付宝当面付提示“支付失败！ Undefined index: app_id”

### ISSUE THREAD

**Issue by kenzie-wu** [Tai7sy/card-system#27]
支付宝当面付提示“支付失败！ Undefined index: app_id”
因为2017年年底之前的当面付失效了，直到刚刚重新找人签约一个，但是不管怎么设置都是这个提示，之前没有问题。
是不是当面付改了？

**Comment by kenzie-wu** [comment]
怕是自己弄错了什么，于是全新安装了一次依旧这样的问题。

公钥和私钥有测试过是匹配的。

**Comment by Tai7sy** [comment]
自己检查json格式的配置，第一个键名是app_id

**Comment by kenzie-wu** [comment]
[https://storage1.cuntuku.com/2018/03/03/dB2xd.png](url)
格式是没有问题的，不知道为啥会出这个提示，还是因为我之前填写了别的回调地址在支付宝内？但是之前也是一模一样的配置就可以。很费解

**Comment by kenzie-wu** [comment]
解决问题，需要用https://docs.open.alipay.com/291/105971这个地址内的工具生成公钥才可以！支付宝产品中心内提供的生成公钥的软件生成的不知道为啥不行，还是用这个老版本的好用。。
