### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by abc13131412** [Tai7sy/card-system#270]
[card_cli-2020-07-28.log](https://github.com/Tai7sy/card-system/files/4988105/card_cli-2020-07-28.log)
500错误
系统:Windows Server 2019 Datacenter (build 17763) x64
版本:3.02
数据库全部ok，但日志里说缺少表？

**Comment by Tai7sy** [comment]
请参考安装教程 
> 构建数据库

这一步

**Comment by abc13131412** [comment]
没有任何报错.....

**Comment by Tai7sy** [comment]
走完了那就不会有问题
