### ISSUE TITLE
请问下大佬CoinPayments这个支付方式应该如何填写相关信息呢？

### ISSUE THREAD

**Issue by mengyalei** [Tai7sy/card-system#272]
首先感谢大佬的分享，想请问下如何配置**CoinPayments这个支付方式**
这里的“方式”填写什么呢？还有就是下面的JSON怎么填写？有可以参考的么？再次感谢！
[
![coninpayment](https://user-images.githubusercontent.com/33970561/88881857-1ab6bc00-d263-11ea-8fbe-975d2deb4735.PNG)
](url)

**Comment by Tai7sy** [comment]
这个驱动的方式没有作用, 只需要在json配置中填写

merchant_id和ipn_secret

**Comment by mengyalei** [comment]
感谢大佬，已经配置好了！大佬威武霸气！
