### ISSUE TITLE
请问下大佬paypal这个支付方式提示获取汇率失败是什么原因呢？

### ISSUE THREAD

**Issue by mengyalei** [Tai7sy/card-system#273]
再次麻烦大佬一下，配置了paypal支付方式（国区paypal账号），在购买商品付款页面选择paypal支付之后，跳转提示“支付失败，获取汇率失败”。这个情况怎么解决呢？感谢大佬！

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-gateway/blob/4b8ded87c1785d758bbdec3329acf92e467e04c7/Pay/PayPal/Api.php#L193

代码如下 可能是你的服务器获取不到汇率, 可以自己修改一个

**Comment by mengyalei** [comment]
已经按照大佬的建议修改了，但是跳转到paypal后，PayPal网站提示系统无响应，这个问题有什么好的建议么？感谢大佬的及时回复！
![paypal](https://user-images.githubusercontent.com/33970561/88896297-3b3f4000-d27c-11ea-8755-fa28b5f29b30.png)

**Comment by Tai7sy** [comment]
这个就不知道了 建议换国外ID试一下
