### ISSUE TITLE
后台的配置

### ISSUE THREAD

**Issue by BigBigfeifan** [Tai7sy/card-system#274]
想问下后台的这些设置的源码是在哪里修改的？可以自行修改或者删掉一些功能么？
![Uploading 1.JPG…]()

**Comment by BigBigfeifan** [comment]
![1](https://user-images.githubusercontent.com/51053212/88999010-f40d8980-d325-11ea-94a6-a3708c91b0d7.JPG)

**Comment by BigBigfeifan** [comment]
![1](https://user-images.githubusercontent.com/51053212/89003354-20c79e00-d332-11ea-804a-d2007e9e5085.JPG)

**Comment by Tai7sy** [comment]
可以，但是自己研究没有文档
