### ISSUE TITLE
支付宝手机支付配置好后，支付成功，但显示订单未支付。

### ISSUE THREAD

**Issue by tk1114632** [Tai7sy/card-system#278]
你好，感谢这个项目。遇到一个问题：

配置好支付宝手机支付之后，appid，2个key都设置好，用户端选择支付，并且付款成功后，商家端支付宝收到款，但用户端显示支付不成功。请问是支付宝手机支付回调的问题吗？如果是，回调应该填什么？

**Comment by Tai7sy** [comment]
后台支付方式操作一栏有按钮, 查看异步通知地址, 后台设置一下
