### ISSUE TITLE
3.02更新问题

### ISSUE THREAD

**Issue by dengzhuo111** [Tai7sy/card-system#284]
我在ssh端输入sudo php artisan update 
然后出现Could not open input file: artisan 
有什么解决办法吗 
![QQ截图20200812110902](https://user-images.githubusercontent.com/69563943/89970915-74b87800-dc8c-11ea-8cc0-886ab90edc81.png)
![QQ截图20200812111052](https://user-images.githubusercontent.com/69563943/89970929-7e41e000-dc8c-11ea-9211-755daf424a59.png)
@Tai7sy

**Comment by dengzhuo111** [comment]
![QQ截图20200812114725](https://user-images.githubusercontent.com/69563943/89972924-a8e26780-dc91-11ea-9b1d-fbdb62d88f62.png)
我在根目录  运行sudo php artisan update出现了出于安全原因，exec（）已被禁用

**Comment by dengzhuo111** [comment]
![QQ截图20200812120915](https://user-images.githubusercontent.com/69563943/89974092-b1886d00-dc94-11ea-8a40-af01fab784ae.png)

把禁用删了 还是这个样子

**Comment by Tai7sy** [comment]
请检查命令行使用的php版本师范街禁用了这些函数

**Comment by dengzhuo111** [comment]
重新装了3.11  但是出现这个
![QQ截图20200813090811](https://user-images.githubusercontent.com/69563943/90083227-878e8380-dd44-11ea-8e51-35eaa3f1e2c5.png)

**Comment by Tai7sy** [comment]
3.11从服务器端拉取github更新内容，可能是你服务器连不上github导致的

**Comment by dengzhuo111** [comment]
![QQ截图20200813094820](https://user-images.githubusercontent.com/69563943/90085266-25388180-dd4a-11ea-822d-d125b4791ac3.png)
![QQ截图20200813094828](https://user-images.githubusercontent.com/69563943/90085268-27024500-dd4a-11ea-8ed5-7441211a83a7.png)
我把这个文件已经放在了这里    需要输入什么命令吗

**Comment by Tai7sy** [comment]
不需要，新记录会自动解析

**Comment by dengzhuo111** [comment]
好的谢谢大佬

**Comment by loveqianool** [comment]
```
/var/www/html/card-system $ php artisan update
未找到php安装路径!

/var/www/html/card-system $ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         /usr/local/etc/php/php.ini
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gettext.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imagick.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-redis.ini,
/usr/local/etc/php/conf.d/docker-php-ext-shmop.ini,
/usr/local/etc/php/conf.d/docker-php-ext-soap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sockets.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-swoole.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sysvsem.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xmlrpc.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
/usr/local/etc/php/conf.d/xx-php-ext-memcached.ini,

/var/www/html/card-system $
```
更新提示 未找到php安装路径!
