### ISSUE TITLE
安装的时候报错

### ISSUE THREAD

**Issue by pan9102** [Tai7sy/card-system#289]
Warning: require(/www/wwwroot/card.bzkj.vip/public/../vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/card.bzkj.vip/public/index.php on line 31

Fatal error: require(): Failed opening required '/www/wwwroot/card.bzkj.vip/public/../vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/card.bzkj.vip/public/index.php on line 31

**Comment by Tai7sy** [comment]
请参考教程安装，不要自己瞎搞
