### ISSUE TITLE
有没有易支付的插件

### ISSUE THREAD

**Issue by Delta658** [Tai7sy/card-system#291]
如题。。。。

**Comment by Prk123Studio** [comment]
您可以参照“https://doc.prk123.com/web/#/5?page_id=25”这篇文档哦~

**Comment by Prk123Studio** [comment]
https://doc.prk123.com/web/#/5?page_id=25

**Comment by benxiong2** [comment]
> https://doc.prk123.com/web/#/5?page_id=25
可以自定义易支付吗？
