### ISSUE TITLE
Windows的宝塔怎么安装网站 

### ISSUE THREAD

**Issue by HurryBy** [Tai7sy/card-system#292]
到php执行代码那一步就出问题了 没有执行那3行代码 最后出来是500
执行的话我这边没有反应。自己设置了环境变量（是php74） 没有任何反应
[http://gchat.qpic.cn/gchatpic_new/0/530077417-0-F2ED10D87AB01B1C2E89809DFD96B0D4/0](image)
[http://gchat.qpic.cn/gchatpic_new/0/530077417-0-F2ED10D87AB01B1C2E89809DFD96B0D4/0](url)

**Comment by Tai7sy** [comment]
执行成功的话500很大可能权限配置问题，自己配置目录权限
