### ISSUE TITLE
paypal的邮箱在哪里设置的

### ISSUE THREAD

**Issue by alimalls** [Tai7sy/card-system#297]
请教下大神paypal的邮箱在哪里设置的

**Comment by Tai7sy** [comment]
支付方式里面填写json格式

**Comment by alimalls** [comment]
![image](https://user-images.githubusercontent.com/59955110/92865793-57b0c980-f431-11ea-8785-098cf245e992.png)
这样对吗？

**Comment by Tai7sy** [comment]
```
{"email":"xxxx@xx.com"}
```
