### ISSUE TITLE
我想知道怎么替换当面付时的扫码领红包..

### ISSUE THREAD

**Issue by qq514444957** [Tai7sy/card-system#299]
我想知道怎么替换当面付时的扫码领红包..

**Comment by Tai7sy** [comment]
自己搜issue

**Comment by qq514444957** [comment]
研究了研究  找到了  感谢您制作的发卡网  当初找了很久  可算找到了

**Comment by qq514444957** [comment]
我想问下我现在是3.02版本 该怎么升级到3.11呢 直接覆盖上去吗

**Comment by Tai7sy** [comment]
参考更新教程直接更新即可, 更新完之后需要重新修改这个红包设置

https://github.com/Tai7sy/card-system/wiki/%E6%9B%B4%E6%96%B0%E6%95%99%E7%A8%8B

**Comment by qq514444957** [comment]
好的谢谢回复

**Comment by qq514444957** [comment]
使用更新命令后提示这个
[http://ww1.sinaimg.cn/large/007Yio23ly1ginxcovkfdj30ax01ojr5.jpg](url)
  Too many arguments, expected arguments "command".  
参数过多，预​​期参数为“命令”。

**Comment by Tai7sy** [comment]
请提供大一点的图 看不到详细命令

**Comment by qq514444957** [comment]
看一下老哥  顺便想问下商业版怎么卖
http://ww1.sinaimg.cn/large/007Yio23ly1ginxfqe0e5j30l00dsaaq.jpg

**Comment by Tai7sy** [comment]
括号里面为可选不要输入
