### ISSUE TITLE
nginx 伪静态规则。

### ISSUE THREAD

**Issue by JarvanDing** [Tai7sy/card-system#3]
<del># nginx configuration

<del>location / {
  if (!-e $request_filename){
    rewrite ^(.*)$ /%1 redirect;
  }
  if (!-e $request_filename){
    rewrite ^(.*)$ /index.php break;
  }
}
亲测可用，<del>但是admin 目录进不去，在找方法<del>
原来 前面必须加#/admin
可是一直提示系统繁忙，也无法登陆。

**Comment by JarvanDing** [comment]
写错了。用这个
location / {
    try_files $uri $uri/ /index.php?$query_string;
}

**Comment by Tai7sy** [comment]
已经加到安装说明里面了, 感谢反馈
