### ISSUE TITLE
logo设置 数据库添加了app_logo  value值添加了图片链接 怎么没反应  

### ISSUE THREAD

**Issue by qq514444957** [Tai7sy/card-system#302]
是我设置错了吗
![image](https://user-images.githubusercontent.com/56515945/93095105-47b91400-f6d5-11ea-8f4a-a87a353cda0f.png)

**Comment by Tai7sy** [comment]
缓存问题

**Comment by qq514444957** [comment]
还是不行

**Comment by 928882650** [comment]
> 还是不行

解决了吗？

**Comment by Tai7sy** [comment]
name填写 `logo`
value填写图片网址，如 `http://example.com/1.jpg`
