### ISSUE TITLE
有劳风铃佬大，PayPal还是无法成功设置。

### ISSUE THREAD

**Issue by alimalls** [Tai7sy/card-system#303]
打扰了风铃佬大，按照你发给我的设置方法，paypal支付时还是会提示设置business邮箱。
是不是我还差哪一步没有设置好。

![2020-09-17_111124](https://user-images.githubusercontent.com/59955110/93415872-13ad4100-f8d7-11ea-91d3-d065a8251e30.png)
![2](https://user-images.githubusercontent.com/59955110/93415878-17d95e80-f8d7-11ea-9bf2-8af302f4ac94.png)

![image](https://user-images.githubusercontent.com/59955110/93415957-46573980-f8d7-11ea-890e-35d41ddaebff.png)
![image](https://user-images.githubusercontent.com/59955110/93415967-4bb48400-f8d7-11ea-9d93-8372ad20e044.png)

**Comment by Tai7sy** [comment]
字段名是business 不是email

**Comment by alimalls** [comment]
感谢！！！

**Comment by 1274936135** [comment]
business  是啥  在哪里看？
