### ISSUE TITLE
升级到3.12之后PayPal支付收不到回调验证？

### ISSUE THREAD

**Issue by zhujitop** [Tai7sy/card-system#304]
升级到3.12之后，PayPal支付成功了，但是查询订单还是显示未支付。

但是PayPal后台那边也已经有订单显示是成功付款，我PayPal后台这边也是有收款记录的。

只是发卡网站这边看订单记录哪里，也是有个未支付的记录。
实际上是已经支付成功了的。

不知道是PayPal变政策导致的还是3.12版本导致的？

以前都正常的。

PayPal收款账号是企业账号。

不知道能不能改成用API帐号签名这种模式？

**Comment by Tai7sy** [comment]
PayPal支付驱动没有改动，可能只是单纯通知的时候失败了，PayPal不会重复通知

**Comment by zhujitop** [comment]
不知道是不是PayPal变规则了还是什么？

新建的发卡网站，PayPal用户付款成功了，但网站这边还是显示未付款订单，PayPal那边是已经到账了的。

**Comment by zhujitop** [comment]
@Tai7sy 

邮箱收到PayPal提示：

请检查用于处理PayPal即时付款通知(IPN)消息的服务器。即时付款通知消息未能成功发送至以下URL：
发卡网址/pay/notify/16

然后我打开看了这个地址，显示IPN OK。

现在用户使用PayPal付款之后，系统收不到回调通知，是因为这个原因造成的吗？

网站用了cf的cdn，防火墙设置引起的？

但是以前也正常来着，很奇怪。

**Comment by Tai7sy** [comment]
就是PayPal服务器访问你服务器被拦截了导致，建议单独设置一个域名填写为api域名用来通知

**Comment by zhujitop** [comment]
api的域名可以和发卡网站的网址不一样？

比如发卡网址是：www.faka.com
api的地址可以是：api.faka.com

只需要把api.faka.com，解析到发卡网的同台服务器上就行吗？还是随便解析到那里都可以，只要ping得通？

**Comment by Tai7sy** [comment]
同一台  直接解析，不要上cdn

**Comment by 1274936135** [comment]
老哥贝宝不通知解决了吗？
