### ISSUE TITLE
请问在哪里放代码引入js呢  找不到放代码的地方

### ISSUE THREAD

**Issue by qq514444957** [Tai7sy/card-system#305]

**Comment by Prk123Studio** [comment]
您好，你可以通过【后台>管理中心>网站设置>网站】，拉到最下面，有个"客服代码(QQ等)"和"统计代码"，可以直接粘贴到这里哦~ 也可以通过【域名/admin/system/set】快速进入后台进行设置！

**Comment by qq514444957** [comment]
还能这样啊？
