### ISSUE TITLE
安装出现server Error

### ISSUE THREAD

**Issue by aihoom** [Tai7sy/card-system#31]
安装出现server Error。。。

请问这是什么情况呀 

PHP 环境7.1 宝塔面板 运行目录/public 已经加了nginx伪静态 权限777也给了

**Comment by Tai7sy** [comment]
storage/logs里有出错日志

**Comment by tingsaid** [comment]
这是登录后台地址才会出现server Error
日志错误是
![image](https://user-images.githubusercontent.com/13901263/44625162-0b22f000-a935-11e8-865c-b0d7acce82d0.png)
