### ISSUE TITLE
关于短信发送卡密通知用户

### ISSUE THREAD

**Issue by xiaoyang-yang** [Tai7sy/card-system#312]
为什么发送的是提取卡密的网址，而不是直接发送卡密，导致很多用户直接把提取网址当成卡密，出现卡密错误的误会。

**Comment by Tai7sy** [comment]
卡密会超出短信长度限制

**Comment by xiaoyang-yang** [comment]
我的卡密很短，请问可以自己修改直接发送卡密吗？如果可以的话，应该怎样修改呢？
谢谢
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 风铃 <notifications@github.com&gt;
发送时间: 2020年10月19日 16:40
收件人: Tai7sy/card-system <card-system@noreply.github.com&gt;
抄送: xiaoyang-yang <1044472124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tai7sy/card-system] 关于短信发送卡密通知用户 (#312)





 
卡密会超出短信长度限制

**Comment by Tai7sy** [comment]
app/Jobs/OrderSms.php
自行修改
