### ISSUE TITLE
更新到3.12过后，后台检查更新，始终显示检查更新失败

### ISSUE THREAD

**Issue by iddddg** [Tai7sy/card-system#314]
不知道算不算Bug，还是我环境问题

**Comment by niezhilong** [comment]
我和你一样

**Comment by benxiong2** [comment]
美国服务器也一样，之前风铃说可能被墙的原因

**Comment by Tai7sy** [comment]
主要通过这个接口检查更新
```
https://raw.githubusercontent.com/Tai7sy/card-system/master/.version
```

可以服务器里面curl访问一下确认原因

**Comment by benxiong2** [comment]
> 主要通过这个接口检查更新
> 
> ```
> https://raw.githubusercontent.com/Tai7sy/card-system/master/.version
> ```
> 
> 可以服务器里面curl访问一下确认原因

显示    没有那个文件或目录

**Comment by benxiong2** [comment]
{"version":"3.12","md5":"3a3ef7e38f07944989dc89f4125ab688","url":"http:\/\/p.qpic.cn\/qqshihua\/0\/dab4215b285c461b13e9498691685625\/0\/card_release.tar.gz"}

**Comment by iddddg** [comment]
香港服务器，curl返回
~~~~json
{"version":"3.12","md5":"3a3ef7e38f07944989dc89f4125ab688","url":"http:\/\/p.qpic.cn\/qqshihua\/0\/dab4215b285c461b13e9498691685625\/0\/card_release.tar.gz"}
~~~~
PS：Gay的raw地址国内可能访问不到，我这香港不应该，而且也能curl到，但是检查更新还是失败

**Comment by Tai7sy** [comment]
```
<?php

function curl($url, $post = null, $headers = null)
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_FAILONERROR, false);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    if (!empty($post)) {
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
        if ($headers === null) {
            $headers = array("Content-Type: application/x-www-form-urlencoded");
        }
    }
    if ($headers !== null) {
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    }
    $response = curl_exec($ch);
    if (curl_errno($ch)) {
        throw new Exception(curl_error($ch), 0);
    } else {
        $httpStatusCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        if (200 !== $httpStatusCode) {
            throw new Exception($response, $httpStatusCode);
        }
    }
    curl_close($ch);
    return $response;
}

var_dump(curl('https://raw.githubusercontent.com/Tai7sy/card-system/master/.version'));
```


可以保存为1.php
然后执行
```
php 1.php
```

看一下输出

**Comment by benxiong2** [comment]
> ```
> <?php
> 
> function curl($url, $post = null, $headers = null)
> {
>     $ch = curl_init();
>     curl_setopt($ch, CURLOPT_URL, $url);
>     curl_setopt($ch, CURLOPT_FAILONERROR, false);
>     curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
>     curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
>     if (!empty($post)) {
>         curl_setopt($ch, CURLOPT_POST, true);
>         curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
>         if ($headers === null) {
>             $headers = array("Content-Type: application/x-www-form-urlencoded");
>         }
>     }
>     if ($headers !== null) {
>         curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
>     }
>     $response = curl_exec($ch);
>     if (curl_errno($ch)) {
>         throw new Exception(curl_error($ch), 0);
>     } else {
>         $httpStatusCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
>         if (200 !== $httpStatusCode) {
>             throw new Exception($response, $httpStatusCode);
>         }
>     }
>     curl_close($ch);
>     return $response;
> }
> 
> var_dump(curl('https://raw.githubusercontent.com/Tai7sy/card-system/master/.version'));
> ```
> 
> 可以保存为1.php
> 然后执行
> 
> ```
> php 1.php
> ```
> 
> 看一下输出

终端直接访问？

**Comment by Tai7sy** [comment]
直接访问或者终端执行都可以
注意终端执行需要确保php和你网站使用的php版本一致

**Comment by benxiong2** [comment]
> 直接访问或者终端执行都可以
> 注意终端执行需要确保php和你网站使用的php版本一致

我php7.2直接访问一堆附近语法有问题

**Comment by iddddg** [comment]
宝塔终端下
~~~~
string(157) "{"version":"3.12","md5":"3a3ef7e38f07944989dc89f4125ab688","url":"http:\/\/p.qpic.cn\/qqshihua\/0\/dab4215b285c461b13e9498691685625\/0\/card_release.tar.gz"}"
~~~~
似乎正常

**Comment by benxiong2** [comment]
> 宝塔终端下
> 
> ```
> string(157) "{"version":"3.12","md5":"3a3ef7e38f07944989dc89f4125ab688","url":"http:\/\/p.qpic.cn\/qqshihua\/0\/dab4215b285c461b13e9498691685625\/0\/card_release.tar.gz"}"
> ```
> 
> 似乎正常

你会添加pajs支付吗？

**Comment by Tai7sy** [comment]
> 宝塔终端下
> 
> ```
> string(157) "{"version":"3.12","md5":"3a3ef7e38f07944989dc89f4125ab688","url":"http:\/\/p.qpic.cn\/qqshihua\/0\/dab4215b285c461b13e9498691685625\/0\/card_release.tar.gz"}"
> ```
> 
> 似乎正常

那你这有点邪门。。。里面的代码就是检查更新用的代码。。。
在日志里面有检查更新失败的日志可以看下输出

**Comment by benxiong2** [comment]
仪表板.版本检查更新失败 {version_raw"："\"版本\"：\"3.12\"，\"md5\"：\"3a3ef7e38f0794989dc89f4125ab688\"，\"url \"：\"http：//\/\/p.qpic.cn\/qqshihua\/0\/dab4215b285c461b13e9498691685625\/0\/card_release.tar.gz\"\"\ "

**Comment by iddddg** [comment]
~~~~
[2021-01-25 16:08:25] local.ERROR: Dashboard.version checkUpdate failed {"version_raw":"{\"version\":\"3.12\",\"md5\":\"3a3ef7e38f07944989dc89f4125ab688\",\"url\":\"http:\\/\\/p.qpic.cn\\/qqshihua\\/0\\/dab4215b285c461b13e9498691685625\\/0\\/card_release.tar.gz\"}"} 
~~~~
哈哈玄学

**Comment by benxiong2** [comment]
日志报错

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/commit/96cecab6d3e21dc3c6f7fb47b3d4c68e40cb5453

已修复，文件格式出了一点问题

**Comment by iddddg** [comment]
我这报错验证了，接口返回未知错误，请检查日志
~~~~
[2021-01-25 16:30:01] local.ERROR: Undefined index: description {"userId":1,"email":"xxx","exception":"[object] (ErrorException(code: 0): Undefined index: description at /www/wwwroot/xxxx/app/Http/Controllers/Admin/Dashboard.php:2)
~~~~
和
~~~~
[2021-01-25 16:30:01] local.ERROR: Uncaught Exception {"exception":"[object] (ErrorException(code: 0): Undefined index: description at /www/wwwroot/xxxx/app/Http/Controllers/Admin/Dashboard.php:2)
~~~~
看起来似乎是数组取索引/键名 出错了？

**Comment by Tai7sy** [comment]
现在可以试一下，应该正常了。。

**Comment by benxiong2** [comment]
显示了

**Comment by iddddg** [comment]
OK了，感谢风铃大佬
