### ISSUE TITLE
风铃大佬,反馈一个手机端背景图片显示bug,下个版本可以修复吗 感谢

### ISSUE THREAD

**Issue by etong33** [Tai7sy/card-system#315]
现在有一个问题手机访问的时候。背景图片不会自适应屏幕大小,还依然是pc端的大小,我希望变成自适应,
<img width="1442" alt="Xnip2020-10-31_21-33-29" src="https://user-images.githubusercontent.com/39824967/97780726-542ff800-1bc1-11eb-8684-091166251734.png">

**Comment by Tai7sy** [comment]
长宽都不一样，没法自适应
