### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by sxdd-gtafz** [Tai7sy/card-system#318]
############################################################################################
安装步骤：
############################################################################################
1.网页文件已经放在文件夹里了，在规定路径！
############################################################################################
2.配置文件也已经修改！
############################################################################################
3.数据库已经建立！
############################################################################################
4.防跨站攻击(open_basedir)已经关闭！
############################################################################################
5.设置运行目录为/public成功！
############################################################################################
6. Nginx伪静态已设置location / {    try_files $uri $uri/ /index.php?$query_string;}
############################################################################################
结果：无法打开网站！
显示结果如下：####################################################################################
#Warning: require(/www/wwwroot/sxdd-gtafz.xyz/public/../vendor/autoload.php): failed to open stream: No such file or #directory in /www/wwwroot/sxdd-gtafz.xyz/public/index.php on line 31
############################################################################################
#Fatal error: require(): Failed opening required '/www/wwwroot/sxdd-gtafz.xyz/public/../vendor/autoload.php' 
#(include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/sxdd-gtafz.xyz/public/index.php on line 31
################################################################################################
服务器配置：
############################################################################################
Linun系统-7.4.5宝塔免费版
############################################################################################
已安装：
Nginx 1.17.10---MySQL 5.7.31----PHP-7.4--PHP-7.3-----PHP-7.2----Pure-Ftpd 1.0.49----phpMyAdmin 4.9
############################################################################################
问题：
1.请问那里出现问题了！
2.还是我设置错误了！
3.可以教我一下吗！
############################################################################################
4.如果可以的话加我QQ教我一下！谢谢！！！！！！！
5.QQ：2692097794
6.QQ：2692097794
7.QQ：2692097794
############################################################################################
8.谢谢！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
############################################################################################

**Comment by Tai7sy** [comment]
请下载release里面的源码包，进行安装

**Comment by Murmire** [comment]
![image](https://user-images.githubusercontent.com/69282145/99062180-88ea7900-25dd-11eb-8c70-3351ae3ce512.png)
请问这个怎么解决？源码文件放到wwwroot里了
数据库也导入了 env文件也修改了
![image](https://user-images.githubusercontent.com/69282145/99062273-b6cfbd80-25dd-11eb-81bd-611be08ab2b7.png)
