### ISSUE TITLE
小白求助！！

### ISSUE THREAD

**Issue by Murmire** [Tai7sy/card-system#319]
没找到站点怎么解决 ，第一次搞这个
![image](https://user-images.githubusercontent.com/69282145/99062620-3b224080-25de-11eb-9eec-b7e3dff762b9.png)
域名也解析了  文件上传后台了，数据库也导入了 env文件也修改了 
然后访问网站就是没找到站点。
![image](https://user-images.githubusercontent.com/69282145/99063065-e7642700-25de-11eb-88e4-d3f2fb437927.png)
求指导 谢谢

**Comment by Tai7sy** [comment]
需要设置网站根目录到public目录

**Comment by Murmire** [comment]
> 需要设置网站根目录到public目录

好的 可以用虚拟主机搭建吗

**Comment by Tai7sy** [comment]
自己看虚拟机主机配置，没搭建过
