### ISSUE TITLE
支付接口拉取不出来

### ISSUE THREAD

**Issue by 1639617972** [Tai7sy/card-system#32]
支付宝接口一直提示：错误代码 ILLEGAL_PARTNER，请问需要修改哪些配置文件呢 @Tai7sy

**Comment by Tai7sy** [comment]
哪个支付接口都没说

**Comment by 1639617972** [comment]
支付宝的接口

**Comment by 1639617972** [comment]
选择的是第一个支付宝接口，我改动了合作者id和md5密钥，但是还是提示：错误代码 ILLEGAL_PARTNER @Tai7sy

**Comment by Tai7sy** [comment]
说明改错了 自己找原因或者找支付宝
