### ISSUE TITLE
安装。。。。。。。。。。。。

### ISSUE THREAD

**Issue by sxdd-gtafz** [Tai7sy/card-system#320]
按照提示规定安装了！
但是不能用！
[admin@izj6chcucevs52mb93uz5oz ~]$ sudo su root
[root@izj6chcucevs52mb93uz5oz admin]# cd /www/wwwroot/sxdd-gtafz.xyz
[root@izj6chcucevs52mb93uz5oz sxdd-gtafz.xyz]# php artisan reset:password 2692097794@qq.com sxddzxh5211314

In Application.php line 2:
                                                   
  putenv() has been disabled for security reasons  
                                                   

[root@izj6chcucevs52mb93uz5oz sxdd-gtafz.xyz]# cd /www/wwwroot/sxdd-gtafz.xyz
[root@izj6chcucevs52mb93uz5oz sxdd-gtafz.xyz]# php artisan key:generate

In Application.php line 2:
                                                   
  putenv() has been disabled for security reasons  
                                                   

[root@izj6chcucevs52mb93uz5oz sxdd-gtafz.xyz]# php artisan migrate:fresh --seed 
In Application.php line 2:
                                                   
  putenv() has been disabled for security reasons  
                                                   

[root@izj6chcucevs52mb93uz5oz sxdd-gtafz.xyz]# php artisan cache:clear

显示这个
我创建了一样的数据库！
访问网页结果：
未知错误，请检查日志

安装步骤：
【1】
cd /www/wwwroot/sxdd-gtafz.xyz
curl -L -o card_release.tar.gz https://github.com/Tai7sy/card-system/releases/download/3.0/card_release.tar.gz && tar -zxf card_release.tar.gz && \cp -rf card_system_free_dist/. . && rm -rf card_system_free_dist card_release.tar.gz
chmod -R 777 storage/
chmod -R 777 bootstrap/cache/
【2】
cd /www/wwwroot/sxdd-gtafz.xyz
php -r "copy('.env.example', '.env');"
【3】
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sxdd_gtafz_xyz
DB_USERNAME=sxdd_gtafz_xyz
DB_PASSWORD=7XBfMkWMftwwEzkN
【4】
cd /www/wwwroot/sxdd-gtafz.xyz
php artisan key:generate
php artisan migrate:fresh --seed
php artisan cache:clear
【5】
cd /www/wwwroot/sxdd-gtafz.xyz
php artisan reset:password 2692097794@qq.com sxddzxh5211314
【结果】
未知错误，请检查日志

求解答！！！！！！！！！！！！！！！！！！！！！！！！！
加我qq告诉我或者回复都可以！！！！！！！
谢谢！！！！！！！！！
2692097794

**Comment by Tai7sy** [comment]
```
putenv() has been disabled for security reasons
```
自己启用宝塔禁用的**所有**php函数
