### ISSUE TITLE
卡密提取问题

### ISSUE THREAD

**Issue by yuequan1** [Tai7sy/card-system#321]

**Comment by yuequan1** [comment]
有人在我的网站上跑字典偷卡密咋整

**Comment by yuequan1** [comment]
能否增加查卡密码这个选项，我设置了那个验证码还是没什么用

**Comment by yuequan1** [comment]
网站防CC，ip限制访问也没用

**Comment by Tai7sy** [comment]
设置验证码就可以了, 增加查卡密码不一样跑字典吗

**Comment by yuequan1** [comment]
> 设置验证码就可以了, 增加查卡密码不一样跑字典吗

验证码没用，他们好像是在那个网站的卡密复制的地方那个网站跑字典，验证码压根没用

**Comment by Tai7sy** [comment]
那个是订单号页面吧, 通过订单号查卡密不需要验证码, 这个无需担心, 订单号那么长跑不出来的

**Comment by lchjczw** [comment]
添加查询限制，每天限制20次，字典就没用了

**Comment by Tai7sy** [comment]
你这个防CC策略建议在自己的http服务器侧写规则进行限制

**Comment by yuequan1** [comment]
> 那个是订单号页面吧, 通过订单号查卡密不需要验证码, 这个无需担心, 订单号那么长跑不出来的
他已经跑出来很多了  还在我面前装呢

**Comment by yuequan1** [comment]
> 添加查询限制，每天限制20次，字典就没用了

怎么添加

**Comment by Tai7sy** [comment]
自己谷歌哦
