### ISSUE TITLE
无法修改"订单查询最长天数"

### ISSUE THREAD

**Issue by BOTBAKS** [Tai7sy/card-system#322]
![image](https://user-images.githubusercontent.com/52072126/99868474-c06cad00-2bfd-11eb-9232-cd8e919f6879.png)

修改1天后保存，刷新网页又变回30天了

**Comment by Tai7sy** [comment]
参考readme 删除缓存后重新设置

**Comment by BOTBAKS** [comment]
大大
删除缓存后 依然不行
还有就是  怎么清理登录地址的记录？

**Comment by Tai7sy** [comment]
数据库里面清除

**Comment by BOTBAKS** [comment]
![image](https://user-images.githubusercontent.com/52072126/99882483-c1342c00-2c5b-11eb-9f9a-0268b46ef524.png)
按照这里清理缓存后，修改查询天数  刷新网页  还是变回30天了

**Comment by Murmire** [comment]
我也一样 我看这是个bug
