### ISSUE TITLE
支付宝手机网站驱动AliAop  支付失败！ 支付验证失败，您可以稍后查看支付状态。

### ISSUE THREAD

**Issue by Moe-XW** [Tai7sy/card-system#327]
支付宝手机网站驱动AliAop 可以支付付款，但是验证失败无法发卡
[https://s3.ax1x.com/2020/12/19/rNNZW9.png](url)

**Comment by Moe-XW** [comment]
版本: 2.95e 希望风铃大佬弄个修补文件

**Comment by Moe-XW** [comment]
<a href="https://imgchr.com/i/rNNZW9"><img src="https://s3.ax1x.com/2020/12/19/rNNZW9.png" alt="rNNZW9.png" border="0" /></a>

**Comment by Tai7sy** [comment]
应该是签名校验失败，可能机器网络连不上支付宝那边导致的问题

**Comment by Moe-XW** [comment]
> 应该是签名验证失败，可能机器网络连不上支付宝那边导致的问题
换了几个机器 安装最新版本测试了一下 支付渠道的支付宝官方对接的手机网站功能 支付后都提示验证失败
www.9m3u8.com

**Comment by Tai7sy** [comment]
试了没有问题，应该是你https之类的配置错误导致的问题，比如api支付域名没带https同时开启https跳转之类的问题，非程序原因
