### ISSUE TITLE
上传图片后无法显示(裂开)

### ISSUE THREAD

**Issue by 1028781861** [Tai7sy/card-system#329]
通过后台商品描述处上传图片后，预览的图片是裂开的，并且在网站上显示也是裂开的，右键新建打开显示404错误
nginx
a padding to disable MSIE and Chrome friendly error page
查看图片路径是
 "http://域名/storage/images/product/KvUH8L8aphg2HWA0h0ibFPlL8bWY6EHBzGcY04EF.png"
但是我在面板看图片的路径实际上上传到了
"http://域名/storage/app/images/product/KvUH8L8aphg2HWA0h0ibFPlL8bWY6EHBzGcY04EF.png"
我需要在哪里更改读取图片的路径？

**Comment by Tai7sy** [comment]
宝塔nginx配置存在问题，伪静态无效，需要自己修改，
例子: 16-20行
https://github.com/Tai7sy/card-system/blob/74d4cd494426a94c11c8fa38b4a90377953021b1/public/nginx.conf.example#L16

或者换Apache

**Comment by 1028781861** [comment]
谢谢
