### ISSUE TITLE
自己集成第三方支付

### ISSUE THREAD

**Issue by aqingyang** [Tai7sy/card-system#33]
自己集成的第三方支付，问题出在：数据库将订单插入数据库了，但是支付的时候提示未找到支付方式，数据库中已经存在该支付方式，并且插入数据库的订单中，支付方式id是正确的 @Tai7sy ，求大佬解惑

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/wiki/%E6%94%AF%E4%BB%98%E6%8E%A5%E5%8F%A3%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3
