### ISSUE TITLE
如何修改首页固定的显示文字

### ISSUE THREAD

**Issue by BOTBAKS** [Tai7sy/card-system#332]
风铃大大，如何修改首页固定的显示文字？
比如 "店铺公告" 这几个字
还有 "请输入手机号，用于查询订单" 这些地方

**Comment by Tai7sy** [comment]
/public/dist 
目录中，建议使用notepad++等工具目录内搜索文本替换

**Comment by BOTBAKS** [comment]
好的，谢谢
