### ISSUE TITLE
安装好后后台检测更新是失败是什么原因？

### ISSUE THREAD

**Issue by niezhilong** [Tai7sy/card-system#334]
请问商业版怎么购买，有没有联系方式
还有就是安装好后后台检测更新是失败是什么原因？
我的qq：77167840
请加我
![QQ截图20201231001416](https://user-images.githubusercontent.com/61985182/103366278-157fc680-4aba-11eb-8fa2-9836010bc6a8.png)

**Comment by Tai7sy** [comment]
检测更新需要链接到github，可能是被墙了的原因

**Comment by niezhilong** [comment]
在后台商品介绍上传图片，图片就直接变成这样了是什么原因？
![屏幕截图 2021-01-01 003903](https://user-images.githubusercontent.com/61985182/103418496-d4a1b380-4b86-11eb-99ea-d7fd247e6333.png)

**Comment by Tai7sy** [comment]
自己搜issue 宝塔Nginx配置问题
