### ISSUE TITLE
请问如何增加stripe接口？

### ISSUE THREAD

**Issue by iamleo973** [Tai7sy/card-system#335]
请教风铃大大，想对接stripe，驱动和方式应该填什么？
配置JSON填的是card-gateway/Pay/Stripe/Api.php吗？
谢谢！
-------------------------
**我已经根据支付接口接入文档写好了api，在支付渠道配置里的pid我不知道应该填什么(应该是微信支付有的接口)，stripe后台并没有这个pid，能不能请风铃大大指教一下？感激不尽！**

**Comment by iamleo973** [comment]
感谢解答！我去试试看

**Comment by iamleo973** [comment]
> 这个pid不需要啊，json格式是自己约定的一个数据格式，在api.php内通过config变量获取

风铃大大你好，我已经改了一下json的格式，但是在付款的时候弹出了：请填写API秘钥 [api_key]，我填了很多遍了(sk_live格式)，可以帮我看看是怎么回事吗？谢谢！

![123](https://user-images.githubusercontent.com/76947339/104727346-2c9df580-5703-11eb-8856-b215d798c90a.png)
![456](https://user-images.githubusercontent.com/76947339/104727347-2c9df580-5703-11eb-8eb2-3d0a67d76878.png)
![789](https://user-images.githubusercontent.com/76947339/104727348-2d368c00-5703-11eb-946f-2007b3032a8f.png)

**Comment by Tai7sy** [comment]
不要瞎改php代码，php代码不要修改

**Comment by iamleo973** [comment]
好的，我再试一试，谢谢！
