### ISSUE TITLE
coinpayments怎么对接

### ISSUE THREAD

**Issue by zhujitop** [Tai7sy/card-system#337]
请问coinpayments怎么对接？

在json里面，怎么填写ID和ipn呢？

方式直接写coinpayments就行了吧？

还有库存预警通知，是发给那个邮箱呢？后台配置的邮箱号吗？还是管理员登录邮箱？默认admin@qq.com这个自己改下？

**Comment by Tai7sy** [comment]
1 json格式，不动可以参考其他支付方式格式照着写
2 自己数据库users表修改管理员
