### ISSUE TITLE
支付宝手机网站支付回调还是有问题

### ISSUE THREAD

**Issue by Moe-XW** [Tai7sy/card-system#338]
支付失败！
支付验证失败，您可以稍后查看支付状态。 支付api设置都是http，付款后还是验证失败没有发卡
<a href="https://imgchr.com/i/sN5u4I"><img src="https://s3.ax1x.com/2021/01/13/sN5u4I.jpg" alt="sN5u4I.jpg" border="0" /></a>
http://www.9m3u8.com/

**Comment by Tai7sy** [comment]
当面付吗，我这边测试没问题
