### ISSUE TITLE
用数据库关闭了验证码刷新缓存后过一会就自动500报错 再次刷新缓存才会显示

### ISSUE THREAD

**Issue by heyyoulist** [Tai7sy/card-system#341]
问题排查了几个小时了，一直找不到解决办法，大佬帮忙看一下 

ps:只动了关闭验证码那行数据库

[错误日志.log](https://github.com/Tai7sy/card-system/files/5835768/default.log)

**Comment by heyyoulist** [comment]
![image](https://user-images.githubusercontent.com/66654989/105033586-42107800-5a93-11eb-8d25-2e7d951df8a5.png)
![Uploading image.png…]()

**Comment by Tai7sy** [comment]
请清空网站缓存, 操作如下
````
cd /www/wwwroot/example.com&nbsp; #进入网站目录
rm -rf storage/framework/cache/data/*
php artisan cache:clear
php artisan config:clear
php artisan route:clear
````





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "heyyoulist"<notifications@github.com&gt;; 
发送时间: 2021年1月19日(星期二) 晚上8:14
收件人: "Tai7sy/card-system"<card-system@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [Tai7sy/card-system] 用数据库关闭了验证码刷新缓存后过一会就自动500报错 再次刷新缓存才会显示 (#341)





 
问题排查了几个小时了，一直找不到解决办法，大佬帮忙看一下
 
ps:只动了关闭验证码那行数据库
 
错误日志.log

**Comment by heyyoulist** [comment]
我清空了，过一会他又会报500

**Comment by heyyoulist** [comment]
就很奇怪

**Comment by heyyoulist** [comment]
现在又500了。。。

**Comment by Tai7sy** [comment]
是不是配置了定时任务之类的, 然后没有用www权限, 导致生成的缓存目录权限不对



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "heyyoulist"<notifications@github.com&gt;; 
发送时间: 2021年1月19日(星期二) 晚上8:24
收件人: "Tai7sy/card-system"<card-system@noreply.github.com&gt;; 
抄送: "windy"<19060@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Tai7sy/card-system] 用数据库关闭了验证码刷新缓存后过一会就自动500报错 再次刷新缓存才会显示 (#341)





 
就很奇怪

**Comment by heyyoulist** [comment]
![image](https://user-images.githubusercontent.com/66654989/105035271-adf3e000-5a95-11eb-8bbb-1264088f8ec4.png)

**Comment by heyyoulist** [comment]
没有啊，今天就动了个数据库，别的都没动

**Comment by heyyoulist** [comment]
可以加一下我的Q处理下嘛。可以有偿，顺便我想咨询一下商业版 QQ2094629698

**Comment by heyyoulist** [comment]
解决了，我把目录所有权限从root改成www了
