### ISSUE TITLE
检测更新失败

### ISSUE THREAD

**Issue by niezhilong** [Tai7sy/card-system#348]
服务器是国内的 北京的  执行更新命令提示检测更新失败，更新不了的话如果卡网有大更新或者有什么bug更新不了 咋办 有别的办法更新吗？风铃大佬
![屏幕截图 2021-02-02 190208](https://user-images.githubusercontent.com/61985182/106591637-7acb4980-6589-11eb-83ae-215502991fbd.png)

**Comment by Tai7sy** [comment]
代理支持 --proxy 选项
可以先在小鸡上开个v2代理客户端
