### ISSUE TITLE
请教大大！后台是否可增加时区设置（不同于服务器时区）！

### ISSUE THREAD

**Issue by haileshe1234** [Tai7sy/card-system#349]
由于支付平台按美东时区结算。现有服务器时区需要设为北京时间，但发卡系统需独立按美东时区，是否可在后台增加设置或者手动如何修改！麻烦大大！

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/blob/39bf54970a2c6f5983cd7c4b83f0854b8f3b359b/config/app.php#L73

自行修改
PRC = 中国
其他的代码自己找

**Comment by haileshe1234** [comment]
大大！根据：https://www.php.net/manual/en/timezones.php 调整了时区代码，替换输入America/Toronto，并重启服务器，但未生效！是否可在后台增加该选项？

**Comment by Tai7sy** [comment]
修改config目录内配置是唯一修改方式, 不生效请参考readme清空缓存
