### ISSUE TITLE
求助安装出问题

### ISSUE THREAD

**Issue by landlordlycat** [Tai7sy/card-system#354]
php artisan cache:clear
php artisan config:clear
php artisan route:clear

安装构建数据库用的这里命令的时候，就出错

PHP Parse error:  syntax error, unexpected '?' in /www/wwwroot/xxx/vendor/overtrue/wechat/src/Kernel/Support/Helpers.php on line 2

Parse error: syntax error, unexpected '?' in /www/wwwroot/xxx/vendor/overtrue/wechat/src/Kernel/Support/Helpers.php on line 2

看命令是语法错误 有个'?'有问题 我头都搞大了。不知道咋回事。

麻烦帮帮忙看一下。谢谢了

**Comment by Murmire** [comment]
宝塔数据库里面 连接要设置成所有人

**Comment by Tai7sy** [comment]
命令行php版本问题, 不会设置就不要安装其他php版本  只保留7.4
