### ISSUE TITLE
好懵逼哦

### ISSUE THREAD

**Issue by 810848174** [Tai7sy/card-system#356]
对于一个新手来说，不知道啥都是啥，我到现在也就是进行到三分之一，商业版也不知道怎么搞，求大佬教教

**Comment by 810848174** [comment]
我QQ：810848174，求大佬指点一下

**Comment by Tai7sy** [comment]
教程已经很详细了, 实在不行可以谷歌
https://baiyue.one/archives/293.html
https://www.virplus.com/thread-1249.htm
https://www.daniao.org/10179.html
