### ISSUE TITLE
能否加一个每人限购数量

### ISSUE THREAD

**Issue by Rottyler** [Tai7sy/card-system#36]
比如每人限购一张

**Comment by asleep2** [comment]
@Rottyler  可以设置的。但是我现在不知道怎么设置用户名和更改密码，默认用户名不是admin@qq.com吗？在哪能改呢？

**Comment by Rottyler** [comment]
加一个吧，容易绕过总比没有强

**Comment by asleep2** [comment]
@Tai7sy  假如有人来我网站搞事，乱填联系方式，疯狂提交订单。也不支付，我网站会不会瞬间宕机？

**Comment by Tai7sy** [comment]
@asleep2 取决于你服务器性能。

**Comment by asleep2** [comment]
@Tai7sy  我想接入鲨鱼支付，该怎么做？ shayupay  我有id和key

**Comment by Tai7sy** [comment]
@asleep2 
目前不支持 需要单独定制

**Comment by asleep2** [comment]
@Tai7sy  邮件设置还是有点没懂，剩下的该怎么填呢？
![y46](https://user-images.githubusercontent.com/39230916/48540328-c5067880-e8f4-11e8-984c-4699043337b4.png)

**Comment by Tai7sy** [comment]
@asleep2 这里是你的发件邮箱信息
