### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by benxiong2** [Tai7sy/card-system#360]
![CJOF@EXT@}(~U X W5_7TBV](https://user-images.githubusercontent.com/60654542/109105055-22423300-7768-11eb-94fb-9ca1aa8fa5b7.png)
打开系统日志显示这个
![$~~XC B_O~9}507MXO4 %5L](https://user-images.githubusercontent.com/60654542/109105149-49990000-7768-11eb-8843-179cb7c7369a.png)
这个禁用词已经删了但还是提示这个

**Comment by Tai7sy** [comment]
宝塔php禁用的函数全部删除
