### ISSUE TITLE
后台概览支付方式统计中，今日统计的数据不对

### ISSUE THREAD

**Issue by oozzbb** [Tai7sy/card-system#361]
function stat(Request $sp13451b) {
		$this->validate($sp13451b, array('day' => 'required|integer|between:1,30'));
		$spe595a6 = (int) $sp13451b->input('day');
		if ($spe595a6 === 30) {
			$speeaf8a = Carbon::now()->addMonths(-1)->toDateString() . ' 00:00:00';
		} else {
			$speeaf8a = Carbon::now()->addDays(-$spe595a6)->toDateString() . ' 00:00:00';
                     //$speeaf8a = Carbon::now()->addDays(1-$spe595a6)->toDateString() . ' 00:00:00';
		}
                .............................
      }

在前台传入day=1的情况下，统计的是昨天和今天两天的数据

建议：
1、后台首页概览里和支付方式统计里可否增加一个当月的统计
2、订单的付款时间，可否用支付方式实际付款时间，比如微信或支付宝订单里的付款时间
谢谢大佬 赞

**Comment by Tai7sy** [comment]
1. `day = 1` 意味着是 统计近1天的数据 这里使用了 0点作为分隔, 是否使用当前时间?
2. 订单付款时间储存于 `paid_at` 字段中, 接受到支付渠道的回调时会设置此字段, 不同支付方式返回数据各种各样 无法使用支付渠道内的时间(有些渠道可能没有这个字段)
