### ISSUE TITLE
当面付配置问题

### ISSUE THREAD

**Issue by benxiong2** [Tai7sy/card-system#362]
当面付调用显示空白
![QEB5(A7UJTLA1BB$14I}K0](https://user-images.githubusercontent.com/60654542/109133810-56314e80-7790-11eb-8c17-b962534b8a23.png)
![@094)M4_ _$X8 N IT%B7QJ](https://user-images.githubusercontent.com/60654542/109133874-677a5b00-7790-11eb-9c2a-677cfa3e6407.png)
两种都试了

**Comment by Tai7sy** [comment]
空白页面可以看下有没有日志

 storage/logs 目录下
