### ISSUE TITLE
使用升级命令升级后 网站就显示503当前服务不可用，请稍后重试

### ISSUE THREAD

**Issue by 928882650** [Tai7sy/card-system#363]
多次重新跑升级命令也是不行，不知道问题出在哪里

[root@iZ2ze2nevqtdxk2qbmp0jaZ www]# sudo appnode-php73 artisan update

检查更新中...
当前版本: 2.93
最新版本: 3.13
版本说明: 

 是否现在更新 (yes/no) [no]:
 > yes

正在下载新版本...
    download: 100.00%
正在解压...
正在关闭主站...
 --> 正在清理旧文件...
 --> 正在复制新文件...
 --> 正在创建缓存...

In Application.php line 2:
                                                             
  Class 'Intervention\Image\ImageServiceProvider' not found  
                                                             
一次 跑报错。
[root@iZ2ze2nevqtdxk2qbmp0jaZ www]# sudo appnode-php73 artisan update
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33

检查更新中...
当前版本: 3.13
最新版本: 3.13
版本说明: 
您的版本已是最新!

 是否再次更新 (yes/no) [no]:
 > yes

正在下载新版本...
    download: 100.00%
正在解压...
正在关闭主站...
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
 --> 正在清理旧文件...
 --> 正在复制新文件...
 --> 正在创建缓存...
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
 --> 正在更新数据库...
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
 --> 正在设置目录权限...
正在启用主站...
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /data/mystack/sites/pay.aigeek.top/www/artisan on line 33
清理临时目录...
更新成功!

**Comment by Tai7sy** [comment]
php版本问题。。没识别出php路径，建议手动下载release覆盖一下

**Comment by Tai7sy** [comment]
你这个php有点特殊没识别出php路径导致。可以把默认php设为73试试

**Comment by 928882650** [comment]
> 你这个php有点特殊没识别出php路径导致。可以把默认php设为73试试

解决了，appnode面版 在组件管理中 把默认命令行设置为7.3即可。
如果提示noSymLink错误，。执行以下命令即可解决，虽然我不知道原因。。。
rpm -e php-devel-5.4.16-46.1.el7_7.x86_64
rpm -e php-cli-5.4.16-46.1.el7_7.x86_64
 rpm -e php-common-5.4.16-46.1.el7_7.x86_64
