### ISSUE TITLE
2.93升级到3.13后无法登录后台了。。提示 未知错误，请检查日志

### ISSUE THREAD

**Issue by 928882650** [Tai7sy/card-system#364]
@Tai7sy 

[card_fpm-fcgi-2021-02-26.log](https://github.com/Tai7sy/card-system/files/6047039/card_fpm-fcgi-2021-02-26.log)

**Comment by Tai7sy** [comment]
到网站目录执行
```
php artisan migrate
```

手动升级请严格按照升级教程执行

**Comment by 928882650** [comment]
可视我是用的自动升级的命令的，
[root@iZ2ze2nevqtdxk2qbmp0jaZ www]# appnode-php73 artisan migrate

In Connection.php line 2:
                                                                                      
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'password_resets' a  
  lready exists (SQL: create table `password_resets` (`email` varchar(128) not null,  
   `token` varchar(255) not null, `created_at` timestamp null) default character set  
   utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)                                
                                                                                      

In PDOStatement.php line 2:
                                                                                      
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'password_resets' a  
  lready exists                                                                       
                                                                                      

In PDOStatement.php line 2:
                                                                                      
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'password_resets' a  
  lready exists                                                                       
                                                                                      

[root@iZ2ze2nevqtdxk2qbmp0jaZ www]# 
@Tai7sy

**Comment by Tai7sy** [comment]
你这个问题有点严重哦，你数据库不是自动生成的吗

**Comment by Tai7sy** [comment]
这个版本升级了数据库结构，运行上述命令会自动升级数据库，但是看你的命令输出，提示的内容说明数据库不是程序维护的，强行执行可能会损坏数据

**Comment by 928882650** [comment]
我一脸懵逼。。。用的都是命令啊，没有手动操作过什么。大佬有功夫看下嘛，账号是我Q，红包感谢！~@Tai7sy
