### ISSUE TITLE
支付驱动未找到

### ISSUE THREAD

**Issue by zhujitop** [Tai7sy/card-system#37]
今天安装了新版本2.3的。
微信扫码支付一直提示：支付驱动未找到

不知道为何？
我还去重新设置了微信支付号的32位密钥。

**Comment by jihuoxia** [comment]
我也是遇到了微信支付 提示 支付驱动未找到
微信扫码和H5都提示支付驱动未找到

**Comment by zhujitop** [comment]
> 官网微信支付请将支付驱动改为“WeChat” 
> 搭建后默认的是小写导致的此问题，将在下个个版本修复

请问怎么购买商业版？
商业版本是多商户的吗？
