### ISSUE TITLE
支付宝手机支付完成后订单依然显示未支付，点击支付后才显示订单成功。

### ISSUE THREAD

**Issue by t7aliang** [Tai7sy/card-system#370]
之前对接Paypal时候也是PC端正常，手机支付后订单显示未支付。后来添加了同域名的API网址解析PayPal的两种支付方式都能成功了。
今天对接支付宝的时候，也是同样的问题，PC端正常，手机支付后订单显示未支付，商品数量不变。在查询订单的页面点击一下支付才可弹出支付成功的页面，商品数量随之减少。
这应该怎么配置呢？支付宝的渠道是电脑网站支付和手机网站支付。

**Comment by Tai7sy** [comment]
说明通知失败了，支付宝通知你服务器失败 原因很多了

**Comment by Tai7sy** [comment]
说明通知失败了，支付宝通知你服务器失败 原因很多了

**Comment by t7aliang** [comment]
支付宝手机支付的回调地址应该如何填写？



在 2021年3月7日，上午12:39，风铃 <notifications@github.com> 写道：

﻿

说明通知失败了，支付宝通知你服务器失败 原因很多了

**Comment by Tai7sy** [comment]
点击支付方式最后的链接按钮，获取异步通知地址

**Comment by t7aliang** [comment]
感谢回答，已经解决了，没有留意到这个按钮的信息。
