### ISSUE TITLE
您好！请问建立数据库出现下面的错误是什么问题？

### ISSUE THREAD

**Issue by dayn97** [Tai7sy/card-system#372]
Warning: require(/www/wwwroot/127.0.0.1/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/127.0.0.1/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/127.0.0.1/vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/127.0.0.1/artisan on line 18

Fatal error: require(): Failed opening required '/www/wwwroot/127.0.0.1/vendor/autoload.php' (include_path='.:/www/server/php/73/lib/php') in /www/wwwroot/127.0.0.1/artisan on line 18

**Comment by dayn97** [comment]
已解决，但是安装了没有客户管理项目，不知道这个功能要怎么启用？

**Comment by Tai7sy** [comment]
配置rewrite规则
