### ISSUE TITLE
新版本背景音乐设置连接后不播放求大佬请教需要配置什么

### ISSUE THREAD

**Issue by sevenage** [Tai7sy/card-system#373]

**Comment by sevenage** [comment]
</script><audio autoplay="" loop=""><source src="http://sa.sycdn.kuwo.cn/922e8993f7fa41dc5594f54c97c73e50/604d6a16/resource/n1/53/22/2777080926.mp3"></audio>  只能添加代码了

**Comment by sevenage** [comment]
`</script><audio autoplay="" loop=""><source src="http://sa.sycdn.kuwo.cn/922e8993f7fa41dc5594f54c97c73e50/604d6a16/resource/n1/53/22/2777080926.mp3"></audio>`

**Comment by Tai7sy** [comment]
代码没问题，可能浏览器拦截了？

**Comment by sevenage** [comment]
这样 好我再试试&nbsp; 感谢大佬回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月19日(星期五) 凌晨0:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tai7sy/card-system] 新版本背景音乐设置连接后不播放求大佬请教需要配置什么 (#373)





 
代码没问题，可能浏览器拦截了？
