### ISSUE TITLE
您好，删除查询记录的联系方式查询该如何删除

### ISSUE THREAD

**Issue by lookjazz** [Tai7sy/card-system#374]
我只想保留浏览器缓存和订单号查询的方式，删除联系方式查询。该如何做
（因为现在流行查询QQ绑定的手机号来查订单。。加了查询密码，但是总有人不明白）

**Comment by Tai7sy** [comment]
这个没有选项可以关闭，需要自己源码修改

app/http/shop/里面改

**Comment by lookjazz** [comment]
谢谢
