### ISSUE TITLE
风铃大大 可以更新码支付默认域名显示成自己的域名吗？

### ISSUE THREAD

**Issue by 1274936135** [Tai7sy/card-system#376]
![image](https://user-images.githubusercontent.com/28992655/112261126-2ea5a700-8ca6-11eb-8264-f55b6149aecf.png)

**Comment by 1274936135** [comment]
![image](https://user-images.githubusercontent.com/28992655/112300547-eef5b400-8cd3-11eb-94d3-3320a86ae95d.png)

**Comment by 1274936135** [comment]
希望风铃大大 更新一下

**Comment by Tai7sy** [comment]
可以自己替换 app/library/gateway/pay/
里面找到codepay目录的api.php文件

自己替换
