### ISSUE TITLE
后台首页报错

### ISSUE THREAD

**Issue by hiCasper** [Tai7sy/card-system#378]
访问首页，提示 “day 字段是必须的”

Laravel中log内容：
`Caught a UnauthorizedHttpException {"exception":"[object](Symfony\\Component\\HttpKernel\\Exception\\UnauthorizedHttpException(code: 0): Token not provided at /***/vendor/tymon/jwt-auth/src/Http/Middleware/BaseMiddleware.php:2)`

请求URL：/api/admin/order/stat?day=7      返回HTTP 422错误
直接访问此地址，提示 “您需要登录您的账户再进行此操作”

**Comment by Tai7sy** [comment]
这种情况属于post数据丢失，通常是你https跳转/开启反代没配好
等等原因导致

**Comment by hiCasper** [comment]
我在控制台看到请求是GET类型，参数应该都带上了，并且https为nginx原生实现，套cloudflare也没有设置过别的。
![](https://ae01.alicdn.com/kf/Ue59a40300c6347999294c30627ed474cV.jpg)

**Comment by Tai7sy** [comment]
可以去掉https试试, 大概率你http强跳转没配好
