### ISSUE TITLE
请问能麻烦写一个V免签对接的Api.php吗

### ISSUE THREAD

**Issue by xiaoyang-yang** [Tai7sy/card-system#379]
请问能麻烦写一个V免签对接的Api.php吗？

**Comment by qinghuas** [comment]
+1

**Comment by a1361663667** [comment]
同样需要！

**Comment by rrkai** [comment]
需求V免签的人越来越多了!!!+10086

**Comment by ios3c** [comment]
一起集资就好了，别天天想着白嫖，这样不好，大哥怎么样？ @ilay1678

**Comment by qq854115156** [comment]
+1

**Comment by dengzhuo111** [comment]
你们说的这个
![image](https://user-images.githubusercontent.com/69563943/114290497-bcf59780-9ab2-11eb-8388-fd0f777d5f68.png)

**Comment by qq854115156** [comment]
> 你们说的这个
> ![image](https://user-images.githubusercontent.com/69563943/114290497-bcf59780-9ab2-11eb-8388-fd0f777d5f68.png)

求分享啊

**Comment by xiaoyang-yang** [comment]
我已经花钱找人写好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tai7sy/card-system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月11日(星期天) 中午11:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tai7sy/card-system] 请问能麻烦写一个V免签对接的Api.php吗 (#379)





  
你们说的这个
 
  
求分享啊

**Comment by qq854115156** [comment]
> 我已经花钱找人写好了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tai7sy/card-system" ***@***.***&gt;; 发送时间:&nbsp;2021年4月11日(星期天) 中午11:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Tai7sy/card-system] 请问能麻烦写一个V免签对接的Api.php吗 (#379) 你们说的这个 求分享啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以分享么

**Comment by rrkai** [comment]
> 我已经花钱找人写好了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tai7sy/card-system" ***@***.***&gt;; 发送时间:&nbsp;2021年4月11日(星期天) 中午11:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Tai7sy/card-system] 请问能麻烦写一个V免签对接的Api.php吗 (#379) 你们说的这个 求分享啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

V免签问题挺多的...最好是换成他的升级版 https://github.com/dreamncn/VPay
这个我测试了,很多V免签的问题他都没了..

**Comment by shijie32177** [comment]
> 我已经花钱找人写好了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tai7sy/card-system" ***@***.***&gt;; 发送时间:&nbsp;2021年4月11日(星期天) 中午11:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Tai7sy/card-system] 请问能麻烦写一个V免签对接的Api.php吗 (#379) 你们说的这个 求分享啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

默认没对接之前支付nginx返回是404，你们也一样吗？

**Comment by moyun157** [comment]
有大佬能教我搭建吗，小白不懂，有偿的,qq1574177655

**Comment by 2399483979** [comment]
易支付：http://mzf.jvhezs.com/
（不用挂机，但是要到凌晨才结账）
码支付http://zf.jvhezs.com/
（即时到账，但要挂机）
以上都不用身份证，营业执照注册。真正适合个人发卡网
QQ讨论群：978095958

**Comment by Tai7sy** [comment]
3.14 已加入支持, 详细参考
https://github.com/Tai7sy/card-gateway/tree/master/Pay/VPay
