### ISSUE TITLE
支付宝 - 高级手机网站支付V4调起不了支付宝客户端

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#38]
遇到以下问题，大神能否在完善一下
1.在手机浏览器上用支付宝 - 高级手机网站支付V4接口支付的时候，即使支付宝客户端都已经打开，还是调起不了，只能在浏览器登陆支付宝账号支付，而且付完之后，显示了卡密，但是关闭不了窗口，点"关闭“俩字没反应”
2.官方接口的微信支付提示找不到驱动，测试了几台服务器都这样。

**Comment by Tai7sy** [comment]
1. "支付宝 - 高级手机网站支付V4 " 这个接口是直接跳转支付宝官方wap站, 若无法唤起可以联系支付宝
2. "微信支付官方接口" 请将支付驱动名称改为 "WeChat" (大写), 程序搭建后默认的是小写导致的此问题, 将在下个版本修复，感谢反馈

**Comment by jihuoxia** [comment]
改为 "WeChat" (大写)以后，可以支付了
PC网站上是没问题了，移动端还有点问题
1.在微信里打开时，不能长按二维码识别，只能截图或者用另一个手机扫，选H5支付提示不能在微信内使用，在手机浏览器里选H5支付，提示网页无法打开（我的微信商户开通过H5支付了）。
H5支付目前看来是在浏览器和微信里都无法使用。
2.建议改成微信内打开直接调起微信支付，浏览器里打开能实现调起微信就调起，不能实现就展示二维码，无法支付的场景屏蔽显示（比如微信里H5）。用户一顿操作之后提示不能支付，很可能就黄了

**Comment by Tai7sy** [comment]
@jihuoxia 
微信的支付SDK非常垃圾, 二维码支付在微信里面无法直接跳转(支付宝和QQ都是支持的)
微信H5在微信里面无法调用, 但是外部是可以调用的, 你这边出错的话可以再找下原因
总结一下,  微信内部只能使用微信自带的JSAPI发起支付, 非常臃肿和麻烦

**Comment by Tai7sy** [comment]
解决方案如下，在你的网站统计代码or客服代码里面添加下面几句

`if(navigator.userAgent.match(/MicroMessenger/i) !== null) alert('请点击右上角<...>，选择在<浏览器打开>')`

**Comment by Tai7sy** [comment]
版本2.4已经加入微信内逻辑判断
微信内使用微信方式支付(扫码/H5)，皆会使用JSAPI调用微信支付。
使用前请配置微信公众号的授权域名(用于获取当前微信openid进行下单)和微信支付内的JSAPI域名。

**Comment by jihuoxia** [comment]
2.4版本功能很实用了，微信支付体验很好，
还有一点建议：
1.界面尽量简洁扁平化一些，去除一切不必要的操作和步骤，更切合当下，下拉框更像10年前的东西。。
2.商品和类型能不能直接排列，类型相当于标题，标题下面直接排列商品，每个商品名称结束显示价格和购买小按钮（因为用发卡系统的商品不会很多，直接排出来更省事，简洁。如果商品很多，那么用下拉框选，一屏幕也显示不全那体验也是不好。下拉框选类型在选商品，操作有些繁琐，感觉不出优点）
3.后台能否加上可以给每个商品单独设置小标签，比如热销，新品，推荐等小标签，标签可以是图标，或者直接文字外面套方框，不同的标签不同底色。
4.公告最好后台可设置显不显示，背景最好能支持php文件，比如想用bing的php接口文件当背景，每天自动换壁纸，当前版本好像是不支持。

**Comment by jihuoxia** [comment]
搞错了，目前版本背景支持php文件

**Comment by Tai7sy** [comment]
123条都和店铺模板有关, 这个新的店铺模板大概要等等了
4完全可以自己实现接口, 比如 `https://open.saintic.com/api/bingPic/`
