### ISSUE TITLE
您好，关于Payjs的问题 

### ISSUE THREAD

**Issue by youzi199900** [Tai7sy/card-system#381]
支付渠道添加了payjs支付
我测试VX支付的时候付款成功了，但是不会跳转 而且查询订单也显示未支付这是为什么，我需要怎么做？

**Comment by Tai7sy** [comment]
异步通知没配好吧

**Comment by youzi199900** [comment]
老哥，通知都没问题，好像是Payjs 的通知问题，payjs里 通知都是失败 。如何检查我发一下日志给您？

**Comment by youzi199900** [comment]
![image](https://github.com/youzi199900/111/blob/main/02.png?raw=true)

**Comment by youzi199900** [comment]
![image](https://github.com/youzi199900/111/blob/main/03.png?raw=true)

**Comment by Tai7sy** [comment]
可以开启env里面 app_debug 设置为true，然后查看日志

**Comment by moyun157** [comment]
有大佬能教我搭建吗，小白不懂，有偿的,qq1574177655
