### ISSUE TITLE
大佬 能麻烦集成下VPAY么

### ISSUE THREAD

**Issue by rrkai** [Tai7sy/card-system#389]
https://github.com/dreamncn/VPay

**Comment by corvo007** [comment]
+1

**Comment by fjhechuan** [comment]
+1
或者集成一下这个
https://github.com/szvone/Vmqphp

**Comment by rrkai** [comment]
> +1
> 或者集成一下这个
> https://github.com/szvone/Vmqphp

V免签问题比较多...VPAY是在他的上面改的  作者还有更新..V免签我已经抛弃用了

**Comment by fjhechuan** [comment]
> > +1或
> > 集成一下这个
> > https://github.com/szvone/Vmqphp
> 
> V免签问题比较多... VPAY是在他的上面改的作者还有更新..V免签我已经抛弃用了

那这个能分享一下api文件吗，大佬们，谢谢了

**Comment by rrkai** [comment]
> > > +1或
> > > 集成一下这个
> > > https://github.com/szvone/Vmqphp
> > 
> > 
> > V免签问题比较多... VPAY是在他的上面改的作者还有更新..V免签我已经抛弃用了
> 
> 那这个能分享一下api文件吗，大佬们，谢谢了

https://gitee.com/yuniks/VPAY
我还没开始弄...但他这个有个API文件

**Comment by rrkai** [comment]
> > > +1或
> > > 集成一下这个
> > > https://github.com/szvone/Vmqphp
> > 
> > 
> > V免签问题比较多... VPAY是在他的上面改的作者还有更新..V免签我已经抛弃用了
> 
> 那这个能分享一下api文件吗，大佬们，谢谢了

https://gitee.com/yuniks/VPAY/blob/master/sdk/pay/Vpay.php
