### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by ioscit** [Tai7sy/card-system#39]
[root@iZj6chau6rtlfr1vw1lvtcZ money_ioacg_top]# php artisan key:generate
PHP Parse error:  syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /www/wwwroot/money_ioacg_top/artisan on line 33

**Comment by ioscit** [comment]
> 请确保命令行使用的php版本> 7.0 
> 可以使用`php --version`查看版本
背景图片在哪个文件夹以及修改账号名和后台地址admin变更在哪。大佬

**Comment by Tai7sy** [comment]
背景图片在后台设置, 后台地址无法变更, 请设置高强度密码
