### ISSUE TITLE
订单只要提交不付款优惠券也会被使用

### ISSUE THREAD

**Issue by qq854115156** [Tai7sy/card-system#393]
订单只要提交不付款优惠券也会被使用

**Comment by 1274936135** [comment]
这不是bug 因为你生成了订单 优惠券就扣除了   你仍然可以查询那个未支付的订单   进行支付

**Comment by qq854115156** [comment]
做成订单支付后才使用优惠券不是更好

**Comment by chauyuen** [comment]
这个就有个问题，你需要改成在支付的时候才能使用优惠券，否则就有可能出现优惠券被重复使用。

**Comment by moyun157** [comment]
有大佬能教我搭建吗，小白不懂，有偿的

**Comment by moyun157** [comment]
有大佬能教我搭建吗，小白不懂，有偿的，qq1574177655
