### ISSUE TITLE
大佬，我安装最新版本访问后就只显示这个内容（貌似是某处语法错误）

### ISSUE THREAD

**Issue by lazybri** [Tai7sy/card-system#397]
Parse error: syntax error, unexpected '?' in /www/wwwroot/pay.localhost/vendor/overtrue/wechat/src/Kernel/Support/Helpers.php on line 2

求个解决方案

**Comment by Tai7sy** [comment]
PHP版本最低要求7.0,推荐7.4

**Comment by chauyuen** [comment]
请更新php版本。

**Comment by lazybri** [comment]
谢谢，更新到7.4就不报错了，话说在哪里修改账号？只找到修改密码的入口

**Comment by Tai7sy** [comment]
> 谢谢，更新到7.4就不报错了，话说在哪里修改账号？只找到修改密码的入口

数据库users表
