### ISSUE TITLE
网站安装后出现500错误

### ISSUE THREAD

**Issue by FlyBirdF** [Tai7sy/card-system#40]
查看网站错误日志如下
[2018-12-14 12:14:50] local.ERROR: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No address associated with hostname {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No address associated with hostname at /home/wwwroot/www.yjfaka.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2, PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No address associated with hostname at /home/wwwroot/www.yjfaka.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2, PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: No address associated with hostname at /home/wwwroot/www.yjfaka.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2)
[stacktrace]
#0 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(2): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=\\xE6\\x95\\xB0\\xE6...', '\\xE7\\x94\\xA8\\xE6\\x88\\xB7\\xE5\\x90\\x8D', '\\xE5\\xAF\\x86\\xE7\\xA0\\x81', Array)
#1 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(2): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=\\xE6\\x95\\xB0\\xE6...', '\\xE7\\x94\\xA8\\xE6\\x88\\xB7\\xE5\\x90\\x8D', '\\xE5\\xAF\\x86\\xE7\\xA0\\x81', Array)
#2 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(2): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=\\xE6\\x95\\xB0\\xE6...', Array, Array)
#3 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(2): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): call_user_func(Object(Closure))
#6 /home/wwwroot/www.yjfaka.com/app/Console/Kernel.php(2): Illuminate\\Database\\Connection->getPdo()
#7 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(2): App\\Console\\Kernel->schedule(Object(Illuminate\\Console\\Scheduling\\Schedule))
#8 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(2): Illuminate\\Foundation\\Console\\Kernel->defineConsoleSchedule()
#9 [internal function]: Illuminate\\Foundation\\Console\\Kernel->Illuminate\\Foundation\\Console\\{closure}(Object(Illuminate\\Foundation\\Application))
#10 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): call_user_func(Object(Closure), Object(Illuminate\\Foundation\\Application))
#11 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#12 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(2): Illuminate\\Foundation\\Application->boot()
#13 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#14 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(2): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#15 /home/wwwroot/www.yjfaka.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(2): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#16 /home/wwwroot/www.yjfaka.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"} 
我该如何解决这个问题，求解答

**Comment by Tai7sy** [comment]
请配置你的数据库信息

**Comment by FlyBirdF** [comment]
只是在.env文件中修改数据库信息么？

**Comment by Tai7sy** [comment]
是

**Comment by FlyBirdF** [comment]
已经在.env配置好了mysql数据库信息,还是提示这样的错误
数据库名字是指定的么，还是自定义的

**Comment by Tai7sy** [comment]
1. 如果不会搭建的请严格按照教程步骤来, 教程里面写的很清楚在哪一步需要配置数据库信息
2. 配置好 `.env` 不生效的问题 readme里面有写, 需要执行那几条命令才能生效
