### ISSUE TITLE
卡网更新至3.12之后支付会出现下单错误是什么情况

### ISSUE THREAD

**Issue by xiaobai5165** [Tai7sy/card-system#402]
![111](https://user-images.githubusercontent.com/84277406/118432104-60694600-b70a-11eb-899a-03d96b723692.png)

**Comment by xueba0458** [comment]
我也遇到了！！！

**Comment by Baiyi-zhuixio** [comment]
程序有问题，不要更新，使用之前版本就可以

**Comment by 1457695165** [comment]
已解决，数据库问题

**Comment by Tai7sy** [comment]
新版本增加了订单查询密码, 请检查升级方式是否存在问题
命令行更新会自动增加此字段
https://github.com/Tai7sy/card/blob/master/database/migrations/2021_02_25_152603_add_query_password_to_orders.php
