### ISSUE TITLE
卡网上传本地图片不显示怎么解决

### ISSUE THREAD

**Issue by 1457695165** [Tai7sy/card-system#404]
![QQ浏览器截图20210526011118](https://user-images.githubusercontent.com/84277406/119540026-856f5000-bdbf-11eb-80ac-3673c4e76f69.png)

**Comment by Baiyi-zhuixio** [comment]
You can try to use URL to display pictures, which is the way I use to display pictures

**Comment by Tai7sy** [comment]
宝塔NGINX配置问题，请删除NGINX配置中关于图片结尾的规则
