### ISSUE TITLE
请问怎么设置  商品直链/商品单独链接  啊

### ISSUE THREAD

**Issue by lzhmhznr** [Tai7sy/card-system#407]
请问怎么设置  商品直链/商品单独链接  啊,  比如我想卖商品ID=def  然后从网址  abc.com/p/def  就直接能购买了
不用输入   http://abc.com/p/d2kdljovc6fyv2q7nxt1   后面的1大长串字符

**Comment by Tai7sy** [comment]
这个是随机生成的, 不支持自己设置, 确实需要的话可以设置nginx/apache rewrite规则
