### ISSUE TITLE
商品描述不能上传照片，不能使用html语言美化

### ISSUE THREAD

**Issue by runkeychow** [Tai7sy/card-system#41]
商品描述不能上传照片，上传照片提示错误，不能使用html语言美化。

**Comment by Tai7sy** [comment]
上传照片提示错误请自己排查原因

**Comment by runkeychow** [comment]
<!DOCTYPE html>
 <html lang="en">
 <head>
 <meta charset="utf-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>500</title>
 
 
 <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
 
 
 <style>
 html, body {
 background-color: #fff;
 color: #636b6f;
 font-family: 'Raleway', sans-serif;
 font-weight: 100;
 height: 100vh;
 margin: 0;
 }
 
 .full-height {
 height: 100vh;
 }
 
 .flex-center {
 display: flex;
 justify-content: center;
 }
 
 .position-ref {
 position: relative;
 }
 
 .content {
 text-align: center;
 padding-top: 30vh;
 }
 
 .title {
 font-size: 36px;
 padding: 20px;
 }
 </style>
 </head>
 <body>
 <div class="flex-center position-ref full-height">
 <div class="content">
 <div class="title">
 未知错误，请联系客服
 </div>
 </div>
 </div>
 </body>
 </html>
 <!--
 fatal error

**Comment by runkeychow** [comment]
希望可以直接调用图床地址

**Comment by Tai7sy** [comment]
500错误参考readme解决
图床那么多, 我也不知道添加哪个啊, 因此暂不考虑, 又需要可以自行添加 
以后版本会考虑手动添加图片URL
