### ISSUE TITLE
请问为什么卡网背景不显示了

### ISSUE THREAD

**Issue by Baiyi-zhuixio** [Tai7sy/card-system#410]
使用的url链接是正常的，浏览器能直接打开图片，但是放在了发卡网后台背景图片，卡网就打不开背景

**Comment by Baiyi-zhuixio** [comment]
我清除了缓存也一样不行

**Comment by Tai7sy** [comment]
可能是https原因？浏览器按f12有报错吗

**Comment by Baiyi-zhuixio** [comment]
> 可能是https原因？浏览器按f12有报错吗

http，f12看起来没问题，背景图片就是不显示

**Comment by Tai7sy** [comment]
发一下看看
