### ISSUE TITLE
求助，卡网打不开了

### ISSUE THREAD

**Issue by Baiyi-zhuixio** [Tai7sy/card-system#411]
一直显示   未知错误，请检查日志
该怎么办

**Comment by Tai7sy** [comment]
可以发一下日志内容

**Comment by Baiyi-zhuixio** [comment]
> 可以发一下日志内容
> 
> We can post the logs

哪个是日志啊..

**Comment by Tai7sy** [comment]
首页readme

**Comment by Baiyi-zhuixio** [comment]
> 可以发一下日志内容

那个Log.php就是日志吗？

**Comment by Baiyi-zhuixio** [comment]
> 首页readme

我没有找到readme

**Comment by Baiyi-zhuixio** [comment]
> 可以发一下日志内容

<h1 align="center">CardSystem</h1>
<p align="center">
<a href="https://github.com/Tai7sy/card-system/releases"><img src="https://img.shields.io/badge/version-3.02-blue.svg?style=flat-square" alt="License"></a>
<img alt="PHP from Packagist badge" src="https://img.shields.io/badge/php-%3E%3D7.0.0-brightgreen.svg?style=flat-square">
<a href="https://opensource.org/licenses/Apache-2.0"><img src="https://img.shields.io/badge/License-MIT-brightgreen.svg?style=flat-square" alt="License"></a>
<a href="https://travis-ci.org/Tai7sy/card-system"><img src="https://img.shields.io/travis/Tai7sy/card-system.svg?style=flat-square" alt="Travis"></a>
<br><br>
<a href="https://github.com/Tai7sy/card-system/wiki/%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B---BT%E9%9D%A2%E6%9D%BF">安装文档</a>&nbsp;&nbsp;
<a href="https://github.com/Tai7sy/card-system/wiki/%E6%9B%B4%E6%96%B0%E6%95%99%E7%A8%8B">更新文档</a>
</p>

**Comment by Baiyi-zhuixio** [comment]
> 首页readme



> > 可以发一下日志内容
> 
> # CardSystem
> [![License](https://camo.githubusercontent.com/b2d88e7f271d05bc25c6a70ca0281e5f760459cc480201caeb10686f4375208e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f76657273696f6e2d332e30322d626c75652e7376673f7374796c653d666c61742d737175617265)](https://github.com/Tai7sy/card-system/releases) ![PHP from Packagist badge](https://camo.githubusercontent.com/90ed51897e863cb720fdda6fe4752785992f0ec5e912766446c84ae8f22ff877/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f7068702d253345253344372e302e302d627269676874677265656e2e7376673f7374796c653d666c61742d737175617265) [![License](https://camo.githubusercontent.com/a7c74f30b55adc967f690227203b6fc7a6dede137ad92a3c0a86d9a50649faaf/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4c6963656e73652d4d49542d627269676874677265656e2e7376673f7374796c653d666c61742d737175617265)](https://opensource.org/licenses/Apache-2.0) [![Travis](https://camo.githubusercontent.com/1be53d766e2976a70d537c14f9b6bfcf985ba355d51fb970f4ad9ae9426a08b5/68747470733a2f2f696d672e736869656c64732e696f2f7472617669732f5461693773792f636172642d73797374656d2e7376673f7374796c653d666c61742d737175617265)](https://travis-ci.org/Tai7sy/card-system)
> 
> [安装文档](https://github.com/Tai7sy/card-system/wiki/%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B---BT%E9%9D%A2%E6%9D%BF)   [更新文档](https://github.com/Tai7sy/card-system/wiki/%E6%9B%B4%E6%96%B0%E6%95%99%E7%A8%8B)



> 首页readme

请大佬看看这是怎么回事

**Comment by Tai7sy** [comment]
提示500错误 / 未知错误

storage/logs 里面有错误详细内容, 可以自行参考解决, 或者附录log文件提交issue
看不见吗。。。

**Comment by Baiyi-zhuixio** [comment]
> 提示500错误 / 未知错误
> 
> storage/logs 里面有错误详细内容, 可以自行参考解决, 或者附录log文件提交issue
> 看不见吗。。。

好的...谢谢大佬

**Comment by Baiyi-zhuixio** [comment]
> 提示500错误 / 未知错误
> 
> storage/logs 里面有错误详细内容, 可以自行参考解决, 或者附录log文件提交issue
> 看不见吗。。。


[log.zip](https://github.com/Tai7sy/card-system/files/6638184/log.zip)

**Comment by Baiyi-zhuixio** [comment]
> > 提示500错误 / 未知错误
> > storage/logs 里面有错误详细内容, 可以自行参考解决, 或者附录log文件提交issue
> > 看不见吗。。。
> 
> [log.zip](https://github.com/Tai7sy/card-system/files/6638184/log.zip)

请问这个是怎么回事...

**Comment by Tai7sy** [comment]
#412
