### ISSUE TITLE
为啥卡网后台存库显示是负数的.....

### ISSUE THREAD

**Issue by Baiyi-zhuixio** [Tai7sy/card-system#416]
一会儿就500错误了....

**Comment by Baiyi-zhuixio** [comment]
每一次在卡网买一次东西之后卡网就会提示500错误......需要清理缓存才能显示出来...

**Comment by Tai7sy** [comment]
说明网站目录权限设置的不对, 请参考首页readme清空缓存并合理设置目录权限(www用户+755)

**Comment by Baiyi-zhuixio** [comment]
> 说明网站目录权限设置的不对, 请参考首页readme清空缓存并合理设置目录权限(www用户+755)

我上后台看了一下，，是755权限。。

**Comment by Baiyi-zhuixio** [comment]
> 说明网站目录权限设置的不对, 请参考首页readme清空缓存并合理设置目录权限(www用户+755)

权限是755，清空了缓存商品列表的库存是-1

**Comment by Tai7sy** [comment]
可以参考首页readme 情空一次缓存，
库存负数可能得数据库编辑了
