### ISSUE TITLE
大佬我网站前面的ico小标签无法被检测到

### ISSUE THREAD

**Issue by SweetlandDSL** [Tai7sy/card-system#423]
已经将`<link rel="icon" type="image/x-icon" href="icon.ico" />`放置于根index.html文件夹的<head><head>之间的地方，但是始终无法被找到，求解惑谢谢

**Comment by SweetlandDSL** [comment]
已经将.ico图片放置于index.html文件同属地方，但还是无法被找到/显示

**Comment by Tai7sy** [comment]
名字似乎是favicon.ico？

**Comment by SweetlandDSL** [comment]
大佬我试过，依旧没有效果

**Comment by Tracalight** [comment]
> 已经将`<link rel="icon" type="image/x-icon" href="icon.ico" />`放置于根index.html文件夹的之间的地方，但是始终无法被找到，求解惑谢谢

public文件夹内就有icon 自己替换那个就行
