### ISSUE TITLE
升级最新版后，那个添加音乐的用不了。加了一个音乐链接，但是它不会播放

### ISSUE THREAD

**Issue by zhiqiuchn** [Tai7sy/card-system#424]
升级最新版后，那个添加音乐的用不了。加了一个音乐链接，但是它不会播放

**Comment by SmilingCoffins** [comment]
> 升级最新版后，那个添加音乐的用不了。加了一个音乐链接，但是它不会播放
他那个加音乐链接是无效果   好多东西没作用  音乐 加图片不能本地上传  邮箱哪里也没作用无效果

**Comment by SmilingCoffins** [comment]
> 升级最新版后，那个添加音乐的用不了。加了一个音乐链接，但是它不会播放
    </script>
<audio autoplay="autoplay" loop=""><source src="这里改成你要的音乐链接"></audio>
这种的https://link.hhtjim.com/163/1855383602.mp3
这个代码放到网站设置客服代码(QQ等)里面

**Comment by SmilingCoffins** [comment]
</script>
<audio autoplay="autoplay" loop=""><source src="这里改成你要的音乐链接"></audio>
这种的https://link.hhtjim.com/163/1855383602.mp3

**Comment by SmilingCoffins** [comment]
</script>
<audio autoplay="autoplay" loop=""><source src="这里改成你要的音乐链接"></audio>
这种的https://link.hhtjim.com/163/1855383602.mp3
[这个代码放到网站设置客服代码(QQ等)里面[]
回复消息不能发代码

**Comment by SmilingCoffins** [comment]
1.     </script>
<audio autoplay="autoplay" loop=""><source src="https://link.hhtjim.com/163/1855383602.mp3"></audio>

**Comment by SmilingCoffins** [comment]
<audio autoplay="autoplay" loop=""><source src="https://link.hhtjim.com/163/1855383602.mp3"></audio>
