### ISSUE TITLE
当面付那个好像用不了

### ISSUE THREAD

**Issue by zhiqiuchn** [Tai7sy/card-system#425]
我后台配置的当面付东西都是对的，但是点击支付时，那个没有反应。

**Comment by SmilingCoffins** [comment]
> 我后台配置的当面付东西都是对的，但是点击支付时，那个没有反应。

有反应啊  
你ID  公钥  私钥填的对不对

**Comment by SmilingCoffins** [comment]
> 我后台配置的当面付东西都是对的，但是点击支付时，那个没有反应。

传授配置当面付加Discord

**Comment by SmilingCoffins** [comment]
https://discord.gg/y6wN3F58
