### ISSUE TITLE
邮箱设置没作用

### ISSUE THREAD

**Issue by SmilingCoffins** [Tai7sy/card-system#426]
作者给解释一下 为啥不能使用邮箱服务  点击测试提示
timeout of 15000ms exceeded

**Comment by SmilingCoffins** [comment]
解决方法[[url=https://sm.ms/image/iCacHUJBPgME9sh][img]https://i.loli.net/2021/07/15/iCacHUJBPgME9sh.png[/img][/url]](url)

**Comment by SmilingCoffins** [comment]
解决方法是看图片方法改https://i.loli.net/2021/07/15/iCacHUJBPgME9sh.png

**Comment by WilliamFWJ** [comment]
你好，我也遇到这个问题了，图片好像失效了，能否重发一下

**Comment by SmilingCoffins** [comment]
图片没有失效你复制粘贴浏览器打开 不要直接点击打开
