### ISSUE TITLE
安装数据包的时候 给我跳这个错误

### ISSUE THREAD

**Issue by Luo-jaiwen** [Tai7sy/card-system#430]
In KeyGenerateCommand.php line 4:
                                                                                                   
  file_get_contents(/www/wwwroot/daxiong.space/.env): failed to open stream: No such file or dire  
  ctory                                                                                            
                              
![image](https://user-images.githubusercontent.com/86880332/124872255-9be00c80-dff7-11eb-99b7-e3a4a119e29b.png)

**Comment by Tai7sy** [comment]
按照安装教程来
