### ISSUE TITLE
为什么我不能下载发卡系统

### ISSUE THREAD

**Issue by MoliseHack** [Tai7sy/card-system#432]
在我下载的时候出现了问题，请帮帮我

**Comment by SmilingCoffins** [comment]
你不能下载原因就是中国大陆墙的原因造成

**Comment by SmilingCoffins** [comment]
3.13版本的风铃https://wwx.lanzoui.com/iUOzNnl35vi

**Comment by MoliseHack** [comment]
> 3.13版本的风铃https://wwx.lanzoui.com/iUOzNnl35vi

好的，我已经上传至服务器了，
但是还有一个问题，我不能构建数据库

**Comment by SmilingCoffins** [comment]
请私聊我 QQ或者Discord

**Comment by SmilingCoffins** [comment]
Discord
https://discord.gg/BZczMQDF

**Comment by SmilingCoffins** [comment]
不能构建数据库是什么状况

**Comment by SmilingCoffins** [comment]
php7.3版本

**Comment by SmilingCoffins** [comment]
更简便方法导入数据库

**Comment by SmilingCoffins** [comment]
这个是数据库  你自己导入数据库吧
https://wwx.lanzoui.com/iUOzNnl35vi

**Comment by SmilingCoffins** [comment]
如果密码不是默认 安装教程里面有重置密码地方
