### ISSUE TITLE
为什么会白屏啊

### ISSUE THREAD

**Issue by ghost** [Tai7sy/card-system#433]
非宝塔面板
（缓存也清除了）
php版本7.4-mysql版本8.0
是不是因为mysql版本的原因
![563FA6DF-51C2-432B-8CFD-39A142D50F64](https://user-images.githubusercontent.com/87112537/125152266-7b928800-e186-11eb-94c6-275c002bdbbe.jpeg)

**Comment by SmilingCoffins** [comment]
请用低版本php7.2

**Comment by Tai7sy** [comment]
F12 看错误原因
