### ISSUE TITLE
symfony/debug的Test文件可以删除吧，我用软件检测说这玩意里面有后门病毒

### ISSUE THREAD

**Issue by Nansir0808** [Tai7sy/card-system#439]
![210804170651](https://user-images.githubusercontent.com/77816761/128154394-5a918b99-2692-44c4-99a4-93225cf4adce.png)
小白一个，啥都不懂的那种，我就直接删除了Test文件夹，目前未发现报错。

**Comment by Tai7sy** [comment]
https://github.com/symfony/debug
