### ISSUE TITLE
请问在docker内如何导入数据库？能否提供一个sql文件？

### ISSUE THREAD

**Issue by NBY** [Tai7sy/card-system#44]

**Comment by Tai7sy** [comment]
运行命令行 `php artisan migrate:fresh --seed` 即可自动生成新的数据库

**Comment by NBY** [comment]
> 运行命令行 `php artisan migrate:fresh --seed` 即可自动生成新的数据库

我进入docker内执行构建数据库相关命令无回显也没有新的表增加

**Comment by Tai7sy** [comment]
那是否可以把执行的错误输出发一下

**Comment by NBY** [comment]
root@Tokyo:~/docker/www/bluecard.cc# docker exec -it 42da1112ab66 bash
root@42da1112ab66:/var/www/html# cd bluecard.cc/
root@42da1112ab66:/var/www/html/xxxx.cc# php artisan migrate:fresh --seed
root@42da1112ab66:/var/www/html/xxxx.cc# exit
exit
没错误也没其他提示 很蛋疼
PHP 7.2.7 (cli) (built: Nov 29 2018 19:01:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.7, Copyright (c) 2002-2018, by ionCube Ltd.
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
    with Zend OPcache v7.2.7, Copyright (c) 1999-2018, by Zend Technologies

**Comment by NBY** [comment]
root@xxxxx:~/docker/www/xxxxx.cc# docker exec -it 42xxxxxfab66 bash
root@42xxxxxfab66:/var/www/html# cd xxxxx.cc/
root@42xxxxxfab66:/var/www/html/xxxxx.cc# php artisan migrate:fresh --seed
root@42xxxxxfab66:/var/www/html/xxxxx.cc# exit
exit
没输出任何信息 很蛋疼
PHP 7.2.7 (cli) (built: Nov 29 2018 19:01:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.7, Copyright (c) 2002-2018, by ionCube Ltd.
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
    with Zend OPcache v7.2.7, Copyright (c) 1999-2018, by Zend Technologies

**Comment by Tai7sy** [comment]
可以运行一下下面的命令, 如果依然没有输出请检查你的php环境是否完整
```
ubuntu@Windy:/mnt/d/MyProjects/card/card$ php --version
PHP 7.2.10 (cli) (built: Oct 20 2018 18:54:13) ( NTS )
...
ubuntu@Windy:/mnt/d/MyProjects/card/card$ php artisan
Laravel Framework 5.5.44

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
....
```

**Comment by NBY** [comment]
看起来是我环境不完整 我修改一下Dockerfile重新构建一下镜像

**Comment by chenzhen1565** [comment]
您好，我是win环境，能否给个sql文件，我导入一下

**Comment by Tai7sy** [comment]
命令行执行php artisan migrate --seed
会自动创建数据库

**Comment by chenzhen1565** [comment]
我是windows的电脑。本地先测试一下系统，没办法执行命令行，能否直接分享个sql文件
