### ISSUE TITLE
/admin为啥404

### ISSUE THREAD

**Issue by 1269832711** [Tai7sy/card-system#440]
Not Found
The requested URL was not found on this server.

Apache Server at bufferedreader.top Port 443

**Comment by Tai7sy** [comment]
按照安装教程来，rewrite规则你没配好

**Comment by gzy700809** [comment]
请问作者可以出一个图片教程吗？不好意思，我知道，我这样有点冒犯，但是我真的很着急，我看不懂

**Comment by gzy700809** [comment]
> 按照安装教程来，rewrite规则你没配好

请问作者可以出一个图片教程吗？不好意思，我知道，我这样有点冒犯，但是我真的很着急，我看不懂
