### ISSUE TITLE
请问后台登陆后会立刻闪退到登录界面怎么解决

### ISSUE THREAD

**Issue by Chun-QiuCC** [Tai7sy/card-system#451]
安装完了进入/admin输入admin@qq.com和123456登录，但是显示后台不超过1秒闪退回登录界面

**Comment by Tai7sy** [comment]
缓存问题或者https配置问题，都有可能
参考readme清空缓存试试

**Comment by DemoJack** [comment]
清除缓存了，还是进去之后又退回到登录页面了

**Comment by DemoJack** [comment]
> 

你的问题解决了吗？
