### ISSUE TITLE
未知错误  怎么解决啊  求助

### ISSUE THREAD

**Issue by zhangling99** [Tai7sy/card-system#458]
求助
[card_fpm-fcgi-2021-10-09.log](https://github.com/Tai7sy/card-system/files/7315532/card_fpm-fcgi-2021-10-09.log)
求助

**Comment by Tai7sy** [comment]
Access denied for user ''@'localhost' to database

请检查.env文件是否正确配置数据库信息，然后参考readme清空缓存
