### ISSUE TITLE
可以手动添加订单记录吗？

### ISSUE THREAD

**Issue by zhujitop** [Tai7sy/card-system#46]
因为有客户是在别的地方购买了，所以想在这个后台手动添加个记录，好让客户之后可以查询。

**Comment by Tai7sy** [comment]
自己在数据库里面加吧 没有其他办法

**Comment by zhujitop** [comment]
> 自己在数据库里面加吧没有其他办法

好快的回复。。。。
想到了，就是我们后台不是有个备注吗，我们在后台写的备注，用户查询订单的时候，也可以看见这个备注就行了。

**Comment by Tai7sy** [comment]
我感觉既然用户都在其他地方购买了, 没有必要在这个系统内添加了,
打个比方, 你在tmall买的东西, jd肯定查不到的

所以说, 这个提议的使用场景是什么? 能具体描述一下吗

**Comment by zhujitop** [comment]
> 我感觉既然用户都在其他地方购买了，没有必要在这个系统内添加了，
> 打个比方，你在tmall买的东西，jd肯定查不到的
> 
> 所以说，这个提议的使用场景是什么？能具体描述一下吗

我有在tb卖关于次数的产品，比如1块钱可以帮做5次，客户购买的时候就做了1次，还剩下4次，就需要做个记录。
可以不用这个需求了，比较麻烦，现在我设置了1分钱，我自己1分钱购买一次，然后在后台添加备注，他来查询可以看见备注就行了。

**Comment by zhujitop** [comment]
> 我感觉既然用户都在其他地方购买了，没有必要在这个系统内添加了，
> 打个比方，你在tmall买的东西，jd肯定查不到的
> 
> 所以说，这个提议的使用场景是什么？能具体描述一下吗

准备自己改的，才想起是vue，不会这个，我查关键词，手动添加了一句：
[t._v("备注")]),t._v(" "),i("td",[t._v(t._s(e.remark))])]),t._v(" "),i("tr",[i("th",{attrs:{scope:"row"}},
发现没生效，希望您有时间了可以改下，以后有时间了再来学学。
