### ISSUE TITLE
提示,目前库存不足，您还有-1件未发货

### ISSUE THREAD

**Issue by Nisekoi5** [Tai7sy/card-system#460]
版本(3.13)，商品库存100%是足够的，后台可以看到有200多件，并尝试过刷新库存。
下单的时候有一定概率会出现图上这种情况。会发出去2个卡密。并提示库存不足。其中第二行是正常该出现的卡密。
第一行是随机出现一个已经卖过的卡密（其他商品的也有可能）
触发原理不明。。大概8-10个订单就有1次会出现这个情况（最近2天出现3次了）。系统日志没有任何异常。应该如何定位问题所在？
![k](https://user-images.githubusercontent.com/49276902/136728015-59b5284a-442b-4286-aa5a-f251d03b4370.jpg)
。

**Comment by Nisekoi5** [comment]
> 用户实际下单数量是多少？商品卡密是否是单次售卖的卡密？

下单数量为1，是单次售卖的
![2021-10-11 13-28-54](https://user-images.githubusercontent.com/49276902/136737821-ea697876-a2d6-495f-a0b1-33699e74de9b.jpg)
卡密

**Comment by Tai7sy** [comment]
日志里面搜索这个订单号，是否有关于这个订单号的日志内容(库存不足等会记录日志)？
