### ISSUE TITLE
V免签提示签名错误解决方法

### ISSUE THREAD

**Issue by Tai7sy** [Tai7sy/card-system#461]
按照
https://github.com/Tai7sy/card-gateway/tree/master/Pay/VPay

替换Api.php为最新版本即可

**Comment by qingxiablog** [comment]
最新3.15版本好像替换了也不行

**Comment by andyoulovexy** [comment]
> 最新3.15版本好像替换了也不行

是的，确实有这个问题，把https换成http也不行
![image](https://user-images.githubusercontent.com/38940994/220519261-19944a5b-de2d-48b9-ab85-d120cc5468aa.png)
