### ISSUE TITLE
手动修改已经支付的订单卡密

### ISSUE THREAD

**Issue by WilliamFWJ** [Tai7sy/card-system#463]
风铃大佬你好，以下是我的一点小建议，
1.手动修改已经付款的订单的卡密内容 这个功能，不知道可不可行，

**Comment by Tai7sy** [comment]
可以直接修改卡密，订单查询页面会自动同步

**Comment by WilliamFWJ** [comment]
感谢大佬回复，解决了我长久以来的困惑，感谢大佬
