### ISSUE TITLE
支付完成后，返回提示未知错误，请检查日志，标签提示是500

### ISSUE THREAD

**Issue by weiwei9151** [Tai7sy/card-system#464]
但是选择已支付后，可以正常查询订单，正常发货
[card_fpm-fcgi-2021-10-23.log](https://github.com/Tai7sy/card-system/files/7402265/card_fpm-fcgi-2021-10-23.log)
这里是日志

**Comment by WilliamFWJ** [comment]
大佬们，我想请问一下
我也是遇到了同样的情况，
应该如何解决，大佬们可以指导一下小弟我吗？感激不尽
