### ISSUE TITLE
网站可以正常访问但是后台管理卡在加载转圈

### ISSUE THREAD

**Issue by HurryBy** [Tai7sy/card-system#465]
网站可以正常访问但是后台管理卡在加载转圈
一直套了腾讯云的cdn
之前我用ipv6访问正常
然后我朋友用ipv4访问就卡在加载
我就也尝试了ipv4访问然后也卡在加载
然后我再换回去ipv6的时候我也进不去了

**Comment by Tai7sy** [comment]
f12看原因
