### ISSUE TITLE
能不能增加对订单查询密码的描述

### ISSUE THREAD

**Issue by WilliamFWJ** [Tai7sy/card-system#466]
抱歉打扰到风铃大佬，以下是鄙人一些小建议，如果能得到风铃大佬的回复，那实在是感激不尽
1.能不能增加对订单查询密码的描述，比如用户填写了联系方式，但是没有填查询密码就支付，
目前默认的弹窗是“请填写订单查询密码”，这一个弹窗提示可以自定义修改吗？
比如我想改为“请您自行设置一个查询密码”（因为一些用户可能会不知道什么是查询密码）

2.还有一个就是手机访问的时候
联系方式（订单查询重要凭证）
查询密码（订单查询重要凭证）
这个 ”（订单查询重要凭证）“  这个几个字好像颜色有点淡，字体有点细

3.能不能联系方式那里除了QQ 外增加微信和电子邮件

**Comment by Tai7sy** [comment]
1.这个字符串可以用一些编辑器，目录搜索字符串自己替换修改
2.这个应该没法改，这个和前面的是一起的是个placeholder
3.这个应该是指的额外加联系方式字段吗，这种只有手动发货会用到吧

**Comment by WilliamFWJ** [comment]
风铃大佬，很抱歉再次打扰您，（因为我是个小白，好像不太会怎么搜索字符串）
关于如何用编辑器搜索某个字符串（如请填写订单查询密码），风铃大佬能否指点一二，感激不尽，临表涕零。

再次感谢今天风铃大佬 解决我v免签的的问题，再次感谢

**Comment by WilliamFWJ** [comment]
风铃大佬晚上好，请原谅我再次打扰您，
我想请教一下，我是修改了经典主题下的字符串：请填写订单查询密码 ，修改为：请您设置订单查询密码
宝塔下修改后如图：
https://s3.bmp.ovh/imgs/2021/12/6449b26007f55add.png

但是似乎前端没有生效，已经重启了机器，也试过用新的浏览器访问，还是显示修改前的：请填写订单查询密码
https://s3.bmp.ovh/imgs/2021/12/f2e90ef4017fbd60.png

**Comment by Tai7sy** [comment]
comment.js是原始文件  需要修改 min.js结尾的文件
可以直接用common.js覆盖common.min.js

**Comment by WilliamFWJ** [comment]
再次感谢风铃大佬的耐心解答，如果不是您的指点，我可能永远也找不出解决办法，再次衷心感谢
