### ISSUE TITLE
使用负载均衡时主控服务器正常，负载服务器500未知错误

### ISSUE THREAD

**Issue by 777TTTTTTT** [Tai7sy/card-system#468]
[logs_JW4GEW.zip](https://github.com/Tai7sy/card-system/files/7490960/logs_JW4GEW.zip)
![image](https://user-images.githubusercontent.com/80535317/140618879-45e71a15-b23f-42fa-92f2-7943362c692a.png)
负载服务器500未知错误，按readme清空网站缓存后正常，过一会还是报错
麻烦大佬看看

**Comment by Tai7sy** [comment]
[2021-11-07 01:34:42] local.ERROR: Uncaught Exception {"exception":"[object] (ErrorException(code: 0): file_put_contents(/www/wwwroot/zzzz/storage/framework/cache/data/d3/07/d30767922b20db54a8a3846c795b00f2b861e685): failed to open stream: Permission denied at /www/wwwroot/zzzz/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:2)



从报错来看还是目录权限问题导致的，清空缓存后记得目录设置wwwroot用户+777权限

**Comment by 777TTTTTTT** [comment]
按照安装教程设置storage/和bootstrap/cache/的权限了，都是777＋root用户

**Comment by Tai7sy** [comment]
看一下是否有定时任务或者其他东西生成的文件不是wwwroot用户，报错的时候找到对应文件和目录看下权限

**Comment by 777TTTTTTT** [comment]
在storage/framework/cache/data/生成了两个目录，权限是755，目录里的文件权限是655，但没有定时任务和其他东西

**Comment by Tai7sy** [comment]
你的负载均衡是怎么配的？是否使用文件同步之类的手段？

**Comment by Tai7sy** [comment]
另外data里面应该是有两级子目录，要看最终文件权限所有者，是你网站用户还是root之类其他用户

**Comment by Tai7sy** [comment]
这样就是远程连了个数据库，不会生成文件。
网站本身没有root权限但是生成的文件带了root，说明你在其他地方比如后台队列/计划任务里面设置的命令不是wwwroot用户导致的问题，网站本身是wwwroot的话，是没有能力在目录生成root权限的文件

**Comment by 777TTTTTTT** [comment]
那应该怎么解决这个问题呢？

**Comment by 777TTTTTTT** [comment]
没有使用文件同步，主控服务器搭建好之后把文件复制到了负载服务器上，然后负载服务器连接主控服务器数据库

**Comment by 777TTTTTTT** [comment]
![image](https://user-images.githubusercontent.com/80535317/140638639-c28e7126-9e8e-4a56-b126-83f10ae54f5c.png)

**Comment by Tai7sy** [comment]
负载服务器上也运行一下命令设置权限即可, 或者直接在负载服务器搭建, 服务器地址写你另外服务器就可以了
