### ISSUE TITLE
发卡有漏洞,被成功偷卡好几次了

### ISSUE THREAD

**Issue by 1274936135** [Tai7sy/card-system#471]
![X 98HJ5A8A_NIV@AP%G_0TB](https://user-images.githubusercontent.com/28992655/141346746-942ccdfa-780b-4fe5-957c-41906c9f5ba2.jpg)

**Comment by Tai7sy** [comment]
拿出证据

**Comment by 1274936135** [comment]
QQ通过一下 给你发聊天

**Comment by 1274936135** [comment]
记录
