### ISSUE TITLE
能否加入自己可调用的api

### ISSUE THREAD

**Issue by HurryBy** [Tai7sy/card-system#472]
访问api要验证一个key，key生成5分钟有效 key也通过一个api生成 或者直接调用api
就是想做一个访问api生成优惠卷然后能够返回优惠卷的东西 因为要跟游戏联动qaq

**Comment by Tai7sy** [comment]
所有系统前后端分离，鉴权使用oauth2，本身所有的页面都是api，可以自己f12查看

另外可以自己直接写个单页链接数据库生成优惠券，更加符合你的需求一些
