### ISSUE TITLE
网址打开以后，在商品购买跟菜单查询出现英文弄不掉

### ISSUE THREAD

**Issue by Perfume-code** [Tai7sy/card-system#479]
![105](https://user-images.githubusercontent.com/85380564/143847326-8eb4cdde-81fc-4f91-8a82-988886315001.jpg)
打开以后就显示add_shopping_cart/search.不知道怎么解决，哪里出问题了？版本是最新版本

**Comment by Perfume-code** [comment]
@ilay1678 @Tai7sy @zfbjk ？

**Comment by Tai7sy** [comment]
这里是materialdesign的图标文件，显示不出来请考虑换个现代一点的浏览器

**Comment by Perfume-code** [comment]
各种浏览器都试过了，在手机端打开才会有，电脑没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月29日(周一) 晚上10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tai7sy/card-system] 网址打开以后，在商品购买跟菜单查询出现英文弄不掉 (Issue #479)




 
这里是materialdesign的图标文件，显示不出来请考虑换个现代一点的浏览器

**Comment by WuMe-sicx** [comment]
这个问题我也有，我两个服务器测试发现 国内服务器正常显示，国外部分图标无法显示

**Comment by Perfume-code** [comment]
好吧，那也没办法了，新版本的问题吧，以前的版本没出现过这个问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月9日(周四) 上午9:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tai7sy/card-system] 网址打开以后，在商品购买跟菜单查询出现英文弄不掉 (Issue #479)




 
这个问题我也有，我两个服务器测试发现 国内服务器正常显示，国外部分图标无法显示

**Comment by WuMe-sicx** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Tai7sy** [comment]
1. 浏览器原因导致图标格式无法识别，ie11以下(以及同时期旧版本浏览器)可能存在
2. 未知原因导致woff字体文件缺失  这个建议电脑端f12模拟手机看下报错内容

**Comment by Perfume-code** [comment]
可以删除这个图标不？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月12日(周日) 下午4:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tai7sy/card-system] 网址打开以后，在商品购买跟菜单查询出现英文弄不掉 (Issue #479)




  
浏览器原因导致图标格式无法识别，ie11以下(以及同时期旧版本浏览器)可能存在 

未知原因导致woff字体文件缺失  这个建议电脑端f12模拟手机看下报错内容

**Comment by Perfume-code** [comment]
我想请问网站的主页在哪个文件里，我没想到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月12日(周日) 下午4:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tai7sy/card-system] 网址打开以后，在商品购买跟菜单查询出现英文弄不掉 (Issue #479)




  
浏览器原因导致图标格式无法识别，ie11以下(以及同时期旧版本浏览器)可能存在 

未知原因导致woff字体文件缺失  这个建议电脑端f12模拟手机看下报错内容

**Comment by imPrk0** [comment]
该问题为无法正常渲染字体图标所致，加载文件失败或浏览器无法加载等，已收录至 “常见问题”
该 issues 因年代久远，将被关闭，如有问题请重新发起。
