### ISSUE TITLE
好像没有像留言一样的东西？

### ISSUE THREAD

**Issue by ChenSee** [Tai7sy/card-system#48]
有个需求我是要手动发货的，但是要留言一些信息给我。

**Comment by Tai7sy** [comment]
初衷是自动发卡平台, 所以没有加入手动发货这一类提交发货信息的内容
目前来说, 可以考虑让用户把信息写在联系方式里面

**Comment by ChenSee** [comment]
哦哦 大大有时间可以在后台加个开关  开启留言模式这样。vue没有源代码改不动。。😄

**Comment by Tai7sy** [comment]
下个版本有自定义主题, 带普通JQuery实现的模板, 目前还在开发中

**Comment by ChenSee** [comment]
嗯嗯 坐等大大新版本。。
