### ISSUE TITLE
date 与给定的格式 Y-m-d 不一致

### ISSUE THREAD

**Issue by dylanbai8** [Tai7sy/card-system#481]
![image](https://user-images.githubusercontent.com/26950227/144742915-75d0b08c-5a9f-4070-9b7e-e186d9e927a8.png)

**Comment by Tai7sy** [comment]
直接在日期里面选择，不要手动输入时间试试？

**Comment by dylanbai8** [comment]
> 直接在日期里面选择，不要手动输入时间试试？

![image](https://user-images.githubusercontent.com/26950227/144821271-da9504d6-5b07-4203-b097-bd0054413e5d.png)

选择和手动输入都不行，如上图 好像是获取不到“年”的值。

**Comment by Tai7sy** [comment]
是什么浏览器？

**Comment by dylanbai8** [comment]
> 是什么浏览器？

电脑用的chrome，手机上也尝试了一下使用的是edge和pure。同样的报错 问题复现

**Comment by Tai7sy** [comment]
重新新环境搭建试了下并没有这个问题，这个应该是日期格式化出错，比较玄学，你本地时区是修改过吗？

**Comment by dylanbai8** [comment]
时区没动过。腾讯云北京 宝塔 CentOS 8.4.2105 x86_64(Py3.7.8 Nginx  PHP7.2

![image](https://user-images.githubusercontent.com/26950227/145707185-613c31e0-5cee-4e5b-8105-ae91d485b338.png)

**Comment by dylanbai8** [comment]
要是服务器环境问题我就懒得处理了，反正不影响使用，只是单纯过来反馈一下 表达对此项目的感谢。如有需要 我可以继续协助排查问题

**Comment by dylanbai8** [comment]
测试搭建了另一台腾讯服务器，也是这个报错。腾讯的锅，？ :(

![image](https://user-images.githubusercontent.com/26950227/145707368-691b5f64-9125-425b-b574-35a8948d88c1.png)

**Comment by Tai7sy** [comment]
这个是本地浏览器js计算的时间格式，和服务器无关
