### ISSUE TITLE
coinpayments这个渠道没有回调 

### ISSUE THREAD

**Issue by Nisekoi5** [Tai7sy/card-system#483]
程序版本3.14。可以成功创建订单并付款。商户后台也成功收到资金了。
但是网站上仍显示为未支付，查看NGINX日志也没有回调请求。站点设置里的API地址是设置好了的。其他的支付渠道可以正常回调。
是我还有哪里遗漏了吗

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-gateway/blob/fed335367ff51e57cab4bbe6655948a94a7c088f/Pay/CoinPayments/Api.php#L6

支持回调，可以查看是否api地址正常设置

**Comment by Nisekoi5** [comment]
> https://github.com/Tai7sy/card-gateway/blob/fed335367ff51e57cab4bbe6655948a94a7c088f/Pay/CoinPayments/Api.php#L6
> 
> 支持回调，可以查看是否api地址正常设置


SYS_URL_API 这里填的和网站地址是一样的。最后看nginx日志里面 没有来自其他服务器的向SYS_URL_API/pay/notify/22这个URL的请求(我还有其他的子渠道，是可以回调到SYS_URL/pay/return/{渠道ID}的)

在下单完毕之后的付款页面点击"返回商家页面"  回到的 SYS_URL/pay/return/22 这个地址上提示订单正在处理中。网站没有防火墙 
![image](https://user-images.githubusercontent.com/49276902/145663912-086639b1-ac7f-426e-8813-4ccae131eada.png)
![image](https://user-images.githubusercontent.com/49276902/145663869-2bf1c1bc-fff2-499d-b957-8acf67b95276.png)

**Comment by Tai7sy** [comment]
这里的回调用的是ipn_url
https://github.com/Tai7sy/card-gateway/blob/fed335367ff51e57cab4bbe6655948a94a7c088f/Pay/CoinPayments/Api.php#L68

我记得后台好像有相关设置检查一下？

**Comment by Nisekoi5** [comment]
> 这里的回调用的是ipn_url https://github.com/Tai7sy/card-gateway/blob/fed335367ff51e57cab4bbe6655948a94a7c088f/Pay/CoinPayments/Api.php#L68
> 
> 后台有设置ipn_url的地方，自己填一下


感谢，似乎解决了。
不过和这个IPN URL设置好像无关，我无论这个IPN URL设置成其他任何设置或者是留空。创建订单时浏览器发送的那个post的参数似乎都没变
![image](https://user-images.githubusercontent.com/49276902/145664402-3f505003-b219-4ff4-b783-9d867dbb47d6.png)
![2021-12-11 12-52-33](https://user-images.githubusercontent.com/49276902/145664373-9663e2c4-f310-4f40-a5bd-ece98c6a5d1f.jpg)

似乎是因为我把api秘钥当做ipn秘钥填进去的原因。但是没想到这里设置错了直接连回调都不回调了……
修改后我反复测试了4次。均收到了请求。
206.71.x.x - - - [11/Dec/2021:13:29:14 +0800]"POST /pay/notify/22 HTTP/1.0" 200 6 "-" "CoinPayments.net IPN Generator"

还是有个小问题就是付款后返回商家的按钮好像不能直接弹出卡密。点击后会以以get方式回到 domian.com/pay/return/22 提示订单 "支付验证失败，您可以稍后查看支付状态" 要手动查询订单才能得到卡密

![image](https://user-images.githubusercontent.com/49276902/145665259-db98446f-d088-439e-8b3a-3258025e0739.png)

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-gateway/blob/master/Pay/CoinPayments/Api.php

修改了一下增加了返回页面的订单状态校验， 可以替换文件试试

**Comment by Nisekoi5** [comment]
> https://github.com/Tai7sy/card-gateway/blob/master/Pay/CoinPayments/Api.php
> 
> 修改了一下增加了返回页面的订单状态校验， 可以替换文件试试

可以成功返回了。感谢大佬

不过还是想吐槽下这个网站,回调在他们网站上显示付款成功后过了3分钟才来，此时如果点击返回商店。仍会显示订单验证失败，导致体验略差。 
![im1](https://user-images.githubusercontent.com/49276902/145668089-7d878a5f-fa99-4e28-ae13-34d436d943c6.jpg)

**Comment by Tai7sy** [comment]
目前数字货币相关的回调确定慢，这个没办法了，只能等那边通知才可以确认支付成功

**Comment by zgxtao** [comment]
请问下，配置coinpayment遇到参数设置的问题，应该怎么填写
1.子渠道里面怎么配置
![image](https://github.com/Tai7sy/card-system/assets/49793383/73b60c38-69e8-4706-b897-4e06d1660036)
2.前台支付这里怎么配置
![image](https://github.com/Tai7sy/card-system/assets/49793383/ec2f0d27-7168-4a7e-bd3d-7eaab3a8e860)
