### ISSUE TITLE
关于v免签不显示支付宝付款二维码

### ISSUE THREAD

**Issue by WilliamFWJ** [Tai7sy/card-system#484]
风铃大佬你好
我是安装你的GitHub里面装的这个大佬的v免签 
https://github.com/dreamncn/VPay

已经安装说明配置好，v免签内置的商场测试，微信支付宝均可正常弹出二维码并且支付回调

然后我配置到风铃发卡，微信可以正常弹出二维码并且回调，但是支付宝无法弹出二维码，
附图
https://s3.bmp.ovh/imgs/2021/12/9a806354f5a274c1.png

然后我宝塔上装了两个风铃发卡，另一个均是这种情况微信可用，支付宝无法显示二维码
不知道是不是文件夹权限没设置好还是哪里没做对

还望风铃大佬指导一二，如有打扰，实在是不好意思，实在抱歉

**Comment by WilliamFWJ** [comment]
https://s3.bmp.ovh/imgs/2021/12/6237988ee368df2e.png
补充一下，这是微信，支付宝v免签下生成的链接
微信很快加载出来
支付宝加载了一会，然后就没有显示二维码了

**Comment by Tai7sy** [comment]
支付宝页面f12看看又有有报错内容

**Comment by Tai7sy** [comment]
支付宝页面f12看看，有没有报错内容

**Comment by WilliamFWJ** [comment]
实在感谢风铃大佬百忙中抽时间回答小弟的问题，实在是打扰到风铃大佬休息了
这是支付宝异常F12
https://s3.bmp.ovh/imgs/2021/12/88e7d75548c62e44.png

这是微信正常F12
https://s3.bmp.ovh/imgs/2021/12/95576b377fe3f147.png

**Comment by Tai7sy** [comment]
提示的内容是二维码太长了导致，支付宝这个你可能vpay后台配置的二维码有点问题

**Comment by WilliamFWJ** [comment]
风铃大佬晚上好
我在网上找到相关的贴，这个二维码过长，我应该修改风铃发卡还是v免签的相关配置？

https://blog.csdn.net/Nicker_/article/details/113336759
https://www.xenice.com/article/fn96oil1a1
（附上我找到的一些文章）

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/blob/6469c58ee7ed4d4eec7645b4dab7faefebb9cbf2/resources/views/pay/vpay_alipay.blade.php#L115

修改这里即可，这个支付宝当时测试的时候没遇到问题啊，怎么会突然边长呢。。。

**Comment by WilliamFWJ** [comment]
风铃大佬下午好，实在抱歉一直打扰您，我好像发现了具体是什么原因导致的
v免签里面有一个这个 支付宝UID（可以免输入金额）
如果不填写UID，就生成我V免签上传的通用码（没有金额），这种用户输入正确的金额的话，可以成功跳转
但是我还是希望保留这个UID（免输入金额功能）
具体如下图
https://s3.bmp.ovh/imgs/2021/12/7d1032d987a80e04.png

然后我按照您指导的修改后，如下图
https://s3.bmp.ovh/imgs/2021/12/d6860e6c84e13575.png

现在的情况是，支付宝二维码已经可以弹出，但是似乎二维码内容出错了
手机支付宝扫码显示是这个
https://s3.bmp.ovh/imgs/2021/12/c7273ecefe5be2dc.jpg

然后现在网页F12的报错如下图
https://s3.bmp.ovh/imgs/2021/12/3bd1da8218ce7c30.png

**Comment by Tai7sy** [comment]
那应该是这个设置uid的问题，之前写这个v免签驱动没测试到这个功能我去试试

**Comment by WilliamFWJ** [comment]
好的好的，再次感谢大佬抽空解答小弟的疑问，致上万分敬意与感谢

**Comment by Tai7sy** [comment]
3.15 已经修复, V免签设置了UID之后返回数据自己加了一遍 urlencode 的bug导致
https://github.com/dreamncn/VPay/blob/5d31cc1f55ee5beb4e0498a9e2a4a6db05ee6b19/protected/model/Order.php#L543
