### ISSUE TITLE
建议增加 首页停留超时提醒

### ISSUE THREAD

**Issue by dylanbai8** [Tai7sy/card-system#486]
访客在首页停留过久再下单 会出现显示库存和实际库存一致的问题。

如客户端显示有库存，而在客户首页停留期间实际库存已清零，那么下单时就会报错。

建议：访客首页停留超过一定时间（比如10分钟），当客户填写信息或提交订单时 提醒客户先刷新首页再下单。

**Comment by tohkahznu** [comment]
建议作者添加一个拍下减库存

**Comment by BiliPrk** [comment]
这位小伙伴~ 你好呀~

目前并不能通过 Ajax 请求后端 API 去获取最新的数据。
所以你可以通过使用 JavaScript 计时器去间隔一段时间自动刷新或是提醒用户刷新。

[AD] 派星卡自动发卡平台：https://www.paixingka.com/
