### ISSUE TITLE
网站搭建完成后出现错误500并显示“未知错误，请检查日志"

### ISSUE THREAD

**Issue by WangLing0310** [Tai7sy/card-system#488]
![image](https://user-images.githubusercontent.com/96640500/147376301-e0e00dae-3254-469a-b71b-d195a3c08a75.png)
日志文件↓
[card_fpm-fcgi-2021-12-26.log](https://github.com/Tai7sy/card-system/files/7776027/card_fpm-fcgi-2021-12-26.log)

**Comment by lzkgbld** [comment]
你似乎是本地数据库出现问题了，建议你把logo日志删了，然后重新访问生成一个干净点logo日志方便分析...

**Comment by WangLing0310** [comment]
> 你似乎是本地数据库出现问题了，建议你把logo日志删了，然后重新访问生成一个干净点logo日志方便分析...

这是最新的日志
![image](https://user-images.githubusercontent.com/96640500/149087821-7fc5b7b7-1a3f-4898-865f-48fa90ed9416.png)
[card_fpm-fcgi-2022-01-12.log](https://github.com/Tai7sy/card-system/files/7852737/card_fpm-fcgi-2022-01-12.log)

**Comment by Tai7sy** [comment]
数据库env文件没配置或者没生效导致，连不上数据库提示错误

**Comment by WangLing0310** [comment]
> 数据库env文件没配置或者没生效导致，连不上数据库提示错误

![image](https://user-images.githubusercontent.com/96640500/149126174-1c46b8f7-050a-4de4-85d2-d057beb0d6d8.png)
已按照教程方法配置

**Comment by Tai7sy** [comment]
你的app_key为什么是空的

**Comment by WangLing0310** [comment]
那个不是无需修改吗？

**Comment by Tai7sy** [comment]
安装教程有一步中会生成并写入一个key

**Comment by WangLing0310** [comment]
好的，我重新按照教程安装一遍

**Comment by WangLing0310** [comment]
![image](https://user-images.githubusercontent.com/96640500/149128667-6ad865f7-fae9-4a64-a102-88bdc045296c.png)
在构建数据库时出现报错

**Comment by Tai7sy** [comment]
命令行php版本不对

**Comment by lzkgbld** [comment]
如果使用宝塔，请注意函数报错，自行去宝塔后台PHP删除被禁止的函数即可。

**Comment by WangLing0310** [comment]
卡网已成功搭建，感谢！
![image](https://user-images.githubusercontent.com/96640500/149255501-d4937d21-26c4-40e8-a491-ed87394b0e40.png)

**Comment by chuanyue666** [comment]
兄弟你怎么整好的

**Comment by lzkgbld** [comment]
> 兄弟你怎么整好的

自行查看文档和本档案问题处理经过，相信你也能解决。
