### ISSUE TITLE
验证码验证失败

### ISSUE THREAD

**Issue by lzkgbld** [Tai7sy/card-system#489]
开启普通验证码的店铺验证码，下面的下单和查询都开了，导致下单会出现验证码验证失败。
`Request failed with status code 500`
关闭验证码后，尝试调用Pay Beaver支付会出现获取付款信息超时, 请刷新重试。
已确定清除过缓存。

**Comment by Tai7sy** [comment]
可以检查下日志文件有没有错误内容

**Comment by lzkgbld** [comment]
> 可以检查下日志文件有没有错误的内容

您好，请问一下是查看哪里的日志文件，我并没有学过PHP，感谢回复。

**Comment by Tai7sy** [comment]
网站后台-关于里面

日志可能比较多，可以先全部删掉，触发一次错误，在看日志内容是什么

**Comment by lzkgbld** [comment]
您好，第二天起来发现网站出现跟[该帖子一样的情况](https://github.com/Tai7sy/card-system/issues/488)

**Comment by lzkgbld** [comment]
> 您好，第二天起来发现网站出现跟[该帖子一样的情况](https://github.com/Tai7sy/card-system/issues/488)

查明该原因，发现是因为目录权限不够，不知道为什么最新创建的目录结构权限是root，并不是www，重新手动配置一下目录权限即可！

**Comment by lzkgbld** [comment]
> 网站后台-关于里面
> 
> 日志可能比较多，可以先全部删掉，触发一次错误，在看日志内容是什么

我把日志删除了，然后触发了支付，报错如下：
`local.ERROR: Pay.PayBeaver.goPay.order, request failed:   `

**Comment by Tai7sy** [comment]
连不上支付用的服务器接口导致，
建议手动复制网址在服务器看看能不能打开

**Comment by lzkgbld** [comment]
> 连不上支付用的服务器接口导致， 建议手动复制网址在服务器看看能不能打开

服务器确定能ping通api.paybeaver.com的地址，请问作者对接这家接口是哪个地址？

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-gateway/blob/2f16286dcb93fd6ba061e5fd7ce38632b617d7b3/Pay/PayBeaver/Api.php#L40

访问一下试试

**Comment by lzkgbld** [comment]
> https://github.com/Tai7sy/card-gateway/blob/2f16286dcb93fd6ba061e5fd7ce38632b617d7b3/Pay/PayBeaver/Api.php#L40
> 
> 访问一下试试

您好我尝试ping该地址是通的，我使用python的代码尝试请求也能请求的到，虽然返回的是404..

**Comment by Tai7sy** [comment]
输出日志的地方在下面
https://github.com/Tai7sy/card-gateway/blob/2f16286dcb93fd6ba061e5fd7ce38632b617d7b3/Pay/PayBeaver/Api.php#L64

失败了就会输出，你这个输出是空白明显失败了。原因那就不好找了

**Comment by lzkgbld** [comment]
谢回复，目前也是因为支付文档推荐使用您家的发卡平台，所以才选择使用这个，目前我也有点迷惑，因为他文档并没有写出更详细请求方式，我也想尝试写代码在服务器上运行查询错误原因...

**Comment by Tai7sy** [comment]
大概率是php没装openssl证书？

**Comment by Tai7sy** [comment]
如果你是自己搭建的基础环境如php等可能会有这个情况。可以试试把php文件里面https改成http试试

**Comment by Tai7sy** [comment]
app/library/gateway/Pay/PayBeaver/Api.php

**Comment by lzkgbld** [comment]
> app/library/gateway/Pay/PayBeaver/Api.php

感谢您的答复，我删除了https换成了http，然后支付接口调用成功。
