### ISSUE TITLE
支付宝当面付支付完毕后关闭页面显示未支付

### ISSUE THREAD

**Issue by NBY** [Tai7sy/card-system#49]
大佬，我在使用支付宝当面付的接口时，如果扫码完毕后关闭了窗口，即便付款完毕，订单还是显示未支付，这种问题有办法解决么？

**Comment by Tai7sy** [comment]
当面付是有异步通知的, 请检查你的日志

**Comment by NBY** [comment]
目前我加了一台nginx反向代理服务器并配置了ssl，是否需要把异步通知的地址改为http？我之前使用whmcs遇到过同样的问题，然后参考了https://www.hostloc.bid/thread-355010-1-1.htm在nginx配置文件中添加了规则解决了收不到异步通知的问题。请问如何增加针对于当面付接口的nginx规则？

**Comment by Tai7sy** [comment]
已经接入新版本sdk, 目前新版sdk已经支持异步通知与查询
