### ISSUE TITLE
无法发送短信，无法使用验证码

### ISSUE THREAD

**Issue by xiaoyang-yang** [Tai7sy/card-system#491]
问题1：无法给用户发送短信通知了，后台的钱却还在扣除，我记得以前好好的，不知道那一次更新后就不行了
问题2：验证码验证失败，Request failed with status code 500，我把整个大目录都给了777权限也不行

**Comment by lzkgbld** [comment]
建议去查日志，先把老日志文件删了，然后重新请求看看报错是什么...

**Comment by xiaoyang-yang** [comment]
验证码问题已经找到，PHP必须手动安装扩展fileinfo才行
短信的问题，系统后台也没有报错误，钱也扣了，就是收不到短信

**Comment by Tai7sy** [comment]
短信问题已修复

**Comment by xiaoyang-yang** [comment]
另外想咨询一下，如何以下修改才能直接发送卡密信息，而不是链接，十分感谢
http_build_query(array('id' => System::_get('sms_api_id'), 'key' => System::_get('sms_api_key'), 'to' => $this->mobile, 'msg' => config('app.url') . '/pay/result/' . $this->order->order_no))); } }

**Comment by Tai7sy** [comment]
这个接口就是因为很难申请限制严格所以才内置了一个。
目前长度有限制不支持修改， 有需求的可以自己申请接口换掉

**Comment by xiaoyang-yang** [comment]
主要是，有时候客户付款后，关闭了提取卡密的页面，没拿到商品，也不知道发货了，直接投诉，或者直接把短信的内容当成卡密，然后说卡密不对，又是一顿投诉，建议短信内容注明一下是提取地址，谢谢。
