### ISSUE TITLE
希望增加一个用户必须登录才能跳转到购买页面的模式

### ISSUE THREAD

**Issue by xiaoyang-yang** [Tai7sy/card-system#500]
近期网安对发卡的网站进行了大面积封停，应该是爬虫抓到了什么敏感信息导致，所以想看看能不能增加一个简单的首页，用户必须登录才能到卡密购买的页面。

**Comment by BiliPrk** [comment]
这位小伙伴~ 你好呀~

首先，如果让用户也登录才可以购买，这非常的不现实！
毕竟发卡平台不像是淘宝拼多多京东等电商平台，需要购物什么就可以去搜索。
而是通过链接购买后以 “半匿名” 身份去购买，然后拿到卡密。
如果修改成了买家也需要登录才可以购买，那么将会劝退绝大部分用户！！

中国的网络已经越来越管制了，逐渐像北朝鲜的光明网靠近。
我们就算有再完善再麻烦的措施去挽救这一切也无济于事！
不只是 “彩虹自助下单系统” 被大面积墙
发卡本身就属于 “擦边球” 业务，本身就属于被管制范围！

[AD] 派星卡自动发卡平台：https://www.paixingka.com/
