### ISSUE TITLE
搭建过程没报错，但在前台支付的时候出现500错误，已附上日志，求解！

### ISSUE THREAD

**Issue by Moe-siro** [Tai7sy/card-system#502]
[card_fpm-fcgi-2022-02-14.log](https://github.com/Tai7sy/card-system/files/8059626/card_fpm-fcgi-2022-02-14.log)
环境：CentOS 7.9.2009 x86_64(Py3.7.9)
php7.1
mysql5.6
composer2.2.6

**Comment by Tai7sy** [comment]
下载release安装，
或者clone下来仓库需要子模块 card-
