### ISSUE TITLE
MD主题设置背景音乐后不自动播放

### ISSUE THREAD

**Issue by CodePwn2021** [Tai7sy/card-system#506]
设置的值是 https://xxx.xxx.xxx/source-storage/card_site_background_music.mp3（域名已隐去）
起初我以为是缓存的问题，把cdn和本地的缓存都清理了一遍，还是不自动播放。

**Comment by Tai7sy** [comment]
有点问题，js上个版本更新搞坏了，下次修复

**Comment by CodePwn2021** [comment]
谢谢大大的回答，期待修复

**Comment by SmilingCoffins** [comment]
你可以在网站设置，常规设置，客服代码(QQ等)里填上https://music.163.com/#/outchain/2/1873321491/网易云音乐找音乐点击打开[生成外链播放器]
把HTML代码:
<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=1873321491&auto=1&height=66"></iframe>
代码填在客服代码(QQ等就有音乐了

**Comment by CodePwn2021** [comment]
> 

谢谢了，我试试（刚刚不小心按到close

**Comment by SmilingCoffins** [comment]
什么意思

**Comment by SmilingCoffins** [comment]
将国语

**Comment by SmilingCoffins** [comment]
雪花飘落ssc要不要

**Comment by CodePwn2021** [comment]
> 雪花飘落ssc要不要

可以呀，还有别的吗，或者资源整合的网站能不能给一个（

**Comment by SmilingCoffins** [comment]
700627940QQ群临时交流一下

**Comment by CodePwn2021** [comment]
> 700627940QQ群临时交流一下

怎么我看着是个王者荣耀群，是不是输入错了

**Comment by SmilingCoffins** [comment]
临时交流 正确的

**Comment by CodePwn2021** [comment]
> 临时交流 正确的

行吧行吧

**Comment by CodePwn2021** [comment]
> 临时交流 正确的

加了

**Comment by BiliPrk** [comment]
你好呀~ 这位小伙伴~

目前仅后端有记录音乐的直链
前端并不会手动加载音乐

我这里有两个思路，可供参考哦~

因为音乐链接会随着店铺链接一起传到前端 JavaScript 的 config 变量中。这个变量是一个 JSON ，你可以手动格式化下 JSON 确定音乐直链的位置。这里不一定是链接。我们可以使用网易云音乐的播放器也可以上网搜寻创建音乐播放的 JavaScript 代码。

- 方案一、网易云音乐方案
缺点：不支持 VIP 音乐
输入框里只需要输入网易云音乐中的音乐 ID 。如何获取呢？复制一下歌曲的链接，你会得到下面的链接。
`https://music.163.com/song?id=***&userid=***`
其中，GET 参数 id 的值就是音乐 ID。
`<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width="0px" height="0px" src="https://music.163.com/outchain/player?type=2&id={音乐ID}&auto=1&height=0" style="display: none;"></iframe>`
其中，音乐 ID 就是。我们只需要将下列代码添加到网站的客服代码即可！
```
<script type="text/javascript">
/**
 * Name: Play Music
 * Author: Prk
 * Website: https://www.cprk.cc & https://imprk.me
 * Date: 2022-01-25
 * Location: Huazhou Haizhu Guangzhou Guangdong, People's Republic of China
 */
if ( /^\+?[1-9][0-9]*$/.test(config.theme.music) ){
    document.write('<iframe frameborder="no" border="0" marginwidth="0" marginheight="0" width="0px" height="0px" src="https://music.163.com/outchain/player?type=2&id=' + config.theme.music + '&auto=1&height=0" style="display: none;"></iframe>')
}
</script>
 ```

- 方案二、手动设置方案
如果你是个 Web 开发者或是学习过前端 JavaScript 的话那么你肯定能自己就可以写了。当然，就算你不会网络上也有很多的教程可以搜寻！开动脑筋去思考吧~

[AD] 派星卡自动发卡平台：https://www.paixingka.com/
