### ISSUE TITLE
搭建时终端输入任何指令都出错

### ISSUE THREAD

**Issue by xiaobai5165** [Tai7sy/card-system#509]
![QQ截图20220224125857](https://user-images.githubusercontent.com/84277406/155461313-88233a4f-998a-4d01-9089-7fab4659dd5d.png)

**Comment by Tai7sy** [comment]
看不到报错内容

**Comment by xiaobai5165** [comment]
> 看不到报错内容

就是输入命令之后出现这一大堆东西，但是不执行命令
