### ISSUE TITLE
订单记录卡密栏为空

### ISSUE THREAD

**Issue by JieFuHe** [Tai7sy/card-system#513]
有添加卡密的，但是订单列表是空的

**Comment by Tai7sy** [comment]
截图看看

**Comment by JieFuHe** [comment]
![img](https://s3.bmp.ovh/imgs/2022/03/1dd0ac14e84f87aa.png)

**Comment by Tai7sy** [comment]
对应商品的卡号有标记为售出并减少库存吗？

**Comment by JieFuHe** [comment]
有售出并且减少库存

**Comment by Tai7sy** [comment]
那感觉是你数据库有问题，删了东西，
可以进数据库看下cards_order 表里面订单对应的卡密id是否正常

**Comment by JieFuHe** [comment]
> 那感觉是你数据库有问题，删了东西， 可以进数据库看下cards_order 表里面订单对应的卡密id是否正常

没问题啊，查过了，对得上
