### ISSUE TITLE
已经转账了但是显示未支付

### ISSUE THREAD

**Issue by vantork** [Tai7sy/card-system#519]
![Screenshot_2022-03-12-17-03-27-307_com eg android AlipayGphone](https://user-images.githubusercontent.com/101452612/158011902-6cdcf2a6-e3b6-44f1-bcf5-cc915aec9f01.jpg)

**Comment by mikuknightforever** [comment]
同样的问题同样的人
![Uploading Screenshot_2022-03-12-16-50-50-897_com.eg.android.AlipayGphone.jpg…]()
