### ISSUE TITLE
卡密查询页面 一直显示加载中

### ISSUE THREAD

**Issue by whyliuxing** [Tai7sy/card-system#52]
你好。我这边点击卡密查询界面，。不管是浏览器缓存 订单号 还是联系方式 
下面的那个查询按钮都是显示灰色的 加载中 。

**Comment by whyliuxing** [comment]
经过调试，发现是开启了查询界面 验证码功能， 这个验证码功能在开源版本中无法使用吗

**Comment by Tai7sy** [comment]
geetest验证码版本导致的, 目前是2.0版本的sdk, 下个版本统一升级3.0
