### ISSUE TITLE
安装教程走完后网站提示500未知错误

### ISSUE THREAD

**Issue by anzx65** [Tai7sy/card-system#520]
[card_fpm-fcgi-2022-03-13.log](https://github.com/Tai7sy/card-system/files/8239423/card_fpm-fcgi-2022-03-13.log)
按照教程走完一遍后提示500未知错误

**Comment by Tai7sy** [comment]
配置文件没生效，自己检查env文件或者清理缓存

**Comment by anzx65** [comment]
还是这样
