### ISSUE TITLE
当面付下单报错

### ISSUE THREAD

**Issue by Murmire** [Tai7sy/card-system#521]
![image](https://user-images.githubusercontent.com/69282145/158944858-92701426-d3bf-42c4-845a-0680ed7991bd.png)
偶然情况会出现这样，这个页面刷新五六次就正常了
我想知道是什么原因导致的呢

**Comment by Tai7sy** [comment]
可以谷歌搜一下这个原因，大概率服务器问题

**Comment by BiliPrk** [comment]
你好呀~ 这位小伙伴~

Linux 系统请将下列命令输入在服务器终端（SSH）中然后敲回车：

 - 中国大陆服务器
`echo -e "options timeout:1 attempts:1 rotate\nnameserver 223.5.5.5\nnameserver 223.6.6.6" >/etc/resolv.conf;`

 - 香港特区 / 澳门特区 / 国外服务器
`echo -e "options timeout:1 attempts:1 rotate\nnameserver 8.8.8.8\nnameserver 8.8.4.4" >/etc/resolv.conf;`

Windows 系统直接修改网络适配器，IPv4 的配置，DNS 服务器手动指定

 - 中国大陆服务器
主：223.5.5.5
备：223.6.6.6

 - 香港特区 / 澳门特区 / 国外服务器
主：8.8.8.8
备：8.8.4.4

谢谢！

[AD] 派星卡自动发卡平台：https://www.paixingka.com/
