### ISSUE TITLE
易支付下单支付后，提示未知错误，请检查日志  500

### ISSUE THREAD

**Issue by WilliamFWJ** [Tai7sy/card-system#522]
风铃大佬你好，很抱歉打扰您
我看到之前有人提交过这个issues，
然后我吧EPay里面api替换为您修改后的
也就是这个
https://github.com/Tai7sy/card-gateway/commit/5a786aa93d29eac96c745ca8e49db8b3c9b43082

然后好像还是500 ，提示未知错误，请检查日志

（附上日志以及截图，还望大佬可以指点一二，感激不尽）

这是付款后出错的界面
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/35882207/159116298-6166e8bb-1814-441e-ad31-9c89d15aa9f6.png">

这是日志
[card_fpm-fcgi-2022-03-19 (1).log](https://github.com/Tai7sy/card-system/files/8308934/card_fpm-fcgi-2022-03-19.1.log)

这是易支付后台的错误提示
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/35882207/159116522-3690a19b-d170-46fa-a489-f4a87d3d02c6.png">

**Comment by WilliamFWJ** [comment]
附上完成一次支付的报错日志
(还望风铃大佬可以指导一二)

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/35882207/159120003-bd747ddd-edef-49e1-b189-a42841ce1209.png">

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/35882207/159120019-3fae7c68-6372-47be-a1ca-365d0aff936b.png">

<img width="1605" alt="image" src="https://user-images.githubusercontent.com/35882207/159120032-d50f3aa0-ba5a-4054-a77d-1035589d74a5.png">

**Comment by WilliamFWJ** [comment]
风铃大佬，会不会是我配置不正确，epay的api文件
我只修改了这两个地方为我用的易支付
发卡后台也配置好了前台和后台
可以正确调出二维码，但是付完款是500，提示未知错误，请检查日志
![image](https://user-images.githubusercontent.com/35882207/159134391-7451ba0d-5b35-4cee-a10f-d39e61038462.png)
![image](https://user-images.githubusercontent.com/35882207/159134406-4c52975b-cd80-4c22-bdbb-fb386f659a3e.png)

**Comment by Tai7sy** [comment]
你这个应该不是标准易支付接口，
pid变成了app_id
type变成了method

**Comment by Tai7sy** [comment]
另外这个地方不需要修改，后台json里面加一个gateway即可
