### ISSUE TITLE
请问 更换新的域名网址

### ISSUE THREAD

**Issue by Murmire** [Tai7sy/card-system#523]
请问 更换新的域名网址，老域名网址的文件跟数据怎么 原封不动转换到新的域名网址上？

**Comment by Tai7sy** [comment]
如果只是改个域名，后台直接修改即可
换服务器的话自己谷歌搜怎么迁移网站吧

**Comment by Murmire** [comment]
好的 只修改wwwroot文件下的域名文件名嘛？
数据库这些要去动吗？

**Comment by Tai7sy** [comment]
你可能用的宝塔面板，域名和文件夹名字一点关系都没有，不需要改，加一个域名绑定即可

宝塔面板网站目录文件夹和第一次创建时候填写域名一样，和真正绑定的域名没关系

**Comment by Murmire** [comment]
![image](https://user-images.githubusercontent.com/69282145/159157741-e0e33b75-344e-4b06-9d19-97deb3daabef.png)
哈 这么简单吗 我一直以为要动很多东西
直接在上图的地方添加新的域名 是吗😂

**Comment by Tai7sy** [comment]
是，然后发卡网站系统设置，改下新的域名即可
