### ISSUE TITLE
关于手机易支付，支付后跳转的一点小疑问

### ISSUE THREAD

**Issue by WilliamFWJ** [Tai7sy/card-system#529]
很抱歉因为这一点小问题打扰风铃大佬
我知道电脑易支付的逻辑是
1.风铃发卡点击付款后

2.新建标签页跳转易支付付款，

3.付款后跳转到订单已支付的界面，如下图
![image](https://user-images.githubusercontent.com/35882207/161386630-672176d8-d271-4328-8aa0-1801591afad9.png)

------------------------------------------------------------------------------------------------------------------------

我现在手机易支付的逻辑是
1.风铃发卡点击付款后
（会直接调起支付宝app付款）
（用户支付完手动返回风铃发卡，不会显示订单已支付的卡密详情，只会显示下图）
（当然，手动查询订单也是显示已支付，没问题的）
![46ae3753d0115b75fa458364ab744bd](https://user-images.githubusercontent.com/35882207/161386859-0ccb1c57-8326-4185-af67-70c9749e1c84.jpg)

不知道我理解的对不对，易支付因为付款后，因为没有新建窗口/标签页，所以不会弹出卡密详情
（还是说小弟我可能对接的时候，哪里出错了，麻烦大佬可以指导一二，）
------------------------------------------------------------------------------------------------------------------------

ps：我看一些其他网站对接易支付的时候，如whmcs（如下图），是先跳转cashier.php，而不是submit.php
不知道风铃发卡是否支持这种cashier.php收银台界面

![image](https://user-images.githubusercontent.com/35882207/161387267-650bd4a5-35a8-43e2-8039-01b0558ae110.png)

**Comment by Tai7sy** [comment]
有新建标签页，但是由于拉起支付宝app进行支付，当前页面被浏览器自动关闭（部分浏览器行为不一致，测试chrome会关闭），导致支付完返回的是支付下单页面

**Comment by Tai7sy** [comment]
这个cashier应该不是所有易支付都支持，比较难兼容处理

**Comment by WilliamFWJ** [comment]
感谢风铃大佬百忙中抽时间耐心解答，小弟临表涕零，感激不尽
那chrome自动关闭这个有无解决方案，还是说chorme拉起支付宝的逻辑是这样，暂时无解

ps，还有一个小疑问，下图这个“查看卡密”字眼能否自定义，比如我想改为“点击查看账号密码”
（我刚刚直接在GitHub这个项目搜索查看卡密这几个字眼无结果）
![image](https://user-images.githubusercontent.com/35882207/161388738-1b9b9cb2-c0b1-43e9-88d9-d73eb9a631df.png)

**Comment by Tai7sy** [comment]
这个跳转导致关闭的问题，想了下应该可以解决（新建一个窗口唤起支付宝等app/通过手动点击按钮唤起app），
明天我更新一个版本试一试

**Comment by WilliamFWJ** [comment]
风铃大佬你好
刚刚测试了一下，好像是只有苹果的设备（这边用iPhone和iPad测试）会出现跳转导致关闭  （修改保存后已重启vps）
安卓设备的chorme删不删都不会出现跳转导致关闭

而且好像我删掉了那一行，苹果的chorme 同样会出现跳转导致关闭

ps：会不会是这里应该改为iOS
![image](https://user-images.githubusercontent.com/35882207/161392451-4f990821-64b7-460c-b542-55ede44d12f7.png)

**Comment by Tai7sy** [comment]
不自动跳转app，需要手动点按钮说明修改生效。

**Comment by WilliamFWJ** [comment]
ps，其实风铃大佬有没有考虑过建个电报群 telegram
这样用风铃大佬您面板的用户都可以交流，
遇到不懂的群友之间自己解决，
大佬有木有考虑过
