### ISSUE TITLE
用支付宝电脑版支付有几率付款后显示未支付

### ISSUE THREAD

**Issue by whyliuxing** [Tai7sy/card-system#53]
如题，每天会发生一两起。用户支付完成后未发卡。查询订单发现实际已经支付了。
这种如何解决？没有异步的回调检查之类的吗，目前的代码都被混淆了，有点难调试。

**Comment by Tai7sy** [comment]
这个有可能是支付宝的异步通知的时候你的网站无响应导致, 支付宝会自动每隔一段时间再次进行通知已支付未通知订单, 不需要手动检查

**Comment by stuwgq** [comment]
老哥能否留个联系方式我加你求助一下，支付这块我不会接，有偿

**Comment by Tai7sy** [comment]
已经介入新版本sdk, 目前新版sdk已经支持异步通知与查询
