### ISSUE TITLE
期待更新内容

### ISSUE THREAD

**Issue by lolhfzs** [Tai7sy/card-system#531]
1.期待更新 自定义订单备注的功能或者用户备注功能，又或者购买的商品昵称为备注。
原因：在支付宝上的订单备注等不会出现订单号+随机的备注出现。避免官方认为刷单或诈骗的感觉。很容易被冻结资金。这样收到的款要在4个工作日后才解冻。我这个月已经遇到了两次了。

2.付款页的bug
原因：二维码在IE浏览器情况下不出现二维码图片，期待修复

感谢您的无私奉献，最后想问问专业版如何联系。

**Comment by Tai7sy** [comment]
第一个需求没看懂，是指的可以设置用户下单支付宝那边显示的商品名吗

**Comment by lolhfzs** [comment]
我的意思是指，当前购买的商品名是什么。支付宝所备注的就是什么。这样多规范。

目前我们备注是一个订单号。那么官方很容易就觉得是套现或者刷单。

**Comment by lolhfzs** [comment]
正常的支付宝付款是：
商品说明：收钱码收款        
付款备注：商品名称

而我们的发卡网支付宝当面付付款后，商品说明：是个订单号   付款备注没有的。 是很容易涉嫌刷单或诈骗！易被冻结资金。并且我这边还特地联系了支付宝客服。客服说的接入的商品说明和备注不规范导致的。

**Comment by Tai7sy** [comment]
我支付宝找遍了订单也没找到一个带备注的，付款备注不是你手动填的吗？

**Comment by byif** [comment]
> 我支付宝找遍了订单也没找到一个带备注的，付款备注不是你手动填的吗？
他说的那个备注应该是 商品说明 ，目前商品说明是订单号，建议改为具体的商品名称。
