### ISSUE TITLE
请问支持卡密核销功能吗

### ISSUE THREAD

**Issue by linwenming** [Tai7sy/card-system#532]
3.15发卡系统已经成功安装了，里面功能都体验了下，基本满足需求。除了个别小bug，真的非常棒！！

由于我的需求需要一个卡核销功能，找了下，在系统后台或者api介绍里面都没有。冒昧问一下，请问这套系统支持核销功能吗？
如果开源版本没有的话，那么商业版本有吗

感谢您的无私奉献，最后想问问专业版如何联系。

**Comment by Tai7sy** [comment]
核销应该是要对接你的目标系统吧，这个每个人卡密用法不一样。
或者你说的是手动核销功能？
