### ISSUE TITLE
为啥会这样

### ISSUE THREAD

**Issue by xuancaohua** [Tai7sy/card-system#537]
![FM$O{S}0EYKM0Z0B~9$7_}U](https://user-images.githubusercontent.com/104002067/166613566-bfd0b2a8-cd5e-480a-a45b-2d65d5da9972.png)

**Comment by SISUBEN** [comment]
宝塔禁用了一些函数，重新启用即可

**Comment by BiliPrk** [comment]
你好呀，这位小伙伴~

请确定正确配置了环境变量！
.env 文件，不是 .env.example

```
DB_HOST=这里写IP连接地址，通常是 localhost / 127.0.0.1
DB_PORT=这里写数据库连接端口，默认是 3306
DB_DATABASE=数据库名
DB_USERNAME=数据库用户名
DB_PASSWORD=用户名的密码
```

**宝塔面板在创建数据库的时候未必会按照你填写的内容创建，请确保大小写和字符填写正确**

确保 MySQL 的状态是正常的。

出现这个报错是数据库连接出现的问题。，

如果你需要技术支持可以随时联系我哦~

Telegram: @BiliPrk

[AD] 派星卡自动发卡平台：https://www.paixingka.com/

**Comment by SISUBEN** [comment]
> 你好呀，这位小伙伴~
> 
> 请确定正确配置了环境变量！ .env 文件，不是 .env.example
> 
> ```
> DB_HOST=这里写IP连接地址，通常是 localhost / 127.0.0.1
> DB_PORT=这里写数据库连接端口，默认是 3306
> DB_DATABASE=数据库名
> DB_USERNAME=数据库用户名
> DB_PASSWORD=用户名的密码
> ```
> 
> **宝塔面板在创建数据库的时候未必会按照你填写的内容创建，请确保大小写和字符填写正确**
> 
> 确保 MySQL 的状态是正常的。
> 
> 出现这个报错是数据库连接出现的问题。，
> 
> 如果你需要技术支持可以随时联系我哦~
> 
> Telegram: @BiliPrk
> 
> [AD] 派星卡自动发卡平台：https://www.paixingka.com/

大佬能看看我的issue吗QAQ挺急的，帮别人搭建的

**Comment by Tai7sy** [comment]
数据库密码不对，自己检查

**Comment by kfbnc** [comment]
我也遇到过这个问题，解决办法：
1.检查.env文件和数据库用户名、密码
2.尝试重启服务器
3.如果还是不行，可以进入/config/database.php 找到第46-48行，把数据库名、用户名、密码修改成你的数据库信息（不推荐使用，但是确实解决了我的问题）
