### ISSUE TITLE
未知错误：请检查日志

### ISSUE THREAD

**Issue by SISUBEN** [Tai7sy/card-system#539]
日志：[2022-05-10 09:16:33] production.ERROR: Type error: Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key, null given, called in /www/wwwroot/kw.tbsursuit.cn/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 2 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given, called in /www/wwwroot/kw.tbsursuit.cn/vendor/lcobucci/jwt/src/Signer/BaseSigner.php on line 2 at /www/wwwroot/kw.tbsursuit.cn/vendor/lcobucci/jwt/src/Signer/Hmac.php:2)

![image](https://user-images.githubusercontent.com/100661067/167523396-e767a201-5f20-4470-bec0-1fef4356e061.png)

.env文件：

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=kw
DB_USERNAME=kw
DB_PASSWORD=xwd6k********

# 下面配置无需修改
APP_ENV=local
APP_KEY=base64:0C/I4qLFR7nY6ZPm7ppGJExGGG82JN06kKCoMcnJxkc=
APP_DEBUG=false
APP_LOG_LEVEL=error
APP_LOG=daily

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=array
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

**Comment by SISUBEN** [comment]
下面是我的log
[card_fpm-fcgi-2022-05-10.log](https://github.com/Tai7sy/card-system/files/8656457/card_fpm-fcgi-2022-05-10.log)
:

**Comment by Tai7sy** [comment]
大概率.env文件不对, 自己检查一下重新设置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tai7sy/card-system"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 上午9:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Tai7sy/card-system] 未知错误：请检查日志 (Issue #539)





 
下面是我的log
 card_fpm-fcgi-2022-05-10.log
 :

**Comment by SISUBEN** [comment]
> 大概率.env文件不对, 自己检查一下重新设置
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tai7sy/card-system" ***@***.***&gt;; 发送时间:&nbsp;2022年5月10日(星期二) 上午9:54 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [Tai7sy/card-system] 未知错误：请检查日志 (Issue #539) 下面是我的log card_fpm-fcgi-2022-05-10.log : — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

看过了，应该是对的，密码也是对的
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=kw
DB_USERNAME=kw
DB_PASSWORD=xwd6k7taAkP8emsh


# 下面配置无需修改
APP_ENV=local
APP_KEY=base64:0C/I4qLFR7nY6ZPm7ppGJExGGG82JN06kKCoMcnJxkc=
APP_DEBUG=false
APP_LOG_LEVEL=error
APP_LOG=daily

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=array
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

**Comment by SISUBEN** [comment]
![image](https://user-images.githubusercontent.com/100661067/167544950-edda8086-286c-4e64-a27e-fcd63eab390a.png)
风铃大佬，我看到这里DB_SOCKET是空的，是不是要配置.sock文件啊

**Comment by BiliPrk** [comment]
这位小伙伴~ 你好呀~

首先，在搭建且无需特别修改需求的时候请不要修改其他文件。因为在修改其他文件的时候往往反而会造成坏的影响！
**在宝塔面板中，如果按照[教程](https://github.com/Tai7sy/card-system/wiki/%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B---BT%E9%9D%A2%E6%9D%BF)去做的话通常不会遇到问题！**
我看到你有修改 “database.php”，你貌似是使用过 ThinkPHP 开发的一些程序需要手动修改数据库信息的思路去操作。但是不需要在这里进行修改！应当修改网站目录下的 .env 文件！

因为个人原因，暂时无法观看日志。请先根据我下面说的进行自查，自查后如果依旧无果请再继续回复。

1、运行环境，PHP 7.3，MySQL 5.7；不仅仅是要检查版本，同时也要检查运行状态等。是否是运行状态都要去检查一次。
2、网站配置，是否有关闭 open_basedir（防跨站攻击），以及重写规则（伪静态）。
Nginx 服务器配置规则，宝塔请直接复制到伪静态处粘贴保存：
```
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```
3、环境变量，**这里一定要重点检查！很多人都载在这里！**

打开 env 文件，确保里面输入的内容与宝塔后台一致！
一定要看清大小写以及是否有多余空格！
宝塔在部分情况会自动将数据库名转换为小写
且数据库名、用户名、密码会与当时设定的出现一些差异！请务必核对是否正确！
DB_DATABASE 是数据库名
DB_USERNAME 是用户名
DB_PASSWORD 是密码

完成后保存。再使用下面命令构建数据库：
`php artisan key:generate && php artisan migrate:fresh --seed && php artisan cache:clear`

完成后进入后台，如果依旧出现这个问题

① 请到浏览器【开发者工具】-【网络】-【Fetch/XHR】中截图
② 请到后台目录 storage 中拿日志并提交进来

当我有时间后我会来看 或者风铃会回复解决

通常都是低级错误，几乎重装都可以解决！

**请一定要看清安装文档！**

如有问题，也可以通过 Telegram 联系我~
GitHub & Telegram : @BiliPrk 
Twitter: @bili_prk

[AD] 派星卡自动发卡平台：https://www.paixingka.com/

**Comment by BiliPrk** [comment]
**REPLENISH!!** I THINK, AT THE MOMENT YOUR WEBSITE SHOULD REDEPLOY THE CODE!

**Comment by SISUBEN** [comment]
好的，谢谢，我去尝试一下











SISUBENY_comprehensive&nbsp;the&nbsp;x-coordinate&nbsp;is&nbsp;356.6542546,654.56486,684.6458

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月11日(周三) 晚上7:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tai7sy/card-system] 未知错误：请检查日志 (Issue #539)




 
这位小伙伴~ 你好呀~
 
首先，在搭建且无需特别修改需求的时候请不要修改其他文件。因为在修改其他文件的时候往往反而会造成坏的影响！
 在宝塔面板中，如果按照教程去做的话通常不会遇到问题！
 我看到你有修改 “database.php”，你貌似是使用过 ThinkPHP 开发的一些程序需要手动修改数据库信息的思路去操作。但是不需要在这里进行修改！应当修改网站目录下的 .env 文件！
 
因为个人原因，暂时无法观看日志。请先根据我下面说的进行自查，自查后如果依旧无果请再继续回复。
 
1、运行环境，PHP 7.3，MySQL 5.7；不仅仅是要检查版本，同时也要检查运行状态等。是否是运行状态都要去检查一次。
 2、网站配置，是否有关闭 open_basedir（防跨站攻击），以及重写规则（伪静态）。
 Nginx 服务器配置规则，宝塔请直接复制到伪静态处粘贴保存：
 location / {     try_files $uri $uri/ /index.php?$query_string; }  
3、环境变量，这里一定要重点检查！很多人都载在这里！
 
打开 env 文件，确保里面输入的内容与宝塔后台一致！
 一定要看清大小写以及是否有多余空格！
 宝塔在部分情况会自动将数据库名转换为小写
 且数据库名、用户名、密码会与当时设定的出现一些差异！请务必核对是否正确！
 DB_DATABASE 是数据库名
 DB_USERNAME 是用户名
 DB_PASSWORD 是密码
 
完成后保存。再使用下面命令构建数据库：
 php artisan key:generate &amp;&amp; php artisan migrate:fresh --seed &amp;&amp; php artisan cache:clear
 
完成后进入后台，如果依旧出现这个问题
 
① 请到浏览器【开发者工具】-【网络】-【Fetch/XHR】中截图
 ② 请到后台目录 storage 中拿日志并提交进来
 
当我有时间后我会来看 或者风铃会回复解决
 
通常都是低级错误，几乎重装都可以解决！
 
请一定要看清安装文档！
 
如有问题，也可以通过 Telegram 联系我~
 GitHub &amp; Telegram : @BiliPrk
 Twitter: @bili_prk
 
[AD] 派星卡自动发卡平台：https://www.paixingka.com/

**Comment by gudaonanfeng** [comment]
一样，一直500错误，尝试过刷新缓存，重新安装，切换php版本都不行，最后修改database.php默认用户名和密码可以进入后台不过功能都不可以使用

**Comment by Tai7sy** [comment]
大概率你.env文件权限不对，检查下整个目录都设置777得了

**Comment by zwc456baby** [comment]
local.ERROR: Uncaught Exception {"exception":"[object] (RuntimeException(code: 0): Missing BC Math or GMP extension
 
 打开网页商品列表提示 未知错误
需要安装 gmp 扩展 sudo apt install php-gmp

**Comment by SISUBEN** [comment]
why? does my environment config hava any problem?











SISUBENY_comprehensive&nbsp;the&nbsp;x-coordinate&nbsp;is&nbsp;356.6542546,654.56486,684.6458

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月11日(周三) 晚上7:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tai7sy/card-system] 未知错误：请检查日志 (Issue #539)




 
REPLENISH!! I THINK, AT THE MOMENT YOUR WEBSITE SHOULD REDEPLOY THE CODE!
