### ISSUE TITLE
最新版这个背景图片挂了，请修复一下，谢谢

### ISSUE THREAD

**Issue by dbrundage1** [Tai7sy/card-system#54]
最新版这个背景图片挂了，原来每天自动换背景图片，现在一片空白了，请修复一下，谢谢

**Comment by Tai7sy** [comment]
手动可以在后台修改背景图，主题更新的时候换了默认bing的，结果不是很稳定。。。。(话说bing今天被墙了？)

你自己可以在后台进行更改

**Comment by stuwgq** [comment]
老哥能否留个联系方式我加你求助一下，支付这块我不会接，有偿

**Comment by Tai7sy** [comment]
内置了部分与主题风格搭配的轮播图片URL, 
将背景URL设置为 "内置1" 即可使用
