### ISSUE TITLE
500 Internal Server Error nginx

### ISSUE THREAD

**Issue by Murmire** [Tai7sy/card-system#545]
500 Internal Server Error
nginx
突然今天就出现这个报错了
什么也没动

**Comment by BiliPrk** [comment]
亲爱的用户，你好：

如果一直在正常的情况下突然出现 500 错误请检查所有的服务是否在运行当中。亦或者可以的话你需要详细介绍下问题，没有日志不知道你的环境无法直接定位到问题并快速得到解决！

谢谢！

Prk
2022 年 06 月 21 日
[AD] 派星卡自动发卡平台 https://www.paixingka.com
