### ISSUE TITLE
查询密码为 123123. 时会500

### ISSUE THREAD

**Issue by dylanbai8** [Tai7sy/card-system#549]
查询密码为 123123. 时会500

## 123123.

别的数字加 .号 没有这个问题，只有 123123 后加 . 才会，奇了怪了

**Comment by BiliPrk** [comment]
你好，因安全起见，当订单查询密码为 `123123.` 时，会提示错误信息 “您输入的查询密码过于简单，请重新输入” 并没有办法直接进行操作。如果出现了 500 错误请查看日志，并检查是否存在低级错误。如果没有存在低级错误建议清空缓存后重试！

[AD] 派星卡自动发卡平台：https://www.paixingka.com/

**Comment by dylanbai8** [comment]
# 不审题就打广告啊？

是七位数，

**Comment by BiliPrk** [comment]
你好，请仔细阅读我的消息。你的密码输入的是 123456. 后面有个点的对吧？那本身也会提示过于简单

[AD] 派星卡：https://www.paixingka.com
