### ISSUE TITLE
查询订单页面有点白，看的不大清楚

### ISSUE THREAD

**Issue by cjiasu** [Tai7sy/card-system#55]
程序整体非常棒 特别是后端  前端手机端太白了 字都看不到😂

**Comment by Tai7sy** [comment]
能否截个图发一下, 看看是否是不同设备字体原因

**Comment by cjiasu** [comment]
https://faka.cjiasu.app/?theme=Material#/record?tab=order_no




C加速官网:https://cjiasu.app

风铃 <notifications@github.com> 于 2019年1月25日周五 下午8:01写道：

**Comment by cjiasu** [comment]
购买商品那个页面也是很白  字都看不到  我把背景黄全黑才好点

风铃 <notifications@github.com> 于 2019年1月25日周五 下午8:01写道：
