### ISSUE TITLE
运行php artisan migrate:fresh --seed提示这些东西（.env已经检查了）（网站主页提示:未知错误，请检查日志)

### ISSUE THREAD

**Issue by 9wijfw** [Tai7sy/card-system#552]
In Connection.php line 2:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user '11111'@'localhost' to databa  
  se 'forge' (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')           
                                                                               

In PDOConnection.php line 2:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user '11111'@'localhost' to databa  
  se 'forge'                                                                   
                                                                               

In PDOConnection.php line 2:
                                                                               
  SQLSTATE[HY000] [1044] Access denied for user '11111'@'localhost' to databa  
  se 'forge'

**Comment by Tai7sy** [comment]
大概率是.env文件权限不对
