### ISSUE TITLE
大佬能不能集成epusdt支付方式?

### ISSUE THREAD

**Issue by Tohkaustc** [Tai7sy/card-system#553]
https://github.com/assimon/epusdt

感觉这个要比CoinPayments要好用的多,CoinPayments因身份验证经常出现问题..
求大佬整合一下!
现在独角数卡已经支持,如果风铃发卡支持的话应该也会收获一大批用户

**Comment by BiliPrk** [comment]
你好，目前已集成有关接口。

可参阅如下地址：
https://github.com/Tai7sy/card-gateway/tree/master/Pay/EpUSDT

目前我已经完成了测试通过
如果遇到问题，请回复我或是留下联系方式

**Comment by ShawLyon** [comment]
![WechatIMG186](https://user-images.githubusercontent.com/24935255/234748296-ac05516a-42e4-4fab-801b-ddfdb9a42fcb.jpeg)
epusdt支付能成功，钱也能收到，但是报了‘支付验证失败’错误
