### ISSUE TITLE
为什么会被运营商劫持？

### ISSUE THREAD

**Issue by Murmire** [Tai7sy/card-system#555]
网站内容没违规的啊，难道是我太久没关系源码的问题吗？我是3.02

**Comment by WuMe-sicx** [comment]
正常 我已经被封2个域名了

**Comment by Tai7sy** [comment]
一刀切政策，网站名称和公告不要出现发卡两个字。卖什么都行，就是别提发卡

**Comment by WuMe-sicx** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by WilliamFWJ** [comment]
唉，我的好像也是这样，我还一直以为是我vps的问题，

除了风铃大佬说的网站名称和公告不要出现发卡两个字

大佬们还有其他办法可以规避一下这个挟持吗？ @Tai7sy @WuMe-sicx @Murmire

**Comment by Murmire** [comment]
不知道，完全看运气感觉

**Comment by Murmire** [comment]
我觉得是源码的问题了

**Comment by Murmire** [comment]
我源码版本好久没更新了

**Comment by WuMe-sicx** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
