### ISSUE TITLE
如何解决后台不显示卡密和商品，我有3100张卡密还在里面啊

### ISSUE THREAD

**Issue by black-fruit** [Tai7sy/card-system#558]
后台无数据，购买发卡正常，无法查询订单，数据库正常

其它的风铃都正常，唯独这个卡密多的站点后台和查单有问题

**Comment by Tai7sy** [comment]
数据库配错了吧，购买正常，后台没有，你卡从哪出来的，这不是搞笑呢

**Comment by black-fruit** [comment]
> 数据库配错了吧，购买正常，后台没有，你卡从哪出来的，这不是搞笑呢

不知道，但是确实就这个情况，可以提供截图

**Comment by black-fruit** [comment]
![Screenshot_20221001-074329.png](https://user-images.githubusercontent.com/77201076/193369826-0790805e-83d1-4697-95a8-d168cf34f5b5.png)![Screenshot_20221001-074356.png](https://user-images.githubusercontent.com/77201076/193369829-107d7aaf-1655-4a9d-9235-1b695fe66663.png)

**Comment by black-fruit** [comment]
![Screenshot_20221001-075130.png](https://user-images.githubusercontent.com/77201076/193370243-f0325f72-b8fd-4166-833c-a19623d49063.png)
正常创建订单和支付

**Comment by black-fruit** [comment]
不相信自己试yznl.store

**Comment by black-fruit** [comment]
如果需要可以进行漏洞复现

**Comment by Tai7sy** [comment]
方便的话，我加你看一下

**Comment by black-fruit** [comment]
OK

**Comment by black-fruit** [comment]
找到问题了，后台多账号，重置账号后正常
