### ISSUE TITLE
支付宝当面付提示验签出错

### ISSUE THREAD

**Issue by DreamVoid** [Tai7sy/card-system#564]
版本是3.15最新版，当面付APPID、支付宝公钥和应用私钥都加到配置里了，但是一发起支付就提示验签出错

![1](https://user-images.githubusercontent.com/45266046/212805005-00f5bee9-10b9-4f91-920b-774cb42427ee.png)

**Comment by BiliPrk** [comment]
通常为自己的错误，我使用最新的 3.15 版进行测试，没有出现问题，正常的支付与回调。建议检查是否填写有误。

**Comment by BiliPrk** [comment]
APPID 为纯数字，在 [支付宝开放平台](https://open.alipay.com/) 处应用名称下方。
支付宝公钥：在 [支付宝开放平台](https://open.alipay.com/) 处，应用信息 **签名** 中。
应用私钥为文件：`应用私钥RSA2048-敏感数据，请妥善保管.txt`

首次创建应用户需要审核通过后才可以使用，且需要能力 “**当面付**” 成功添加及审核并签约通过后才可以正常使用。

后台 JSON 数据：

``` json
{
  "app_id": "202301010000000",
  "alipay_public_key": "支付宝公钥",
  "merchant_private_key": "应用私钥"
}
```

[常见问题](https://github.com/Tai7sy/card-system/wiki/5.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 支付宝部分有更多你可能会遇到的问题。

前台支付图标库：[card-payway-icon](https://github.com/BiliPrk/card-payment-image)

**Comment by DreamVoid** [comment]
> APPID 为纯数字，在 [支付宝开放平台](https://open.alipay.com/) 处应用名称下方。 支付宝公钥：在 [支付宝开放平台](https://open.alipay.com/) 处，应用信息 **签名** 中。 应用私钥为文件：`应用私钥RSA2048-敏感数据，请妥善保管.txt`
> 
> 首次创建应用户需要审核通过后才可以使用，且需要能力 “**当面付**” 成功添加及审核并签约通过后才可以正常使用。
> 
> 后台 JSON 数据：
> 
> ```json
> {
>   "app_id": "202301010000000",
>   "alipay_public_key": "支付宝公钥",
>   "merchant_private_key": "应用私钥"
> }
> ```
> 
> [常见问题](https://github.com/Tai7sy/card-system/wiki/5.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 支付宝部分有更多你可能会遇到的问题。
> 
> 前台支付图标库：[card-payway-icon](https://github.com/BiliPrk/card-payment-image)

已经确认各项信息都没有问题，当面付2019年签约完毕，一周前换用另一套程序能正常支付，就是在这里一直验签失败。
或者有没有什么开关能输出调试信息，也能方便确认到底是哪里的问题。

**Comment by BiliPrk** [comment]
你留下QQ吧 我去联系你排查

**Comment by DreamVoid** [comment]
> 你留下QQ吧 我去联系你排查

GitHub不方便留QQ，麻烦给一个邮箱，我把QQ发到你的邮箱里。

**Comment by BiliPrk** [comment]
prk@prk123.com

**Comment by DreamVoid** [comment]
> [prk@prk123.com](mailto:prk@prk123.com)

已发送邮件

**Comment by BiliPrk** [comment]
问题完成 关闭
![image](https://user-images.githubusercontent.com/71644464/215745082-5030330e-d5b2-4a07-9801-45fd09c7eeda.png)
