### ISSUE TITLE
数据库初始化成功但网站500日志显示连接错误，但是初始化成功了

### ISSUE THREAD

**Issue by black-fruit** [Tai7sy/card-system#567]
<img width="1664" alt="Screen Shot 2023-02-12 at 20 12 32" src="https://user-images.githubusercontent.com/77201076/218310442-1d0347fe-a59b-44b6-a982-0c6d57ad8830.png">
<img width="1664" alt="Screen Shot 2023-02-12 at 20 13 01" src="https://user-images.githubusercontent.com/77201076/218310443-19747657-e3ae-4aaf-b522-03f226641ed5.png">
<img width="1664" alt="Screen Shot 2023-02-12 at 20 13 26" src="https://user-images.githubusercontent.com/77201076/218310444-43eddf20-5a34-42da-bf82-22ccf44c802a.png">

以上是截图

**Comment by black-fruit** [comment]
函数已经解除禁用

**Comment by BiliPrk** [comment]
方便给下QQ吗 13日晚上给你远程解决

**Comment by black-fruit** [comment]
<img width="1664" alt="Screen Shot 2023-02-12 at 20 21 59" src="https://user-images.githubusercontent.com/77201076/218310802-dd8d9c7a-076c-47e5-b47a-0f685db3717a.png">

**Comment by black-fruit** [comment]
> 方便给下QQ吗 13日晚上给你远程解决

我加你吧，我这个有限制

**Comment by BiliPrk** [comment]
1340682394
