### ISSUE TITLE
关于定时清理未支付订单

### ISSUE THREAD

**Issue by WuMe-sicx** [Tai7sy/card-system#568]
我把该命令,放入宝塔shell 执行后提示错误：
[![pSOA3s1.png](https://s1.ax1x.com/2023/02/19/pSOA3s1.png)](https://imgse.com/i/pSOA3s1)
* * * * * php 安装目录/artisan schedule:run;

**Comment by WuMe-sicx** [comment]
目录已修改为项目{发卡} 目录

**Comment by Tai7sy** [comment]
这个是正常的，程序会在凌晨自动清理

**Comment by WuMe-sicx** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by WuMe-sicx** [comment]
> 这个是正常的，程序会在凌晨自动清理

我定时该设为多少合适

**Comment by Tai7sy** [comment]
1分钟一次，这个是php框架的要求，
程序内部会有自己的定时，外部设置一分钟一次，内部到了时间会触发任务

**Comment by BiliPrk** [comment]
你好，该问题已详细的收录在[常见问题](https://github.com/Tai7sy/card-system/wiki/5.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)的 “**定时清理未支付订单** 提示 `no scheduled commands are ready to run.` 问题” 部分。

如有其它问题请及时提出，过时后该 Issues 将会被关闭，再次提出问题可重新开启 Issues 或重新发起。
