### ISSUE TITLE
老大!求救!救命! 底部版权怎么弄超链接

### ISSUE THREAD

**Issue by 9xbo** [Tai7sy/card-system#574]
整改指引
未通过原因：未按要求悬挂备案号
网站正常使用
若您的网站正在使用，您需要将备案号悬挂至网站首页底部。
#参考代码如下：
<a href="https://beian.miit.gov.cn/" target="_blank">备案号</a>

这是腾讯备案发给我的 网站首页底部备案号未链接至工信部备案官网首页；您需要将网站首页底部正确备案号链接至工信部备案官网首页。（工信部链接：https://beian.miit.gov.cn/）

然后我用他的参考代码写在底部版权上也不对
![QQ截图20230328152416](https://user-images.githubusercontent.com/87254851/228160425-ab3040ec-b280-47ae-8066-cdaad7ffeb42.png)

话说底部版权貌似只在简洁主题下才显示

**Comment by Tai7sy** [comment]
根据你不同的主题，将代码放在对应index.blade.html内
如material主题：
https://github.com/Tai7sy/card-system/blob/master/resources/views/shop_theme/Material/index.blade.php

**Comment by HamGuy** [comment]
多谢，在
```html
<div id=bkg></div>
```
后面加个div就可以了
```html
<div class="main">备案信息</div>
```

其实可以考虑在后台添加个输入备案信息后，自动关联到备案网站的处理
