### ISSUE TITLE
500未知错误

### ISSUE THREAD

**Issue by WangLing0310** [Tai7sy/card-system#575]
[card_fpm-fcgi-2023-03-30.log](https://github.com/Tai7sy/card-system/files/11113477/card_fpm-fcgi-2023-03-30.log)

**Comment by WangLing0310** [comment]
这个解决了，但是进后台就提示未知错误
![image](https://user-images.githubusercontent.com/966
[card_fpm-fcgi-2023-03-31.log](https://github.com/Tai7sy/card-system/files/11113639/card_fpm-fcgi-2023-03-31.log)
40500/228898794-e4f5408f-5f3f-4de4-a9aa-e0b725bdfe13.png)

**Comment by BiliPrk** [comment]
你好，请看常见问题，100% 能解决你的问题。

**Comment by imPrk0** [comment]
回复时间过于长久，且程序经过多人使用并无问题，该问题为用户环境问题，并非程序问题，将结束 issues，如有问题，请重新发起。
