### ISSUE TITLE
页面底部出现 "UNKNOWN CAPTCHA DRIVER" 

### ISSUE THREAD

**Issue by HamGuy** [Tai7sy/card-system#576]
不知道哪里设置出错了，刚部署的时候正常的

<img width="542" alt="image" src="https://user-images.githubusercontent.com/1592573/232262509-4dd0136d-a8e5-41d4-ab37-7289788482f5.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/1592573/232262528-0e9363ab-fdf7-4dd5-8134-8607f15dde4e.png">

另外，请问这个 `footer` 节点在哪里设置，我想自定义下 footer，找了一圈都没找到，谢谢

**Comment by BiliPrk** [comment]
这个需要看一下网络请求返回的内容是和什么相关。未知的人机验证驱动的话应该是和人机验证有关。或许可以发出站点或通过即时通讯来解决问题。建议先检查人机验证驱动部分是否有问题。再查看网络请求部分。footer 部分建议写在后台，因为前端使用 Vue.js 操作 DOM，所以你不能特别自由的通过 HTML 来自定义页脚。如果你特别熟悉 JavaScript，或许你可以在 Vue.js 渲染完页面后操作 DOM 添加自己的元素上去。

如果还有问题，请回复。

**Comment by HamGuy** [comment]
UNKNOWN CAPTCHA DRIVER 这个看了下网络请求，没有出现相关内容
自定义 footer 我参考这个 #574

**Comment by HamGuy** [comment]
刚才更新后试了下，似乎正常了
