### ISSUE TITLE
epusdt支付是成功的，钱也收到了，但是报了‘支付验证失败’错误

### ISSUE THREAD

**Issue by ShawLyon** [Tai7sy/card-system#578]
![WechatIMG186](https://user-images.githubusercontent.com/24935255/234748020-4dfcb50f-11ab-46e7-8314-2893c0fd5512.jpeg)

**Comment by ShawLyon** [comment]
对了，我的版本是3.15

**Comment by BiliPrk** [comment]
方便通过 QQ 调试问题吗

**Comment by ShawLyon** [comment]
> 方便通过 QQ 调试问题吗

可以啊，你加我361901592

**Comment by BiliPrk** [comment]
> > 方便通过 QQ 调试问题吗
> 
> 
> 
> 可以啊，你加我361901592

加了

**Comment by yiqiecongjian** [comment]
我也是遇到同样问题，可以加我qq274935559 吗，我在card-gateway 上 Issues很长时间了没有收到回复

**Comment by imPrk0** [comment]
https://github.com/Tai7sy/card-gateway/tree/master/Pay/EpUSDT
问题已经解决，如依然有问题请重新开 issues。
