### ISSUE TITLE
订单号可以直接用付款订单号吗？

### ISSUE THREAD

**Issue by cjiasu** [Tai7sy/card-system#58]
现在订单号是   20190127121835qd0tV
这样的  用付款订单号无法查询卡密

**Comment by Tai7sy** [comment]
订单号可以查询到卡密，此问题不可能存在

**Comment by cjiasu** [comment]
只能用网站订单号查  付款流水号查不了  用户也不知道网站订单号多少啊

风铃 <notifications@github.com> 于 2019年1月29日周二 下午1:11写道：

**Comment by Tai7sy** [comment]
可以到数据库里找一找，如果数据库里面也没有的话就不是程序原因了

**Comment by cjiasu** [comment]
有啊  只是那个只能用网站生成的订单号查 并不是支付宝付款的流水号

风铃 <notifications@github.com> 于 2019年1月29日周二 下午1:14写道：
