### ISSUE TITLE
关于数据库问题

### ISSUE THREAD

**Issue by WuMe-sicx** [Tai7sy/card-system#580]
Log日志如下
Mysql版本5.7
PHP版本7.3
//
另外一个服务器是5.6的数据库正常使用
> local.ERROR: Config init failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'epay.szz.cn.systems' doesn't exist (SQL: select * from `systems

**Comment by BiliPrk** [comment]
你确定是新建的库 没有写prefix吗？
它这写了 epay.szz.cn.systems 这是不对的

**Comment by WuMe-sicx** [comment]
> 你确定是新建的库 没有写prefix吗？ 它这写了 epay.szz.cn.systems 这是不对的

我是执行PHP 命令创建全新数据库的呀

**Comment by BiliPrk** [comment]
如果还没有解决 远程吧

**Comment by imPrk0** [comment]
回复时间过于长久，且程序经过多人使用并无问题，该问题为用户环境问题，并非程序问题，将结束 issues，如有问题，请重新发起。
