### ISSUE TITLE
为什么我这500错误啊，求解

### ISSUE THREAD

**Issue by ZiQingSir** [Tai7sy/card-system#584]
[card_fpm-fcgi-2023-06-15.log](https://github.com/Tai7sy/card-system/files/11757922/card_fpm-fcgi-2023-06-15.log)
[card_cli-2023-06-15.log](https://github.com/Tai7sy/card-system/files/11757923/card_cli-2023-06-15.log)

**Comment by BiliPrk** [comment]
请参阅 “常见问题” 与 “安装教程”

需注意有关 “缓存” 部分的内容！

**Comment by imPrk0** [comment]
回复时间过于长久，且程序经过多人使用并无问题，该问题为用户环境问题，并非程序问题，将结束 issues，如有问题，请重新发起。
