### ISSUE TITLE
码支付配置后，不能成功付款

### ISSUE THREAD

**Issue by singworld** [Tai7sy/card-system#59]
支付失败！
请求来源错误，请返回页面重新下单

**Comment by singworld** [comment]
原因是用了cdn

**Comment by jcx70100** [comment]
@singworld  您好，请问一下您的码支付是如何配置的呢？ 是不是只要修改id和key就可以了？我修改了一下一直无法成功支付，请教您一下您的id和key是怎么获取的？在支付宝的那个板块里可以找到？
十分感谢

**Comment by singworld** [comment]
@jcx70100 那个网站注册以后就能获取 不过好像和网络环境有关。不是每个人都能支付

**Comment by al90slj23** [comment]
请外请教下。用的码支付。上面有个 通知地址，是掉单了后手动补单后回报用。那个填啥欸~

**Comment by Tai7sy** [comment]
填写后台支付方式后面对应的通知地址

**Comment by al90slj23** [comment]
自己设定就好了么？赞欸

**Comment by Tai7sy** [comment]
填写一个就可以了, 是互通的
