### ISSUE TITLE
接口不存在

### ISSUE THREAD

**Issue by xiaozhi-boy** [Tai7sy/card-system#591]
配置了支付提示接口不存在，系统已经是最新版本，本来想改下支付插件就这样了

**Comment by WuMe-sicx** [comment]
> 配置了支付提示接口不存在，系统已经是最新版本，本来想改下支付插件就这样了

检查是否成功配置好接口

**Comment by imPrk0** [comment]
截图后台配置和提示

**Comment by WuMe-sicx** [comment]
> 截图后台配置和提示

三天前的消息了 他应该修复了
