### ISSUE TITLE
图片功能

### ISSUE THREAD

**Issue by xiaozhi-boy** [Tai7sy/card-system#592]
图片功能一直用不了，还要用图床上传引用
图片路径为/storage/images/product/x9S2kkCYMMMooce4cRQtCpuHL7hCAgMKPpS0T5sR.png
权限777root给了
但是在public中没有storage的路径
网站根目录有storage，但是里面没有/images

**Comment by Tai7sy** [comment]
1. 根据你的描述，上传部分有问题。但是如果设置了777，这部分不会出问题。

2. 实际上可能是访问有问题读不到图片，这个大概率是你用的宝塔面板里面对于jpg等静态请求的规则设置有误，请手动删除网站nginx/apache配置中关于jpg等规则
