### ISSUE TITLE
有办法在Windows下安装吗

### ISSUE THREAD

**Issue by fentianx** [Tai7sy/card-system#596]
有办法能在Windows下也能用吗

**Comment by imPrk0** [comment]
可以的 确保环境信息一致即可 剩下的就是在 PHP CLI 上

详细可以 Google 搜索一下：Laravel 5 in Windows

**Comment by fentianx** [comment]
最新不是3.15吗V2是什么

**Comment by imPrk0** [comment]
程序使用 Laravel 开发，所有的部署操作和 Laravel 同步一致。你要了解的是 Laravel 在 Windows 环境的部署方式。

Laravel 做为 PHP 第一大知名框架，社区方面毋庸置疑，有关教程也有非常多。无论 IIS 还是 Nginx 还是 Apache，在 Windows 环境上的有关教程在 Google 上有非常详细。

甚至你可以直接询问 ChatGPT 如何在 Windows 环境部署 Laravel 程序。

所有的操作其实和 Linux 雷同，在 PHP CLI 上运行命令操作，并给 PHP 安装扩展，配置好服务器软件，再配置好规则重写，其实就可以运行了。

**Comment by fentianx** [comment]
我在Windows上成功运行了但是支付提示，发生错误，下单失败，请稍后重试
<img width="637" alt="image" src="https://github.com/Tai7sy/card-system/assets/141067345/e6a5a900-44d2-4a23-9436-387029971998">

**Comment by imPrk0** [comment]
发日志
