### ISSUE TITLE
想询问一下关于material主题的一些问题【困扰很久】

### ISSUE THREAD

**Issue by heyyoulist** [Tai7sy/card-system#597]
你好风铃大佬，想请问一下如何做到如图所示修改material主题的特定文字，这个问题困扰我许久了，今天我翻遍了数据库以及所有的文件，都无法找到对应的修改位置，如下图，麻烦了，非常感谢！
![默认标题__2023-10-12+03_12_31](https://github.com/Tai7sy/card-system/assets/66654989/acb209a4-e87a-4dfe-b97c-1bb32fd66a07)

**Comment by imPrk0** [comment]
JavaScript 文件会被浏览器 Cache，改完之后 Ctrl + F5 强行刷新缓存。如果用了 CDN 也别忘记。

**Comment by heyyoulist** [comment]
![image](https://github.com/Tai7sy/card-system/assets/66654989/5e168ada-ad6c-429e-802d-8305aaac57e8)
我的失误，因为看这些是白的，再加上这主题是vue，哈哈

**Comment by imPrk0** [comment]
Webpack 打包就是这样

**Comment by heyyoulist** [comment]
大佬很详细，也很细心，但是通过全局搜索发现一共有三个字段符合，依次修改后并未发现前台有所变化，当然是排除了CDN的，因为我直接临时解析到源站ip了

**Comment by heyyoulist** [comment]
这个有点头疼，大佬还有其他位置吗

**Comment by heyyoulist** [comment]
![image](https://github.com/Tai7sy/card-system/assets/66654989/a71248d6-b1bf-429e-a776-9d89686474fc)
ok了大佬，大佬好迅速啊

**Comment by heyyoulist** [comment]
还有想问一下大佬，今天升级的3.15版本，之前一直用的3.02,版本，在3.02版本当中有个BUG，当银行卡没钱的时候使用支付宝手机支付后会正常回调，不知道这个bug在3.15版本中存在吗

**Comment by imPrk0** [comment]
我非常了解这套程序 Laravel 不会干预 Vue 的内容，这一定就是在 .js 文件中，改了就肯定好了，你就全局搜就行了，没变化99%是 cache

**Comment by imPrk0** [comment]
支付接口理论上不会有问题 因为支付宝同步或异步通知就是支付宝说这个付款了那就是付款了

理论上来说会出现这样的问题往往是支付宝的问题更大一些

你可以尝试一下 毕竟得到这样的反馈是第一次

从理论上来说是不会发生的

程序认定是否支付是来自支付宝的 callback

**Comment by heyyoulist** [comment]
恩恩，了解了，因为这个bug我也试过，在银行卡没钱的时候大概率会“白嫖”非常的离谱，哈哈，不过用了三年风铃，这种情况就发生过一次，我也很蒙蔽，最后威逼利诱买家才告诉我如何实现的，那这边就没什么问题了先关单了哈

**Comment by 14Izumi** [comment]
还想请问下,如果上了cdn,修改了无法生效,并且也强制刷新了,这种情况如何解决

**Comment by imPrk0** [comment]
上了 CDN，你确定修改了，那么 CDN 处可能存在缓存，浏览器也会存在缓存

这是个综合的问题

只要你确定已经修改那么就没什么太大问题

**Comment by 14Izumi** [comment]
好的谢谢
