### ISSUE TITLE
如何在公告位置加入自定义HTML代码

### ISSUE THREAD

**Issue by xiaozhi-boy** [Tai7sy/card-system#601]
material模板，如何在公告位置加入自定义HTML代码，以及如何在底部再加一个div显示文字，直接<p><h1>字会偏位

**Comment by imPrk0** [comment]
公告位置只支持编辑器编辑的 JSON 内容
网站底部可在 JS 代码 / 客服代码中插入 

如果你很想修改公告位置插入内容，可以学习一下 JS
