### ISSUE TITLE
新站500未知错误，前后端都无法进入，

### ISSUE THREAD

**Issue by Jayden-Pr** [Tai7sy/card-system#605]
1.php版本切换无效
2.目录权限全改777无效

以下logs文件内容
[2024-03-26 14:33:17] local.ERROR: Config init failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist (SQL: select * from `systems`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist (SQL: select * from `systems`) at /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php:2, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist at /www/wwwroot/fk.runfa.me/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist at /www/wwwroot/fk.runfa.me/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2)
[stacktrace]
#0 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(2): Illuminate\\Database\\Query\\Builder->get(Array)
#5 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(2): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#6 /www/wwwroot/fk.runfa.me/app/System.php(2): Illuminate\\Database\\Eloquent\\Builder->get()
#7 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(2): App\\System::App\\{closure}()
#8 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(2): Illuminate\\Cache\\Repository->remember('settings.all', 10, Object(Closure))
#9 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(2): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#10 /www/wwwroot/fk.runfa.me/app/System.php(2): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#11 /www/wwwroot/fk.runfa.me/app/System.php(2): App\\System::_init()
#12 /www/wwwroot/fk.runfa.me/app/Providers/ConfigServiceProvider.php(2): App\\System::_get('app_name')
#13 [internal function]: App\\Providers\\ConfigServiceProvider->boot()
#14 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(2): call_user_func_array(Array, Array)
#15 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(2): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(2): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): Illuminate\\Container\\Container->call(Array)
#19 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): Illuminate\\Foundation\\Application->bootProvider(Object(App\\Providers\\ConfigServiceProvider))
#20 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(App\\Providers\\ConfigServiceProvider), 29)
#21 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): array_walk(Array, Object(Closure))
#22 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(2): Illuminate\\Foundation\\Application->boot()
#23 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#24 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#25 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#26 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#27 /www/wwwroot/fk.runfa.me/public/index.php(62): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#28 {main}
"} 
[2024-03-26 14:33:17] local.ERROR: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist (SQL: select * from `systems`) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist (SQL: select * from `systems`) at /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php:2, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist at /www/wwwroot/fk.runfa.me/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist at /www/wwwroot/fk.runfa.me/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2)
[stacktrace]
#0 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(2): Illuminate\\Database\\Query\\Builder->get(Array)
#5 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(2): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#6 /www/wwwroot/fk.runfa.me/app/System.php(2): Illuminate\\Database\\Eloquent\\Builder->get()
#7 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(2): App\\System::App\\{closure}()
#8 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(2): Illuminate\\Cache\\Repository->remember('settings.all', 10, Object(Closure))
#9 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(2): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#10 /www/wwwroot/fk.runfa.me/app/System.php(2): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#11 /www/wwwroot/fk.runfa.me/app/System.php(2): App\\System::_init()
#12 /www/wwwroot/fk.runfa.me/app/System.php(2): App\\System::_get('maintain', NULL)
#13 /www/wwwroot/fk.runfa.me/app/Http/Controllers/Controller.php(2): App\\System::_getInt('maintain')
#14 /www/wwwroot/fk.runfa.me/app/Http/Controllers/HomeController.php(15): App\\Http\\Controllers\\Controller->checkIsInMaintain()
#15 [internal function]: App\\Http\\Controllers\\HomeController->shop()
#16 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(2): call_user_func_array(Array, Array)
#17 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(2): Illuminate\\Routing\\Controller->callAction('shop', Array)
#18 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\HomeController), 'shop')
#19 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\Route->runController()
#20 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Route->run()
#21 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/fk.runfa.me/vendor/ken/blade-minify/src/Middleware/Minify.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Ken\\BladeMinify\\Middleware\\Minify->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#27 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#29 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#30 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#31 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/fk.runfa.me/app/Http/Middleware/CORS.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): App\\Http\\Middleware\\CORS->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /www/wwwroot/fk.runfa.me/vendor/fideloper/proxy/src/TrustProxies.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /www/wwwroot/fk.runfa.me/public/index.php(62): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"} 
[2024-03-26 14:33:17] local.ERROR: Uncaught Exception {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist (SQL: select * from `systems`) at /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php:2, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist at /www/wwwroot/fk.runfa.me/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fk_runfa_me.systems' doesn't exist at /www/wwwroot/fk.runfa.me/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2)
[stacktrace]
#0 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2): Illuminate\\Database\\Query\\Builder->runSelect()
#4 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(2): Illuminate\\Database\\Query\\Builder->get(Array)
#5 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(2): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#6 /www/wwwroot/fk.runfa.me/app/System.php(2): Illuminate\\Database\\Eloquent\\Builder->get()
#7 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(2): App\\System::App\\{closure}()
#8 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(2): Illuminate\\Cache\\Repository->remember('settings.all', 10, Object(Closure))
#9 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(2): Illuminate\\Cache\\CacheManager->__call('remember', Array)
#10 /www/wwwroot/fk.runfa.me/app/System.php(2): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array)
#11 /www/wwwroot/fk.runfa.me/app/System.php(2): App\\System::_init()
#12 /www/wwwroot/fk.runfa.me/app/System.php(2): App\\System::_get('maintain', NULL)
#13 /www/wwwroot/fk.runfa.me/app/Http/Controllers/Controller.php(2): App\\System::_getInt('maintain')
#14 /www/wwwroot/fk.runfa.me/app/Http/Controllers/HomeController.php(15): App\\Http\\Controllers\\Controller->checkIsInMaintain()
#15 [internal function]: App\\Http\\Controllers\\HomeController->shop()
#16 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(2): call_user_func_array(Array, Array)
#17 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(2): Illuminate\\Routing\\Controller->callAction('shop', Array)
#18 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\HomeController), 'shop')
#19 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\Route->runController()
#20 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Route->run()
#21 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/fk.runfa.me/vendor/ken/blade-minify/src/Middleware/Minify.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Ken\\BladeMinify\\Middleware\\Minify->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#27 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#29 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#30 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#31 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/fk.runfa.me/app/Http/Middleware/CORS.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): App\\Http\\Middleware\\CORS->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /www/wwwroot/fk.runfa.me/vendor/fideloper/proxy/src/TrustProxies.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /www/wwwroot/fk.runfa.me/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /www/wwwroot/fk.runfa.me/public/index.php(62): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
","method":"GET","url":"https://fk.runfa.me","data":"","ip":"45.121.38.83","client_ip":"45.121.38.83","headers":{"accept-language":["zh-CN,zh;q=0.9"],"accept-encoding":["gzip, deflate, br, zstd"],"sec-fetch-dest":["document"],"sec-fetch-user":["?1"],"sec-fetch-mode":["navigate"],"sec-fetch-site":["cross-site"],"accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"user-agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"],"upgrade-insecure-requests":["1"],"sec-ch-ua-platform":["\"Windows\""],"sec-ch-ua-mobile":["?0"],"sec-ch-ua":["\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\""],"cache-control":["max-age=0"],"host":["fk.runfa.me"],"content-length":[""],"content-type":[""]}}

**Comment by imPrk0** [comment]
你要搞清楚前端后端和前台后台是不同的概念
通过日志来看，是没有找到你的数据表
你是否已经执行了数据库迁移命令且成功？

从你当前的状况来看，你是使用了宝塔面板建站
请查阅我之前非常详细的介绍了的安装过程，注意使用 PHP 73
https://github.com/Tai7sy/card-system/wiki/1.-%E5%AE%89%E8%A3%85%E6%95%99%E7%A8%8B%EF%BC%88%E5%AE%9D%E5%A1%94%E9%9D%A2%E6%9D%BF%EF%BC%89

如果都成功了，你可能需要查阅常见问题
https://github.com/Tai7sy/card-system/wiki/5.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

以及一些插件支持
https://github.com/Tai7sy/card-system/wiki/%E3%80%90%E6%8F%92%E4%BB%B6%E3%80%91%E4%B8%80%E4%BA%9B%E6%8F%92%E4%BB%B6%EF%BC%8C%E5%8F%AF%E4%BB%A5%E8%BE%85%E5%8A%A9%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD

**Comment by Jayden-Pr** [comment]
已自己查找解决。谢谢！
