### ISSUE TITLE
这个开源项目是停更了吗？

### ISSUE THREAD

**Issue by upn369** [Tai7sy/card-system#609]
很好的一个项目，用vue3写的，感觉就是不一样。
要是还能有多些主题模板，有手动发货，比如简单的物流功能，就完美了。

**Comment by imPrk0** [comment]
目前是停更了 或许未来会重启项目 但是可能性不大

目前该程序没有多语言 多货币 只能局限于印度用户的服务

印度用户的情况我想你也清楚 peking将发卡列入诈骗管理

而且程序是开源的 作者也赚不到钱

没有时间和精力投入一个正在被反诈中心列入管制的项目开发当中 赚不到钱是最主要的

如果你喜欢的话 未来或许可以复活它
