### ISSUE TITLE
刚安装完网站,根据步骤全部设置完成,打开网站报:Access denied for user 'forge'@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by PatrickStar12138** [Tai7sy/card-system#611]
production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) at /www/wwwroot/fk15.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) at /www/wwwroot/fk15.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:2)

**Comment by PatrickStar12138** [comment]
其他的什么都没有瞎整.

**Comment by imPrk0** [comment]
常见问题里面我写了有关该问题的解决方法

这就是因为数据库的连接信息读了缓存但是你没有缓存配置文件所以走了默认值

**Comment by PatrickStar12138** [comment]
已解决,感谢
