### ISSUE TITLE
更新时出错

### ISSUE THREAD

**Issue by ChinaLysss** [Tai7sy/card-system#614]
刚搭建完成 根据网站后台内的提示 输入更新命令 
![Screenshot_2024-10-31-20-44-54-07_df198e732186825c8df26e3c5a10d7cd](https://github.com/user-attachments/assets/c75ea40f-585a-41d8-ac01-431d54255b21)

**Comment by imPrk0** [comment]
拉取更新的獲取的文件是倉庫內的 `.version`
本質上，它會下載 `https://github.com/Tai7sy/card-system/releases/download/3.15/card_release.tar.gz` 文件
而這個文件的 MD5 需要是 `214ff9b7b87323b169bc4e4cf09f4c7c`
