### ISSUE TITLE
如何美化此项目UI？

### ISSUE THREAD

**Issue by ChinaLysss** [Tai7sy/card-system#615]
怎么给网站内窗口添加一个毛玻璃与圆角的特效 如：

![399068574-82f7659d-327b-444a-9de9-d37f8cd1f14b](https://github.com/user-attachments/assets/8d2e2442-1d44-4f23-910e-dda7f2f0f3b5)

我尝试了从后台客服代码中添加css  但是无法实现

**Comment by imPrk0** [comment]
你是要实现图片中的效果吗？

需要 CSS 没错，请确保选择器正确以及标签正确。

**Comment by ChinaLysss** [comment]
可不可以告诉我具体需要什么标签?
比如按钮 公告栏 毛玻璃等

**Comment by imPrk0** [comment]
我需要详细了解你的需求。

**Comment by ChinaLysss** [comment]
![image](https://github.com/user-attachments/assets/02d8dcd8-a156-4600-adbb-016b9b82422a)

在这个图片里，网站作者将公告栏的边框进行了圆角化，并且对商品选择也进行了圆角化，我想要知道这个边框的css标签  
并且作者还对公告栏进行了模糊，我也想知道背景的css标签。

**Comment by imPrk0** [comment]
就像 #613 提到的那样

这并非程序本身问题，不会额外修改并添加有关功能

---

但是你可以通过修改 CSS / JavaScript 来实现这个效果

在 “客服代码” 或 “统计代码” 中插入即可

如果你会 CSS 的话你会很简单的写出 “联系客服” 按钮、毛玻璃效果，以及居中按钮

既然你能问出这个问题，说明你可能并不会 CSS

---

不过你上面有写将 CSS 写进去没有效果

你已经有 CSS 了吗？

**Comment by ChinaLysss** [comment]
我尝试写css了，已经完成了模糊背景的效果，但是无法完成圆角化。

**Comment by ChinaLysss** [comment]
<style>
.content {
    backdrop-filter: blur(10px);
}
</style>

这是我所编写的 “模糊背景” 的css代码

**Comment by ChinaLysss** [comment]
![image](https://github.com/user-attachments/assets/b35dd459-d190-4ff4-899a-94f5456a8e9a)

你这里所提出的 我都已经完成 只剩下半圆角了。。

**Comment by imPrk0** [comment]
说明你的 CSS 是生效的，你的情况只有一种可能：

> [!WARNING]
> 1、选择器选错了元素
> 2、属性写错了
> 3、格式写错了

本质原因是你可能不会 CSS；我不能教你 CSS，你可以由于 CSS 并非逻辑型语言，建议自行学习 CSS。

https://developer.mozilla.org/docs/Web/CSS

通常，你需要使用选择器选择到背景元素并给一个 `border-radius` 属性。

- [https://border-radius.com](一个工具网站)

**Comment by ChinaLysss** [comment]
我现在需要这个公告栏的css标签名称与商品选择的标签名称。

**Comment by imPrk0** [comment]
我认为你应该善用浏览器开发者工具：

- [Chromium](https://www.chromium.org/teams/devtools/)
- [Safari](https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac)
- [FireFox](https://firefox-source-docs.mozilla.org/devtools-user/)
