### ISSUE TITLE
部分情况下数据库初始化失败

### ISSUE THREAD

**Issue by TachibanaSuzume** [Tai7sy/card-system#63]
提示1067 Invaild default value for ‘created_at'
把database/migrations中create_files_table和create_logs_table的->timestamp(‘created_at’);修改成->timestamps();后修复

**Comment by Tai7sy** [comment]
能否提供数据库版本来排查原因

**Comment by TachibanaSuzume** [comment]
5.6 宝塔的升级策略过于zz所以没法升级

**Comment by Tai7sy** [comment]
新版本已修复 感谢反馈
