### ISSUE TITLE
求教网站支付中的网站API地址如何填写，应改是有几个配置写错导致付款成功却识别成失败

### ISSUE THREAD

**Issue by 1404939641** [Tai7sy/card-system#64]
谢谢大佬了

**Comment by Tai7sy** [comment]
`网站API地址`在大部分情况下和`网站地址`填写一样就可以, 只不过如果你的主站地址用了防CC之类的可能会影响支付异步通知.
因此如果你的`网站地址`启用了防cc之类的, `网站API地址` 请填写一个没有启用的域名地址

**Comment by 1404939641** [comment]
嗯，谢谢大佬，基本解决了，现在新问题是付款后挂机宝没法发送异步通知，接收不到支付成功的异步通知。已经关闭防跨站保护了
