### ISSUE TITLE
求帮助，求大佬看看。部署检查了很多遍每一步，但是打开提示500.

### ISSUE THREAD

**Issue by al90slj23** [Tai7sy/card-system#67]
[card-2019-04-03.log](https://github.com/Tai7sy/card-system/files/3036292/card-2019-04-03.log)
另外能对接一个trimepay吗？
https://portal.trimepay.com/

**Comment by Tai7sy** [comment]
1. 你的配置文件(`.env`)没有正确配置数据库地址

>  - 修改 `.env` 文件无效 / 修改网站设置无效
> ```
> cd /www/wwwroot/example.com  #进入网站目录
> php artisan config:clear
> php artisan cache:clear
> ```

2. 接口已经有很多第四方支付接口了, `Fakala` 支付驱动支持所有使用本系统(商业版)的站点

**Comment by al90slj23** [comment]
老哥。感恩找到啥原因了。因为之前不知道为啥 .env 没有取消后最，生成那个key就没部署到，然后后面手动改的.env的后缀。老哥哪里捐赠啊。

**Comment by Tai7sy** [comment]
https://pay.his.cat

**Comment by al90slj23** [comment]
[添加报错.log](https://github.com/Tai7sy/card-system/files/3037822/default.log)
老哥有空帮忙看看添加卡号会提示这个。是啥原因呐~
另外用了 码支付 ，CF那边要添加什么规则吗~

**Comment by Tai7sy** [comment]
1. 你数据库不完整导致, 可以更新2.6最新版本
2. 关闭防CC
