### ISSUE TITLE
更换服务器迁移之后卡密添加失败

### ISSUE THREAD

**Issue by binbinbinye** [Tai7sy/card-system#69]
`add_cards, function fatal error: {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1305 PROCEDURE shop_binye_xyz.add_cards does not exist (SQL: call add_cards(1,6,0,0,111,0)) at /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Database/Connection.php:2, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1305 PROCEDURE shop_binye_xyz.add_cards does not exist at /www/wwwroot/shop.binye.xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:2, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1305 PROCEDURE shop_binye_xyz.add_cards does not exist at /www/wwwroot/shop.binye.xyz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:2)
[stacktrace]
#0 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->runQueryCallback('call add_cards(...', Array, Object(Closure))
#1 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Database/Connection.php(2): Illuminate\\Database\\Connection->run('call add_cards(...', Array, Object(Closure))
#2 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(2): Illuminate\\Database\\Connection->statement('call add_cards(...', Array)
#3 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(2): Illuminate\\Database\\DatabaseManager->__call('statement', Array)
#4 /www/wwwroot/shop.binye.xyz/app/Card.php(2): Illuminate\\Support\\Facades\\Facade::__callStatic('statement', Array)
#5 /www/wwwroot/shop.binye.xyz/app/Http/Controllers/Merchant/Card.php(4): App\\Card::add_cards(1, 6, 0, 0, '111', false)
#6 [internal function]: App\\Http\\Controllers\\Merchant\\Card->add(Object(Illuminate\\Http\\Request))
#7 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(2): call_user_func_array(Array, Array)
#8 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(2): Illuminate\\Routing\\Controller->callAction('add', Array)
#9 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Merchant\\Card), 'add')
#10 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Route.php(2): Illuminate\\Routing\\Route->runController()
#11 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Route->run()
#12 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 120, '1')
#21 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#37 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#38 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Router.php(2): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#39 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#40 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#41 /www/wwwroot/shop.binye.xyz/app/Http/Middleware/CORS.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): App\\Http\\Middleware\\CORS->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /www/wwwroot/shop.binye.xyz/vendor/fideloper/proxy/src/TrustProxies.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(2): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(2): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /www/wwwroot/shop.binye.xyz/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(2): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#62 /www/wwwroot/shop.binye.xyz/public/index.php(2): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#63 {main}
"}

以上是日志，是出现在更换服务器后，把之前备份的数据恢复到新服务器上就这样了，请大佬帮忙看一下，另外我想通过在线升级的方式能不能解决，但是我发现，大佬的升级脚本，下载的文档是商业版那个，不是个人版这个
[https://i.loli.net/2019/04/06/5ca824dab0748.png](url)
[https://i.loli.net/2019/04/06/5ca82552d75c6.png](url)

**Comment by Tai7sy** [comment]
说明你迁移的数据库不完整，储存过程没有迁移过去，建议使用专业的mysql管理工具
更新最新版本后，已经删除了储存过程，可以解决此问题

**Comment by binbinbinye** [comment]
谢谢大佬， 大佬看下这是直接下载的地址是不是下载的商业版源码，不是个人呀，还是说我操作的问题

**Comment by Tai7sy** [comment]
之前上传错误版本了 现在试一下

**Comment by binbinbinye** [comment]
好的，谢谢大佬
