### ISSUE TITLE
In Application.php line 635: Class 'Ken\BladeMinify\ServiceProvider' not found 

### ISSUE THREAD

**Issue by sigle0724** [Tai7sy/card-system#72]
In Application.php line 635: Class 'Ken\BladeMinify\ServiceProvider' not found 
我在安装时遇到了这个问题，并且构建数据库时也是
我的PHP版本是7.1，个人猜测是写入.env配置的问题
望大佬解答
![image](https://user-images.githubusercontent.com/42492692/55756680-b0ce3e00-5a84-11e9-8092-64f784e5a51d.png)

**Comment by Tai7sy** [comment]
vendor目录不完整，请重新安装或覆盖升级

**Comment by sigle0724** [comment]
七彩sspanel主题？

风铃 <notifications@github.com>于2019年4月16日 周二下午6:30写道：
