### ISSUE TITLE
运行 php artisan migrate:fresh --seed,显示SQLSTATE[42S02]: Base table or view not found: 1146 Table 'socloudfa.migrations' doesn't exist (SQL: select count(*) as aggregate from `migrations`)

### ISSUE THREAD

**Issue by sosomoo** [Tai7sy/card-system#73]
运行 php artisan migrate:fresh --seed,显示SQLSTATE[42S02]: Base table or view not found: 1146 Table 'socloudfa.migrations' doesn't exist (SQL: select count(*) as aggregate from `migrations`)
网上搜了很久都没找到解决办法,不知道哪里出错了,希望能解答下,谢谢

**Comment by Tai7sy** [comment]
直接运行
`php artisan migrate`试一下

**Comment by sosomoo** [comment]
也是显示这个错误,换过系统,也是一样

**Comment by Tai7sy** [comment]
那你留个联系方式我联系你吧

**Comment by sosomoo** [comment]
telegram @cloudsoso 这个行吗

**Comment by andhub-cn** [comment]
我也出现了这个错误 不知道您解决了吗 请问怎么解决的

**Comment by Tai7sy** [comment]
2.7版本已发布, 已解决此问题

**Comment by andhub-cn** [comment]
呃 现在在安装过程中执行php artisan key:generate就出现错误

**Comment by andhub-cn** [comment]
PHP Warning:  require(/data/wwwroot/JPG/api/vendor/autoload.php): failed to open stream: No such file or directory in /data/wwwroot/JPG/api/artisan on line 18

**Comment by Tai7sy** [comment]
@andhub-cn 请下载打包好的tar.gz

**Comment by andhub-cn** [comment]
我是下载的zip文件

**Comment by andhub-cn** [comment]
我直接下载的zip文件，安装出现以上错误提示

**Comment by Tai7sy** [comment]
@andhub-cn 我都说了请下载打包好的tar.gz, 你非得下载zip, 报错是正常现象

**Comment by andhub-cn** [comment]
已经安装成功 感谢

**Comment by andhub-cn** [comment]
请问有没有使用交流qq群
