### ISSUE TITLE
请问这个问题如何处理

### ISSUE THREAD

**Issue by chenglicq** [Tai7sy/card-system#74]
local.ERROR: Uncaught Exception {"Exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\Http\\Controllers\\Shop\\System' not found at /www/wwwroot/www.mytest.com/app/Http/Controllers/Shop/Product.php:2)
[stacktrace]

**Comment by Tai7sy** [comment]
这是一个临时更新导致的, 更新最新版可以解决此问题
