### ISSUE TITLE
关于当面付支付‘未知错误，请联系客服’

### ISSUE THREAD

**Issue by Tdickson3** [Tai7sy/card-system#76]
[card-2019-04-16.log](https://github.com/Tai7sy/card-system/files/3084845/card-2019-04-16.log)
申请了支付宝当面付，在支付渠道配置了支付宝当面付，依次填入了Appid,支付宝公钥，应用私钥。在支付的时候出现了错误‘未知错误，请联系客服’，500错误。

**Comment by Tai7sy** [comment]
感谢反馈, 2.62打包发布时支付宝驱动漏了一个文件, 
刚才版本已经加进去了, 覆盖更新可以解决此问题

**Comment by Tdickson3** [comment]
刚刚下载了https://github.com/Tai7sy/card-system/releases/download/2.6/card_release.tar.gz这个包，重新安装之后还是同样的错误。日志如下：
[card-2019-04-16.log](https://github.com/Tai7sy/card-system/files/3085059/card-2019-04-16.log)

**Comment by Tai7sy** [comment]
现在应该好了

**Comment by Tdickson3** [comment]
感谢大佬，已经OK了！![image](https://user-images.githubusercontent.com/44915990/56220329-d669d180-609a-11e9-873a-247a3bac7bcc.png)这里的账户余额是什么意思，还有费率百分之一。但是我测试了一下，支付1块钱之后我的支付宝确实收到了一块钱，并不是0.99呀。

**Comment by Tai7sy** [comment]
请自行配置平台内的支付通道手续费

**Comment by Tdickson3** [comment]
ok,再次感谢大佬指点！
