### ISSUE TITLE
发现两个bug

### ISSUE THREAD

**Issue by iLay1678** [Tai7sy/card-system#79]
1.升级最新版本后，无法登录，经查，在数据库user表添加role字段并设置值为admin后解决。
2.后台主题设置无法找到页面

**Comment by Tai7sy** [comment]
刚测试没有发现你这两个问题。。。

**Comment by iLay1678** [comment]
解决了，我是手动下载包更新的，重新下载了tar包更新，我之前是下载的zip包。
