### ISSUE TITLE
针对有偿使用这个接口的一些问题

### ISSUE THREAD

**Issue by CrashPluto** [Tai7sy/card-system#81]
我希望可以通过支付一些钱来请求作者能够加入一些大家所期望的新功能。
类似于：
1、Paypal、BTC、信用卡、财付通、八达通、台湾支付宝等品类更多的第三方支付接口。
2、我希望可以获得作者的联系方式。并且能够支付一定的钱来定制更多的功能。

Q：3463019424

**Comment by Tai7sy** [comment]
欢迎提出宝贵意见
