### ISSUE TITLE
能否添加一个支付渠道

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#82]
https://github.com/ChenSee/ChenPay
https://github.com/szvone/vmqphp
能否增加这两个支付渠道，感觉挺不错的，尤其是第一个

**Comment by Tai7sy** [comment]
测试了这些监视类型，均存在不稳定掉线行为(码支付已经接入，测试发现确实不稳定)，

不会在系统中加入，有需求可以发email单独定做。
