### ISSUE TITLE
建议增加优惠券优惠后价格可以为0

### ISSUE THREAD

**Issue by jihuoxia** [Tai7sy/card-system#83]
建议增加优惠券优惠后价格可以为0，直接下单发卡密
有的人没有国内的支付方式，如果给他们优惠券自己用优惠券取商品，挺不错的解决方案

**Comment by Tai7sy** [comment]
这个可以加入，但是优惠券配置不严谨可能会带来一定隐患。

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/releases/tag/2.7
已加入
