### ISSUE TITLE
希望增加支付方式默认选择一个

### ISSUE THREAD

**Issue by andhub-cn** [Tai7sy/card-system#84]
希望增加支付方式默认选择一个，前端用户在下单时候没有明显的提示，希望默认可以选择一个支付方式，那样子就不需要等用户下单收到提示后再去选择了 ，或者把支付方式选择的那个地方的UI再稍微修改一下，让用户知道在点击下单按钮之前就要选择支付方式，而不是收到提示后才知道

**Comment by Tai7sy** [comment]
> UI再稍微修改一下

能否提一些具体点的建议

**Comment by andhub-cn** [comment]
现在的ui问题是用户如果不熟悉购买流程时候，很难知道在下单页面需要选择支付方式，无论是只有一个支付方式还是更多。 如果可以做到在下单时自动选择一个，并且其他未选择的支付方式的图标为灰色（css实现），已经选择的为正常彩色并会在图片的右下角出现打勾的样式，如果可以实现的话界面会好看些，并且增加了支付方式的辨识度。感谢

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/card-system/releases/tag/2.7
