### ISSUE TITLE
集成数字货币支付（BTC, ETH, LTC, BCH, EOS等）方案

### ISSUE THREAD

**Issue by safepayment** [Tai7sy/card-system#85]
看到新版本支持比特币的版本btc.blade.php，看到了未来的曙光，有一些小的建议。

1）目前数字货币的操作门槛较高，确认时间长，用户交互很重要。经常看到一些用户付了10块钱的比特币，发现3分钟都看不到付款的情况，会比较慌。如可告诉用户支付的状态，并且在线客服实时回答会体验好。
2）支持多种币种。比如说主流货币比特币、比特现金、以太坊、莱特币等，还可以加上闪电网络，EOS等秒级确认的支付货币。
3）给商家结算稳定的币种的选项。部分商家不希望价格波动，所以给他们提供一个稳定的金额的选项。

我们有成熟友好的数字货币解决方案，方便的话我可以提交一个优化的PR？
技术交流：https://t.me/joinchat/GLKSKhUnE4GvEAPgqtChAQ

跳转付款页面：
![image](https://user-images.githubusercontent.com/50819254/58444039-afd29800-8128-11e9-8fbe-4cf4b456d775.png)

选择扫码页面：
![image](https://user-images.githubusercontent.com/50819254/58444041-b4974c00-8128-11e9-83a3-124383f44624.png)

**Comment by safepayment** [comment]
**补充一下信息：**
1) 中文操作流程：
https://github.com/bitpaydev/bitpayForSSPanelV3/blob/master/README.md
2) 商家后台[注册链接](https://merchants.mugglepay.com/user/register?ref=MP0214FL) 
3) 技术在线对接群：https://t.me/joinchat/GLKSKhUnE4GvEAPgqtChAQ
4) API文档 https://mugglepay.docs.stoplight.io
5) PHP改动案例：
https://github.com/Anankke/ss-panel-v3-mod_Uim/pull/660

**Comment by Tai7sy** [comment]
已加入

**Comment by safepayment** [comment]
@Tai7sy 感谢。请问是加载下面的git中么？好像没找到。
https://github.com/Tai7sy/card-system/tree/master/app/Library/Pay

**Comment by Tai7sy** [comment]
还没测试完，之前找了个人要了个号测试，那人忽然失联，我自己的号又要交钱开通，就暂时没发布。

**Comment by safepayment** [comment]
> 还没测试完，之前找了个人要了个号测试，那人忽然失联，我自己的号又要交钱开通，就暂时没发布。

你的账户权限应该开通了，希望可以加入下一次发布，感谢！

**Comment by Tai7sy** [comment]
@safepayment 
https://github.com/Tai7sy/card-system/tree/master/app/Library/Pay/MugglePay

**Comment by safepayment** [comment]
感谢大佬的支持！可以在Readme里面加上AFF 目前邀请奖励是（6+19）。

对于回调函数检验有个小建议。由于回调接口返回json格式，[$_POST不能获取json数据](https://stackoverflow.com/questions/8893574/php-php-input-vs-post)。需要解析为json格式，换成php://input的写法。

例如原来的写法
```
$_POST['merchant_order_id']
```
需要改为
```
$inputString = file_get_contents('php://input', 'r');
$inputStripped = str_replace(array("\r", "\n", "\t", "\v"), '', $inputString);
$inputJSON = json_decode($inputStripped, true); //convert JSON into array

$inputJSON['merchant_order_id'])
```

可以[参考](https://github.com/bitpaydev/bitpayx/blob/master/bitpayx/app/Services/Gateway/BitPayX.php#L137)


![Screen Shot 2019-07-22 at 8 08 53 PM](https://user-images.githubusercontent.com/50819254/61631333-ab57d500-acbc-11e9-8818-e3d7c71b7bf2.png)

**Comment by Tai7sy** [comment]
这个看接口文档是post，没想到是json格式数据
后面再改下吧

**Comment by safepayment** [comment]
嗯嗯。我试了一下，把$_POST改成 $inputJSON 即可。谢谢大佬！

例如原来的写法
```
$_POST['merchant_order_id']
```
需要改为
```
$inputString = file_get_contents('php://input', 'r');
$inputStripped = str_replace(array("\r", "\n", "\t", "\v"), '', $inputString);
$inputJSON = json_decode($inputStripped, true); //convert JSON into array

$inputJSON['merchant_order_id'])
```

**Comment by Tai7sy** [comment]
支付接口 repo 已经独立出来
https://github.com/Tai7sy/card-gateway/blob/master/Pay/MugglePay/Api.php

**Comment by Noah-svg** [comment]
为btc、eth等100多种币种提供API接入实现充提的企业级区块链钱包管理系统比如优盾钱包就挺好用的嘛，支持系统代付自动放款，顶级私钥boss自主掌握，子私钥动态计算不触网，很放心的昂

**Comment by safepayment** [comment]
> 为btc、eth等100多种币种提供API接入实现充提的企业级区块链钱包管理系统比如优盾钱包就挺好用的嘛，支持系统代付自动放款，顶级私钥boss自主掌握，子私钥动态计算不触网，很放心的昂

MugglePay是一个数字货币支付网关。商家可以自己选择交易所，以及选择钱包收款。

**Comment by ysn364** [comment]
这里大家可以了解下优盾钱包（https://www.uduncloud.com）。

接入：开放API  主流币种快捷接入充提 / 多语言SDK 无逢对接
安全：公钥衍生地址，私钥不触网 / 客户端主私钥双重加密 子私钥动态计算不留痕迹  /  硬件加持，纯冷操作 / 多钱包组合 充提分离
管理：账单与资产分布清楚明了，不做糊涂账 / 多级财务审核，权限灵活配置 \  操作员设备绑定，拒绝暗箱操作
便捷：一键配置策略 自动归集 /  矿工费动态调整 高中低档自由选择 / 24小时免审代付 / 双端APP支持 充提币提醒 无遗漏。
