### ISSUE TITLE
数据库路径需要修改吧

### ISSUE THREAD

**Issue by AirTed** [Tai7sy/card-system#88]
当时按照BT面板安装教程V2.X教程中，修改DB_HOST=数据库地址，为DB_HOST=127.0.0.1，运行php artisan key:generate会报错。我最后修改为DB_HOST=localhost，即可加载数据库，未报错。
请修复下，看看有没有这个问题。

**Comment by Tai7sy** [comment]
这个不是源码的问题，报错可以贴出错误内容

**Comment by AirTed** [comment]
emmm报错略过了，下次吧。下次遇到了就贴出来。问下，那个支付api怎么设置，第一次接触api接口不太会，百度google没找到详细的教程

**Comment by andhub-cn** [comment]
支付直接在后台配置既可，很简单的

**Comment by AirTed** [comment]
ok,谢了
