### ISSUE TITLE
望删除无用支付方式

### ISSUE THREAD

**Issue by andhub-cn** [Tai7sy/card-system#89]
您好，在app/Library/Pay/ 中，部分支付方式无法使用，例如meeol ，该网站因未备案早已经被拦截了，删除了一旦更新文件又会出现，希望您可以在您那里删除无用支付方式，另外我看到每次更新之后支付方法里面的变量都会随机变化，请问如果我添加了自己的支付方式 是否每次更新后都会因为变量不一致而无法使用么？类似于$speae203, $sp369aff,

**Comment by Tai7sy** [comment]
这些支付方式不影响程序功能，只有一个文件而已，对大小影响也有限(相比于vendor这些)

局部变量名是编译后的结果，不影响功能
