### ISSUE TITLE
大佬关于代码的参数命名问题

### ISSUE THREAD

**Issue by huangfengye** [Tai7sy/card-system#91]
大佬，发布代码的时候能不能别开代码混淆？？现在好多参数都混淆了，莫名其妙的看不懂啊。。

**Comment by Tai7sy** [comment]
会逐步开放。

**Comment by iLay1678** [comment]
我在新加支付接口，变量混淆弄的好多地方都搞不懂

**Comment by Tai7sy** [comment]
直接参考Demo即可，系统对支付方式做了高度的分离，无需对系统进行适配

**Comment by huangfengye** [comment]
主要是自己技术不太好，想参考下其他支付接口的写法。  如果大佬能把其他支付接口的代码不混淆也是非常不错的。。

**Comment by iLay1678** [comment]
按照demo基本上实现了，除了异步回调没弄好，目前只能用ajax主动查询

**Comment by Tai7sy** [comment]
@iLay1678
支付接口 repo 已经独立出来
https://github.com/Tai7sy/card-gateway/
