### ISSUE TITLE
修改密码提示未知错误，请查看错误日志（storage/logs）

### ISSUE THREAD

**Issue by andhub-cn** [Tai7sy/card-system#92]
在未增加默认支付方式的时候我记得成功修改了密码，但是最新版本修改密码就会提示未知错误！重新搭建也是同样提示，并且出现该错误之后无论使用新密码还是旧密码均无法登陆

Uncaught Exception {“Exception”：“[object]（Symfony \\ Component \\ Debug \\ Exception \\ FatalThrowableError（code：0）：Class'App \\ Http \\ Controllers \\ Admin \\ PasswordReset'not found at /data/wwwroot/****/app/Http/Controllers/Admin/Login.php:2）

**Comment by Tai7sy** [comment]
这是新版本的bug, 可以暂时使用命令行修改密码

**Comment by Tai7sy** [comment]
fixed with 2.73
