### ISSUE TITLE
仪表盘交易额统计存在bug

### ISSUE THREAD

**Issue by andhub-cn** [Tai7sy/card-system#94]
在后台仪表盘交易统计处，举个例子，今天的交易额是100元，前天的交易额是100元，但是如果选择那个右上角最近七天或者最近15天，他就会显示交易额为零。而不会自动累加

**Comment by Tai7sy** [comment]
请提供更多详细信息

**Comment by andhub-cn** [comment]
后台 仪表盘 概览 可以查看今日交易昨日交易以及最近7天和15天交易额。我今日交易额12 昨日12，但是最近7天交易日却显示0，最近15天也是0，没有累计最近n天交易额，而是直接显示为0

**Comment by Tai7sy** [comment]
未测试出此BUG, 
![VIckm4.png](https://s2.ax1x.com/2019/06/15/VIckm4.png)

可以自行到演示站点测试 (测试站无需支付, 支付会直接成功)
http://demo.anfaka.com
admin@qq.com/123456

**Comment by andhub-cn** [comment]
嗯嗯，是我理解错误。
我以为选择十五或者7天之后变化的部分不仅仅是下方图表。
我以为成交笔数交易额以及利润也会对15天进行累加统计显示呢。

**Comment by Tai7sy** [comment]
上方文字仅仅是 今日 昨日这两个选项
