### ISSUE TITLE
邮件判断识别问题

### ISSUE THREAD

**Issue by yi-shiyu** [Tai7sy/card-system#96]
邮件发送有些小问题，望大佬排查一下，填相同的邮箱，第一次没发邮件，第二次再买，发送了邮件。

**Comment by Tai7sy** [comment]
可以在 storage/logs/查看mail开头的日志文件

**Comment by yi-shiyu** [comment]
里面没有。只有一个card的log文件

**Comment by Tai7sy** [comment]
那就是发送成功了，可以在数据库里面查看orders的mail_sent字段

**Comment by yi-shiyu** [comment]
![QQ截图20190615125952](https://user-images.githubusercontent.com/27227092/59547203-7fcf2580-8f6d-11e9-8fec-352e24039362.jpg)
 
这么看来还是判断的问题么？

**Comment by yi-shiyu** [comment]
![sss20190615130327](https://user-images.githubusercontent.com/27227092/59547226-fec45e00-8f6d-11e9-9d21-efb63927a230.jpg)

**Comment by Tai7sy** [comment]
差不多找到了原因, 等下更新版本

**Comment by Tai7sy** [comment]
已经在2.7版本上修改了, 当前版本2.74
