### ISSUE TITLE
执行安装时出现错误

### ISSUE THREAD

**Issue by cnluminous** [Tai7sy/card-system#98]
php artisan key:generate
php artisan migrate:fresh --seed
php artisan cache:clear
执行这三句的时候全部提示
* Database connection error: SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge'

**Comment by Tai7sy** [comment]
数据库你没配置

**Comment by zeus911** [comment]
php artisan migrate:fresh --seed

报如下错：

In Container.php line 752:
                                       
  Class DatabaseSeeder does not exist
